<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Evolutionary Medicine II: Evolving Pathogens | A Primer of Evolution</title>
  <meta name="description" content="An Introduction to Evolutionary Thought: Theory, Evidence, and Practice" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Evolutionary Medicine II: Evolving Pathogens | A Primer of Evolution" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An Introduction to Evolutionary Thought: Theory, Evidence, and Practice" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Evolutionary Medicine II: Evolving Pathogens | A Primer of Evolution" />
  
  <meta name="twitter:description" content="An Introduction to Evolutionary Thought: Theory, Evidence, and Practice" />
  

<meta name="author" content="Michi Tobler" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"/>
<link rel="next" href="human-evolution.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-F33BYJVTN7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-F33BYJVTN7');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NCY5ZWLVNZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NCY5ZWLVNZ');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#in-the-light-of-evolution"><i class="fa fa-check"></i>In the Light of Evolution</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#beyond-understanding-biodiversity"><i class="fa fa-check"></i>Beyond Understanding Biodiversity</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#an-overview-of-the-semester"><i class="fa fa-check"></i>An Overview of the Semester</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-1-the-basics"><i class="fa fa-check"></i>Part 1: The Basics</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-2-a-genetic-perspective-on-evolution"><i class="fa fa-check"></i>Part 2: A Genetic Perspective on Evolution</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-3-evolutionary-outcomes-in-the-real-world"><i class="fa fa-check"></i>Part 3: Evolutionary Outcomes in the Real World</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-4-applied-evolutionary-biology"><i class="fa fa-check"></i>Part 4: Applied Evolutionary Biology</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i>How to Use This Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html"><i class="fa fa-check"></i>Front Matters</a>
<ul>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html#copyright"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="part"><span><b>I Basic Concepts</b></span></li>
<li class="chapter" data-level="1" data-path="what-evolution-is.html"><a href="what-evolution-is.html"><i class="fa fa-check"></i><b>1</b> What Evolution Is</a>
<ul>
<li class="chapter" data-level="1.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#darwin-and-the-conception-of-a-new-idea"><i class="fa fa-check"></i><b>1.1</b> Darwin and the Conception of a New Idea</a></li>
<li class="chapter" data-level="1.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#two-fundamental-insights"><i class="fa fa-check"></i><b>1.2</b> Two Fundamental Insights</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#predictions"><i class="fa fa-check"></i><b>1.2.1</b> The Pattern: Evolution is Descent with Modification</a></li>
<li class="chapter" data-level="1.2.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#the-process-natural-selection-is-a-mechanism-of-evolution"><i class="fa fa-check"></i><b>1.2.2</b> The Process: Natural Selection is a Mechanism of Evolution</a></li>
<li class="chapter" data-level="1.2.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#distinguishing-between-pattern-and-process"><i class="fa fa-check"></i><b>1.2.3</b> Distinguishing between Pattern and Process</a></li>
<li class="chapter" data-level="1.2.4" data-path="what-evolution-is.html"><a href="what-evolution-is.html#population-thinking"><i class="fa fa-check"></i><b>1.2.4</b> Population Thinking</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#practical-skills-getting-started-with-r"><i class="fa fa-check"></i><b>1.3</b> Practical Skills: Getting Started with R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#what-are-r-and-rstudio"><i class="fa fa-check"></i><b>1.3.1</b> What are R and RStudio?</a></li>
<li class="chapter" data-level="1.3.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#installing-r"><i class="fa fa-check"></i><b>1.3.2</b> Installing R</a></li>
<li class="chapter" data-level="1.3.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#installing-rstudio"><i class="fa fa-check"></i><b>1.3.3</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.3.4" data-path="what-evolution-is.html"><a href="what-evolution-is.html#checking-the-successful-installation"><i class="fa fa-check"></i><b>1.3.4</b> Checking the Successful Installation</a></li>
<li class="chapter" data-level="1.3.5" data-path="what-evolution-is.html"><a href="what-evolution-is.html#some-r-and-rstudio-basics"><i class="fa fa-check"></i><b>1.3.5</b> Some R and RStudio Basics</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="what-evolution-is.html"><a href="what-evolution-is.html#additional-resources"><i class="fa fa-check"></i><b>1.4</b> Additional Resources</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#alternative-evolution-textbooks"><i class="fa fa-check"></i><b>1.4.1</b> Alternative Evolution Textbooks</a></li>
<li class="chapter" data-level="1.4.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#evolution-in-the-primary-literature-and-the-news"><i class="fa fa-check"></i><b>1.4.2</b> Evolution in the Primary Literature and the News</a></li>
<li class="chapter" data-level="1.4.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#r-and-rstudio-resources"><i class="fa fa-check"></i><b>1.4.3</b> R and RStudio Resources</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="what-evolution-is.html"><a href="what-evolution-is.html#reflection-questions"><i class="fa fa-check"></i><b>1.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="1.6" data-path="what-evolution-is.html"><a href="what-evolution-is.html#references-1"><i class="fa fa-check"></i><b>1.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html"><i class="fa fa-check"></i><b>2</b> Evidence for Evolution</a>
<ul>
<li class="chapter" data-level="2.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#microevolution"><i class="fa fa-check"></i><b>2.1</b> Microevolution</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#the-case-of-threespine-stickleback"><i class="fa fa-check"></i><b>2.1.1</b> The Case of Threespine Stickleback</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#speciation"><i class="fa fa-check"></i><b>2.2</b> Speciation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#ring-species"><i class="fa fa-check"></i><b>2.2.1</b> Ring Species</a></li>
<li class="chapter" data-level="2.2.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#catching-speciation-in-action"><i class="fa fa-check"></i><b>2.2.2</b> Catching Speciation in Action</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#macroevolution"><i class="fa fa-check"></i><b>2.3</b> Macroevolution</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#geographic-and-temporal-patterns-of-succession"><i class="fa fa-check"></i><b>2.3.1</b> Geographic and Temporal Patterns of Succession</a></li>
<li class="chapter" data-level="2.3.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#transitional-fossils"><i class="fa fa-check"></i><b>2.3.2</b> Transitional Fossils</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#common-ancestry-and-homology"><i class="fa fa-check"></i><b>2.4</b> Common Ancestry and Homology</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#shared-flaws"><i class="fa fa-check"></i><b>2.4.1</b> Shared Flaws</a></li>
<li class="chapter" data-level="2.4.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#why-homologies-matter"><i class="fa fa-check"></i><b>2.4.2</b> Why Homologies Matter</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#deep-time"><i class="fa fa-check"></i><b>2.5</b> Deep Time</a></li>
<li class="chapter" data-level="2.6" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#tiktaalik"><i class="fa fa-check"></i><b>2.6</b> Correspondence of Different Lines of Evidence</a></li>
<li class="chapter" data-level="2.7" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#absence-of-evidence"><i class="fa fa-check"></i><b>2.7</b> Absence of Evidence…</a></li>
<li class="chapter" data-level="2.8" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#case-study-darwins-finches"><i class="fa fa-check"></i><b>2.8</b> Case Study: Darwin’s Finches</a></li>
<li class="chapter" data-level="2.9" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#practical-skills-r-notebooks-and-plotting-with-ggplot"><i class="fa fa-check"></i><b>2.9</b> Practical Skills: R Notebooks and Plotting with ggplot</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#r-notebooks"><i class="fa fa-check"></i><b>2.9.1</b> R Notebooks</a></li>
<li class="chapter" data-level="2.9.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#libraries"><i class="fa fa-check"></i><b>2.9.2</b> Using Libraries</a></li>
<li class="chapter" data-level="2.9.3" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#import-data"><i class="fa fa-check"></i><b>2.9.3</b> Importing Data</a></li>
<li class="chapter" data-level="2.9.4" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#graphing-data"><i class="fa fa-check"></i><b>2.9.4</b> Graphing Data</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#reflection-questions-1"><i class="fa fa-check"></i><b>2.10</b> Reflection Questions</a></li>
<li class="chapter" data-level="2.11" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#references-2"><i class="fa fa-check"></i><b>2.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html"><i class="fa fa-check"></i><b>3</b> A Mechanism for Change</a>
<ul>
<li class="chapter" data-level="3.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#darwins-logic"><i class="fa fa-check"></i><b>3.1</b> Darwin’s Logic</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#variation"><i class="fa fa-check"></i><b>3.1.1</b> Variation</a></li>
<li class="chapter" data-level="3.1.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#heritability"><i class="fa fa-check"></i><b>3.1.2</b> Heritability</a></li>
<li class="chapter" data-level="3.1.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#the-struggle-for-existence"><i class="fa fa-check"></i><b>3.1.3</b> The Struggle for Existence</a></li>
<li class="chapter" data-level="3.1.4" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#non-random-survival-and-reproduction"><i class="fa fa-check"></i><b>3.1.4</b> Non-Random Survival and Reproduction</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#putting-darwins-logic-to-the-test"><i class="fa fa-check"></i><b>3.2</b> Putting Darwin’s Logic to the Test</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-there-variation-in-beak-size"><i class="fa fa-check"></i><b>3.2.1</b> Is there Variation in Beak Size?</a></li>
<li class="chapter" data-level="3.2.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-variation-in-beak-size-heritable"><i class="fa fa-check"></i><b>3.2.2</b> Is Variation in Beak Size Heritable?</a></li>
<li class="chapter" data-level="3.2.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-there-a-struggle-for-existence"><i class="fa fa-check"></i><b>3.2.3</b> Is there a Struggle for Existence?</a></li>
<li class="chapter" data-level="3.2.4" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-survival-non-random"><i class="fa fa-check"></i><b>3.2.4</b> Is Survival Non-Random?</a></li>
<li class="chapter" data-level="3.2.5" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#did-non-random-survival-lead-to-evolution"><i class="fa fa-check"></i><b>3.2.5</b> Did Non-Random Survival Lead to Evolution?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#case-study-exploring-among-population-variation"><i class="fa fa-check"></i><b>3.3</b> Case Study: Exploring Among-Population Variation</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#the-cave-molly-and-its-ancestors"><i class="fa fa-check"></i><b>3.3.1</b> The Cave Molly and its Ancestors</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#practical-skills-number-sequences-allometry-and-histograms"><i class="fa fa-check"></i><b>3.4</b> Practical Skills: Number Sequences, Allometry, and Histograms</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#number-sequences"><i class="fa fa-check"></i><b>3.4.1</b> Number Sequences</a></li>
<li class="chapter" data-level="3.4.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#allometry-residuals"><i class="fa fa-check"></i><b>3.4.2</b> Allometry &amp; Residuals</a></li>
<li class="chapter" data-level="3.4.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#histograms-and-density-functions"><i class="fa fa-check"></i><b>3.4.3</b> Histograms and Density Functions</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#reflection-questions-2"><i class="fa fa-check"></i><b>3.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="3.6" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#references-3"><i class="fa fa-check"></i><b>3.6</b> References</a></li>
</ul></li>
<li class="part"><span><b>II A Genetic Perspective on Evolution</b></span></li>
<li class="chapter" data-level="4" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html"><i class="fa fa-check"></i><b>4</b> The Raw Materials for Evolution</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#the-genotype-phenotype-gap"><i class="fa fa-check"></i><b>4.1</b> The Genotype-Phenotype Gap</a></li>
<li class="chapter" data-level="4.2" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#mutation-the-fundamental-source-of-novelty"><i class="fa fa-check"></i><b>4.2</b> Mutation: The Fundamental Source of Novelty</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#point-mutations"><i class="fa fa-check"></i><b>4.2.1</b> Point Mutations</a></li>
<li class="chapter" data-level="4.2.2" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#inversions"><i class="fa fa-check"></i><b>4.2.2</b> Inversions</a></li>
<li class="chapter" data-level="4.2.3" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#gene-duplication"><i class="fa fa-check"></i><b>4.2.3</b> Gene Duplication</a></li>
<li class="chapter" data-level="4.2.4" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#genome-duplication"><i class="fa fa-check"></i><b>4.2.4</b> Genome Duplication</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#mutation-rates"><i class="fa fa-check"></i><b>4.3</b> Mutation Rates</a></li>
<li class="chapter" data-level="4.4" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#quantifying-genetic-variation"><i class="fa fa-check"></i><b>4.4</b> Quantifying Genetic Variation</a></li>
<li class="chapter" data-level="4.5" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#a-null-model-for-evolution"><i class="fa fa-check"></i><b>4.5</b> A Null Model for Evolution</a></li>
<li class="chapter" data-level="4.6" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#case-study-hardy-weinberg-equilirbium"><i class="fa fa-check"></i><b>4.6</b> Case Study: Hardy-Weinberg Equilirbium</a></li>
<li class="chapter" data-level="4.7" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#practical-skills-number-sequences-2.0-and-complex-graphs"><i class="fa fa-check"></i><b>4.7</b> Practical Skills: Number Sequences 2.0 and Complex Graphs</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#number-sequences-1"><i class="fa fa-check"></i><b>4.7.1</b> Number Sequences</a></li>
<li class="chapter" data-level="4.7.2" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#layering-data-sets"><i class="fa fa-check"></i><b>4.7.2</b> Layering Data Sets</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#reflection-questions-3"><i class="fa fa-check"></i><b>4.8</b> Reflection Questions</a></li>
<li class="chapter" data-level="4.9" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#references-4"><i class="fa fa-check"></i><b>4.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html"><i class="fa fa-check"></i><b>5</b> Evolutionary Mechanisms I: Modeling Selection</a>
<ul>
<li class="chapter" data-level="5.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#the-effects-of-selection"><i class="fa fa-check"></i><b>5.1</b> The Effects of Selection</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#frequency-dependent-selection"><i class="fa fa-check"></i><b>5.1.1</b> Frequency-Dependent Selection</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#modeling-the-effects-of-selection"><i class="fa fa-check"></i><b>5.2</b> Modeling the Effects of Selection</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#relative-fitness"><i class="fa fa-check"></i><b>5.2.1</b> Relative Fitness</a></li>
<li class="chapter" data-level="5.2.2" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#calculating-allele-frequency-changes"><i class="fa fa-check"></i><b>5.2.2</b> Calculating Allele Frequency Changes</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#case-study-modeling-selection"><i class="fa fa-check"></i><b>5.3</b> Case Study: Modeling Selection</a></li>
<li class="chapter" data-level="5.4" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#practical-skills"><i class="fa fa-check"></i><b>5.4</b> Practical Skills: Modeling Selection</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#modeling-selection"><i class="fa fa-check"></i><b>5.4.1</b> Modeling Selection</a></li>
<li class="chapter" data-level="5.4.2" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#running-multiple-selection-models"><i class="fa fa-check"></i><b>5.4.2</b> Running Multiple Selection Models</a></li>
<li class="chapter" data-level="5.4.3" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#frequency-dependent-selection-1"><i class="fa fa-check"></i><b>5.4.3</b> Frequency-Dependent Selection</a></li>
<li class="chapter" data-level="5.4.4" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#understanding-equilibria"><i class="fa fa-check"></i><b>5.4.4</b> Understanding Equilibria</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#reflection-questions-4"><i class="fa fa-check"></i><b>5.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="5.6" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#references-5"><i class="fa fa-check"></i><b>5.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><i class="fa fa-check"></i><b>6</b> Evolutionary Mechanisms II: Mutation, Genetic Drift, Migration, and Non-Random Mating</a>
<ul>
<li class="chapter" data-level="6.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#mutation-the-force-creating-novelty"><i class="fa fa-check"></i><b>6.1</b> Mutation: The Force Creating Novelty</a></li>
<li class="chapter" data-level="6.2" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#genetic-drift-the-random-force"><i class="fa fa-check"></i><b>6.2</b> Genetic Drift: The Random Force</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#interactions-between-drift-and-selection"><i class="fa fa-check"></i><b>6.2.1</b> Interactions Between Drift and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#migration-the-homogenizing-force"><i class="fa fa-check"></i><b>6.3</b> Migration: The Homogenizing Force</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#interactions-between-migration-and-selection"><i class="fa fa-check"></i><b>6.3.1</b> Interactions Between Migration and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#non-random-mating-not-much-of-a-force"><i class="fa fa-check"></i><b>6.4</b> Non-Random Mating: Not Much of a Force</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#interactions-between-inbreeding-and-selection"><i class="fa fa-check"></i><b>6.4.1</b> Interactions between Inbreeding and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#case-study-background-beyond-selection"><i class="fa fa-check"></i><b>6.5</b> Case Study Background: Beyond Selection</a></li>
<li class="chapter" data-level="6.6" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#practical-skills-modeling-mutation-drift-and-selection"><i class="fa fa-check"></i><b>6.6</b> Practical Skills: Modeling Mutation, Drift, and Selection</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#modeling-mutation-and-selection"><i class="fa fa-check"></i><b>6.6.1</b> Modeling Mutation and Selection</a></li>
<li class="chapter" data-level="6.6.2" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#modeling-genetic-drift"><i class="fa fa-check"></i><b>6.6.2</b> Modeling Genetic Drift</a></li>
<li class="chapter" data-level="6.6.3" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#modeling-genetic-drift-and-selection"><i class="fa fa-check"></i><b>6.6.3</b> Modeling Genetic Drift and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#reflection-questions-5"><i class="fa fa-check"></i><b>6.7</b> Reflection Questions</a></li>
<li class="chapter" data-level="6.8" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#references-6"><i class="fa fa-check"></i><b>6.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html"><i class="fa fa-check"></i><b>7</b> Evolution of DNA Sequences</a>
<ul>
<li class="chapter" data-level="7.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#dna-alignment-and-genome-assembly"><i class="fa fa-check"></i><b>7.1</b> DNA Alignment and Genome Assembly</a></li>
<li class="chapter" data-level="7.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#reconstructing-history-phylogenetic-trees"><i class="fa fa-check"></i><b>7.2</b> Reconstructing History: Phylogenetic Trees</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#molecular-phylogenies"><i class="fa fa-check"></i><b>7.2.1</b> Molecular Phylogenies</a></li>
<li class="chapter" data-level="7.2.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#molecular-phylogenies-in-real-life"><i class="fa fa-check"></i><b>7.2.2</b> Molecular Phylogenies in Real Life</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#the-neutral-theory"><i class="fa fa-check"></i><b>7.3</b> The Neutral Theory</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#molecular-clocks"><i class="fa fa-check"></i><b>7.3.1</b> Molecular Clocks</a></li>
<li class="chapter" data-level="7.3.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#detecting-signatures-of-selection"><i class="fa fa-check"></i><b>7.3.2</b> Detecting Signatures of Selection</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#case-study-sars-cov-2"><i class="fa fa-check"></i><b>7.4</b> Case Study: SARS-CoV-2</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#host-pathogen-coevolution"><i class="fa fa-check"></i><b>7.4.1</b> Host-Pathogen Coevolution</a></li>
<li class="chapter" data-level="7.4.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#the-evolution-of-the-seasonal-flu"><i class="fa fa-check"></i><b>7.4.2</b> The Evolution of the Seasonal Flu</a></li>
<li class="chapter" data-level="7.4.3" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#high-virulence-flu-strains"><i class="fa fa-check"></i><b>7.4.3</b> High-Virulence Flu Strains</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#practical-skills-working-with-phylogenetic-trees"><i class="fa fa-check"></i><b>7.5</b> Practical Skills: Working with Phylogenetic Trees</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#installing-dependencies"><i class="fa fa-check"></i><b>7.5.1</b> Installing Dependencies</a></li>
<li class="chapter" data-level="7.5.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#the-pipe-operator"><i class="fa fa-check"></i><b>7.5.2</b> The Pipe Operator</a></li>
<li class="chapter" data-level="7.5.3" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#importing-a-tree"><i class="fa fa-check"></i><b>7.5.3</b> Importing a Tree</a></li>
<li class="chapter" data-level="7.5.4" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#plotting-a-tree"><i class="fa fa-check"></i><b>7.5.4</b> Plotting a Tree</a></li>
<li class="chapter" data-level="7.5.5" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#annotating-a-tree"><i class="fa fa-check"></i><b>7.5.5</b> Annotating a Tree</a></li>
<li class="chapter" data-level="7.5.6" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#calculating-the-distance-to-root"><i class="fa fa-check"></i><b>7.5.6</b> Calculating the Distance to Root</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#reflection-questions-6"><i class="fa fa-check"></i><b>7.6</b> Reflection Questions</a></li>
<li class="chapter" data-level="7.7" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#references-7"><i class="fa fa-check"></i><b>7.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html"><i class="fa fa-check"></i><b>8</b> The Evolution of Quantitative Traits</a>
<ul>
<li class="chapter" data-level="8.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#qualitative-traits-and-epistasis"><i class="fa fa-check"></i><b>8.1</b> Qualitative Traits and Epistasis</a></li>
<li class="chapter" data-level="8.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantitative-traits-a-product-of-genes-and-environment"><i class="fa fa-check"></i><b>8.2</b> Quantitative Traits: a Product of Genes and Environment</a></li>
<li class="chapter" data-level="8.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantitative-trait-evolution"><i class="fa fa-check"></i><b>8.3</b> Quantitative Trait Evolution</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantifying-trait-heritability"><i class="fa fa-check"></i><b>8.3.1</b> Quantifying Trait Heritability</a></li>
<li class="chapter" data-level="8.3.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantifying-the-strength-of-selection"><i class="fa fa-check"></i><b>8.3.2</b> Quantifying the Strength of Selection</a></li>
<li class="chapter" data-level="8.3.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#calculating-the-response-to-selection"><i class="fa fa-check"></i><b>8.3.3</b> Calculating the Response to Selection</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#modes-of-selection-on-quantitative-traits"><i class="fa fa-check"></i><b>8.4</b> Modes of Selection on Quantitative Traits</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#directional-selection"><i class="fa fa-check"></i><b>8.4.1</b> Directional Selection</a></li>
<li class="chapter" data-level="8.4.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#stabilizing-selection"><i class="fa fa-check"></i><b>8.4.2</b> Stabilizing Selection</a></li>
<li class="chapter" data-level="8.4.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#disruptive-selection"><i class="fa fa-check"></i><b>8.4.3</b> Disruptive Selection</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#identifying-genes-underlying-quantitative-traits"><i class="fa fa-check"></i><b>8.5</b> Identifying Genes Underlying Quantitative Traits</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#qtl-mapping"><i class="fa fa-check"></i><b>8.5.1</b> QTL Mapping</a></li>
<li class="chapter" data-level="8.5.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#gwas"><i class="fa fa-check"></i><b>8.5.2</b> GWAS</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#case-study-quantitative-genetics"><i class="fa fa-check"></i><b>8.6</b> Case Study: Quantitative Genetics</a></li>
<li class="chapter" data-level="8.7" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#practical-skills-qtl-mapping"><i class="fa fa-check"></i><b>8.7</b> Practical Skills: QTL Mapping</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#installing-dependencies-1"><i class="fa fa-check"></i><b>8.7.1</b> Installing Dependencies</a></li>
<li class="chapter" data-level="8.7.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#read-qtl-data"><i class="fa fa-check"></i><b>8.7.2</b> Read QTL Data</a></li>
<li class="chapter" data-level="8.7.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#explore-the-data-genotypes-loci-linkage-map"><i class="fa fa-check"></i><b>8.7.3</b> Explore the Data: Genotypes, Loci &amp; Linkage Map</a></li>
<li class="chapter" data-level="8.7.4" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#explore-the-data-phenotypes"><i class="fa fa-check"></i><b>8.7.4</b> Explore the Data: Phenotypes</a></li>
<li class="chapter" data-level="8.7.5" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#qtl-scan"><i class="fa fa-check"></i><b>8.7.5</b> QTL Scan</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#reflection-questions-7"><i class="fa fa-check"></i><b>8.8</b> Reflection Questions</a></li>
<li class="chapter" data-level="8.9" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#references-8"><i class="fa fa-check"></i><b>8.9</b> References</a></li>
</ul></li>
<li class="part"><span><b>III Evolution in the Real World</b></span></li>
<li class="chapter" data-level="9" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html"><i class="fa fa-check"></i><b>9</b> Adaptation and Phenotypic Plasticity</a>
<ul>
<li class="chapter" data-level="9.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#inferring-adaptation"><i class="fa fa-check"></i><b>9.1</b> Inferring Adaptation</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#interspecific-comparisons"><i class="fa fa-check"></i><b>9.1.1</b> Interspecific Comparisons</a></li>
<li class="chapter" data-level="9.1.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#intraspecific-studies"><i class="fa fa-check"></i><b>9.1.2</b> Intraspecific Studies</a></li>
<li class="chapter" data-level="9.1.3" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#local-adaptation-within-species"><i class="fa fa-check"></i><b>9.1.3</b> Local Adaptation within Species</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#phenotypic-plasticity"><i class="fa fa-check"></i><b>9.2</b> Phenotypic Plasticity</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#types-of-phenotypic-plasticity"><i class="fa fa-check"></i><b>9.2.1</b> Types of Phenotypic Plasticity</a></li>
<li class="chapter" data-level="9.2.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#reaction-norms-and-the-evolution-of-plasticity"><i class="fa fa-check"></i><b>9.2.2</b> Reaction Norms and the Evolution of Plasticity</a></li>
<li class="chapter" data-level="9.2.3" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#adaptive-and-maladaptive-phenotypic-plasticity"><i class="fa fa-check"></i><b>9.2.3</b> Adaptive and Maladaptive Phenotypic Plasticity</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#case-study-local-adaptation-and-phenotypic-plasticity"><i class="fa fa-check"></i><b>9.3</b> Case Study: Local Adaptation and Phenotypic Plasticity</a></li>
<li class="chapter" data-level="9.4" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#practical-skills-more-variables-more-graphs"><i class="fa fa-check"></i><b>9.4</b> Practical Skills: More Variables, More Graphs</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#example-1-many-independent-variables"><i class="fa fa-check"></i><b>9.4.1</b> Example 1: Many Independent Variables</a></li>
<li class="chapter" data-level="9.4.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#example-2-many-dependent-variables"><i class="fa fa-check"></i><b>9.4.2</b> Example 2: Many Dependent Variables</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#reflection-questions-8"><i class="fa fa-check"></i><b>9.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="9.6" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#references-9"><i class="fa fa-check"></i><b>9.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html"><i class="fa fa-check"></i><b>10</b> Social Behavior and Sexual Selection</a>
<ul>
<li class="chapter" data-level="10.1" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#social-behavior"><i class="fa fa-check"></i><b>10.1</b> Social Behavior</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#kin-selection"><i class="fa fa-check"></i><b>10.1.1</b> Kin Selection</a></li>
<li class="chapter" data-level="10.1.2" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#reciprocal-altruism"><i class="fa fa-check"></i><b>10.1.2</b> Reciprocal Altruism</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#sexual-selection"><i class="fa fa-check"></i><b>10.2</b> Sexual Selection</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#causes-of-sexual-selection"><i class="fa fa-check"></i><b>10.2.1</b> Causes of Sexual Selection</a></li>
<li class="chapter" data-level="10.2.2" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#intrasexual-selection-male-male-competition"><i class="fa fa-check"></i><b>10.2.2</b> Intrasexual Selection: Male-Male Competition</a></li>
<li class="chapter" data-level="10.2.3" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#sexual-conflict"><i class="fa fa-check"></i><b>10.2.3</b> Sexual Conflict</a></li>
<li class="chapter" data-level="10.2.4" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#intersexual-selection-female-mate-choice"><i class="fa fa-check"></i><b>10.2.4</b> Intersexual Selection: Female Mate Choice</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#case-study-altruism-and-sexual-selection"><i class="fa fa-check"></i><b>10.3</b> Case Study: Altruism and Sexual Selection</a></li>
<li class="chapter" data-level="10.4" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#reflection-questions-9"><i class="fa fa-check"></i><b>10.4</b> Reflection Questions</a></li>
<li class="chapter" data-level="10.5" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#references-10"><i class="fa fa-check"></i><b>10.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="speciation-1.html"><a href="speciation-1.html"><i class="fa fa-check"></i><b>11</b> Speciation</a>
<ul>
<li class="chapter" data-level="11.1" data-path="speciation-1.html"><a href="speciation-1.html#species-and-species-concepts"><i class="fa fa-check"></i><b>11.1</b> Species and Species Concepts</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="speciation-1.html"><a href="speciation-1.html#the-biological-species-concept"><i class="fa fa-check"></i><b>11.1.1</b> The Biological Species Concept</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="speciation-1.html"><a href="speciation-1.html#speciation-as-a-gradual-process"><i class="fa fa-check"></i><b>11.2</b> Speciation as a Gradual Process</a></li>
<li class="chapter" data-level="11.3" data-path="speciation-1.html"><a href="speciation-1.html#mechanisms-of-reproductive-isolation"><i class="fa fa-check"></i><b>11.3</b> Mechanisms of Reproductive Isolation</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="speciation-1.html"><a href="speciation-1.html#pre-mating-isolation"><i class="fa fa-check"></i><b>11.3.1</b> Pre-Mating Isolation</a></li>
<li class="chapter" data-level="11.3.2" data-path="speciation-1.html"><a href="speciation-1.html#post-mating-pre-zygotic-isolation"><i class="fa fa-check"></i><b>11.3.2</b> Post-Mating, Pre-zygotic Isolation</a></li>
<li class="chapter" data-level="11.3.3" data-path="speciation-1.html"><a href="speciation-1.html#post-zygotic-isolation"><i class="fa fa-check"></i><b>11.3.3</b> Post-Zygotic Isolation</a></li>
<li class="chapter" data-level="11.3.4" data-path="speciation-1.html"><a href="speciation-1.html#reproductive-isolation-as-a-complex-trait"><i class="fa fa-check"></i><b>11.3.4</b> Reproductive Isolation as a Complex Trait</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="speciation-1.html"><a href="speciation-1.html#the-evolution-of-reproductive-isolation"><i class="fa fa-check"></i><b>11.4</b> The Evolution of Reproductive Isolation</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="speciation-1.html"><a href="speciation-1.html#polyploidization-and-instantaneous-speciation"><i class="fa fa-check"></i><b>11.4.1</b> Polyploidization and Instantaneous Speciation</a></li>
<li class="chapter" data-level="11.4.2" data-path="speciation-1.html"><a href="speciation-1.html#allopatric-speciation-and-hybridization"><i class="fa fa-check"></i><b>11.4.2</b> Allopatric Speciation and Hybridization</a></li>
<li class="chapter" data-level="11.4.3" data-path="speciation-1.html"><a href="speciation-1.html#ecological-speciation"><i class="fa fa-check"></i><b>11.4.3</b> Ecological Speciation</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="speciation-1.html"><a href="speciation-1.html#adaptive-radiation"><i class="fa fa-check"></i><b>11.5</b> Adaptive Radiation</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="speciation-1.html"><a href="speciation-1.html#african-cichlid-fishes"><i class="fa fa-check"></i><b>11.5.1</b> African Cichlid Fishes</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="speciation-1.html"><a href="speciation-1.html#case-study-speciation"><i class="fa fa-check"></i><b>11.6</b> Case Study: Speciation</a></li>
<li class="chapter" data-level="11.7" data-path="speciation-1.html"><a href="speciation-1.html#practical-skills-interpreting-structure-plots"><i class="fa fa-check"></i><b>11.7</b> Practical Skills: Interpreting Structure Plots</a></li>
<li class="chapter" data-level="11.8" data-path="speciation-1.html"><a href="speciation-1.html#reflection-questions-10"><i class="fa fa-check"></i><b>11.8</b> Reflection Questions</a></li>
<li class="chapter" data-level="11.9" data-path="speciation-1.html"><a href="speciation-1.html#references-11"><i class="fa fa-check"></i><b>11.9</b> References</a></li>
</ul></li>
<li class="part"><span><b>IV Applied Evolutionary Biology</b></span></li>
<li class="chapter" data-level="12" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><i class="fa fa-check"></i><b>12</b> Evolutionary Medicine I: Aging and Diseases of Civilization</a>
<ul>
<li class="chapter" data-level="12.1" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#darwinian-medicine"><i class="fa fa-check"></i><b>12.1</b> Darwinian Medicine</a></li>
<li class="chapter" data-level="12.2" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#diseases-of-civilization"><i class="fa fa-check"></i><b>12.2</b> Diseases of Civilization</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#modern-hunter-gatherers-and-urbanites"><i class="fa fa-check"></i><b>12.2.1</b> Modern Hunter-Gatherers and Urbanites</a></li>
<li class="chapter" data-level="12.2.2" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#old-adaptations-in-a-modern-world"><i class="fa fa-check"></i><b>12.2.2</b> Old Adaptations in a Modern World</a></li>
<li class="chapter" data-level="12.2.3" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#an-example-breast-cancer"><i class="fa fa-check"></i><b>12.2.3</b> An Example: Breast Cancer</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#why-we-age-and-die"><i class="fa fa-check"></i><b>12.3</b> Why We Age… and Die</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#rate-of-living-hypothesis"><i class="fa fa-check"></i><b>12.3.1</b> Rate of Living Hypothesis</a></li>
<li class="chapter" data-level="12.3.2" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#evolutionary-theories-of-aging"><i class="fa fa-check"></i><b>12.3.2</b> Evolutionary Theories of Aging</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#case-study-evolution-of-aging"><i class="fa fa-check"></i><b>12.4</b> Case Study: Evolution of Aging</a></li>
<li class="chapter" data-level="12.5" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#practical-skills-life-table-analysis"><i class="fa fa-check"></i><b>12.5</b> Practical Skills: Life Table Analysis</a></li>
<li class="chapter" data-level="12.6" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#reflection-questions-11"><i class="fa fa-check"></i><b>12.6</b> Reflection Questions</a></li>
<li class="chapter" data-level="12.7" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#references-12"><i class="fa fa-check"></i><b>12.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html"><i class="fa fa-check"></i><b>13</b> Evolutionary Medicine II: Evolving Pathogens</a>
<ul>
<li class="chapter" data-level="13.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#epidemiology-and-pathogen-fitness"><i class="fa fa-check"></i><b>13.1</b> Epidemiology and Pathogen Fitness</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#a-basic-epidemiological-model"><i class="fa fa-check"></i><b>13.1.1</b> A Basic Epidemiological model</a></li>
<li class="chapter" data-level="13.1.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#r0-a-measure-of-pathogen-fitness"><i class="fa fa-check"></i><b>13.1.2</b> <em>R</em><sub>0</sub>: A Measure of Pathogen Fitness</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#the-evolution-of-virulence"><i class="fa fa-check"></i><b>13.2</b> The Evolution of Virulence</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#trade-offs-and-modes-of-transmission"><i class="fa fa-check"></i><b>13.2.1</b> Trade-Offs and Modes of Transmission</a></li>
<li class="chapter" data-level="13.2.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#short-sighted-and-coincidental-evolution-hypotheses"><i class="fa fa-check"></i><b>13.2.2</b> Short-Sighted and Coincidental Evolution Hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cultural-practices-disease-spread-and-evolution"><i class="fa fa-check"></i><b>13.3</b> Cultural Practices, Disease Spread, and Evolution</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#disrupting-pathogen-transmission"><i class="fa fa-check"></i><b>13.3.1</b> Disrupting Pathogen Transmission</a></li>
<li class="chapter" data-level="13.3.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#vaccination-and-herd-immunity"><i class="fa fa-check"></i><b>13.3.2</b> Vaccination and Herd Immunity</a></li>
<li class="chapter" data-level="13.3.3" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#pathogen-responses"><i class="fa fa-check"></i><b>13.3.3</b> Pathogen Responses</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#antibiotic-resistance"><i class="fa fa-check"></i><b>13.4</b> Antibiotic Resistance</a></li>
<li class="chapter" data-level="13.5" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#case-study-covid-19-epidemiology-and-the-cost-of-antibiotic-resistance"><i class="fa fa-check"></i><b>13.5</b> Case Study: COVID-19 Epidemiology and the Cost of Antibiotic Resistance</a></li>
<li class="chapter" data-level="13.6" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#practical-skills-data-wrangling-and-log-scales"><i class="fa fa-check"></i><b>13.6</b> Practical Skills: Data Wrangling and Log-Scales</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#data-wrangling"><i class="fa fa-check"></i><b>13.6.1</b> Data Wrangling</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#reflection-questions-12"><i class="fa fa-check"></i><b>13.7</b> Reflection Questions</a></li>
<li class="chapter" data-level="13.8" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#references-13"><i class="fa fa-check"></i><b>13.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="human-evolution.html"><a href="human-evolution.html"><i class="fa fa-check"></i><b>14</b> Human Evolution</a>
<ul>
<li class="chapter" data-level="14.1" data-path="human-evolution.html"><a href="human-evolution.html#phylogenetic-position"><i class="fa fa-check"></i><b>14.1</b> Phylogenetic Position</a></li>
<li class="chapter" data-level="14.2" data-path="human-evolution.html"><a href="human-evolution.html#what-the-fossils-say"><i class="fa fa-check"></i><b>14.2</b> What the Fossils Say</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="human-evolution.html"><a href="human-evolution.html#an-abridged-timeline"><i class="fa fa-check"></i><b>14.2.1</b> An Abridged Timeline</a></li>
<li class="chapter" data-level="14.2.2" data-path="human-evolution.html"><a href="human-evolution.html#evolutionary-trends"><i class="fa fa-check"></i><b>14.2.2</b> Evolutionary Trends</a></li>
<li class="chapter" data-level="14.2.3" data-path="human-evolution.html"><a href="human-evolution.html#a-lone-survivor-of-an-extinct-radiation"><i class="fa fa-check"></i><b>14.2.3</b> A Lone Survivor of an Extinct Radiation</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="human-evolution.html"><a href="human-evolution.html#modern-human-origins"><i class="fa fa-check"></i><b>14.3</b> Modern Human Origins</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="human-evolution.html"><a href="human-evolution.html#hypotheses"><i class="fa fa-check"></i><b>14.3.1</b> Hypotheses</a></li>
<li class="chapter" data-level="14.3.2" data-path="human-evolution.html"><a href="human-evolution.html#multiregional-evolution-vs.-out-of-africa"><i class="fa fa-check"></i><b>14.3.2</b> Multiregional Evolution <em>vs</em>. Out-Of-Africa</a></li>
<li class="chapter" data-level="14.3.3" data-path="human-evolution.html"><a href="human-evolution.html#out-of-africa-vs.-hybridization-and-assimilation"><i class="fa fa-check"></i><b>14.3.3</b> Out-of-Africa <em>vs</em>. Hybridization-and-Assimilation</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="human-evolution.html"><a href="human-evolution.html#what-makes-us-human"><i class="fa fa-check"></i><b>14.4</b> What Makes Us Human?</a></li>
<li class="chapter" data-level="14.5" data-path="human-evolution.html"><a href="human-evolution.html#case-study-modern-human-origins"><i class="fa fa-check"></i><b>14.5</b> Case Study: Modern Human Origins</a></li>
<li class="chapter" data-level="14.6" data-path="human-evolution.html"><a href="human-evolution.html#reflection-questions-13"><i class="fa fa-check"></i><b>14.6</b> Reflection Questions</a></li>
<li class="chapter" data-level="14.7" data-path="human-evolution.html"><a href="human-evolution.html#references-14"><i class="fa fa-check"></i><b>14.7</b> References</a></li>
</ul></li>
<li class="part"><span><b>V Interactive Simulations</b></span></li>
<li class="chapter" data-level="" data-path="simulating-selection.html"><a href="simulating-selection.html"><i class="fa fa-check"></i>Simulating Selection</a></li>
<li class="chapter" data-level="" data-path="simulating-genetic-drift.html"><a href="simulating-genetic-drift.html"><i class="fa fa-check"></i>Simulating Genetic Drift</a></li>
<li class="chapter" data-level="" data-path="simulating-mutation-and-selection.html"><a href="simulating-mutation-and-selection.html"><i class="fa fa-check"></i>Simulating Mutation and Selection</a></li>
<li class="chapter" data-level="" data-path="simulating-genetic-drift-and-selection.html"><a href="simulating-genetic-drift-and-selection.html"><i class="fa fa-check"></i>Simulating Genetic Drift and Selection</a></li>
<li class="appendix"><span><b>Appendix I</b></span></li>
<li class="chapter" data-level="" data-path="graph-library.html"><a href="graph-library.html"><i class="fa fa-check"></i>Graph Library</a>
<ul>
<li class="chapter" data-level="8" data-path="graph-library.html"><a href="graph-library.html#sample-data"><i class="fa fa-check"></i><b>8</b> Sample Data</a></li>
<li class="chapter" data-level="9" data-path="graph-library.html"><a href="graph-library.html#loading-dependencies"><i class="fa fa-check"></i><b>9</b> Loading Dependencies</a></li>
<li class="chapter" data-level="10" data-path="graph-library.html"><a href="graph-library.html#one-variable-continuous"><i class="fa fa-check"></i><b>10</b> One Variable: Continuous</a>
<ul>
<li class="chapter" data-level="10.1" data-path="graph-library.html"><a href="graph-library.html#frequency-histogram"><i class="fa fa-check"></i><b>10.1</b> Frequency Histogram</a></li>
<li class="chapter" data-level="10.2" data-path="graph-library.html"><a href="graph-library.html#density-plot"><i class="fa fa-check"></i><b>10.2</b> Density Plot</a></li>
<li class="chapter" data-level="10.3" data-path="graph-library.html"><a href="graph-library.html#frequency-histogram-with-density"><i class="fa fa-check"></i><b>10.3</b> Frequency Histogram with Density</a></li>
<li class="chapter" data-level="10.4" data-path="graph-library.html"><a href="graph-library.html#adding-a-discrete-variable"><i class="fa fa-check"></i><b>10.4</b> Adding a Discrete Variable</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="graph-library.html"><a href="graph-library.html#two-variables-continuous-x-and-y"><i class="fa fa-check"></i><b>11</b> Two Variables: Continuous X and Y</a>
<ul>
<li class="chapter" data-level="11.1" data-path="graph-library.html"><a href="graph-library.html#scatter-plot"><i class="fa fa-check"></i><b>11.1</b> Scatter Plot</a></li>
<li class="chapter" data-level="11.2" data-path="graph-library.html"><a href="graph-library.html#regression-line"><i class="fa fa-check"></i><b>11.2</b> Regression Line</a></li>
<li class="chapter" data-level="11.3" data-path="graph-library.html"><a href="graph-library.html#scatter-plot-with-regression"><i class="fa fa-check"></i><b>11.3</b> Scatter Plot with Regression</a></li>
<li class="chapter" data-level="11.4" data-path="graph-library.html"><a href="graph-library.html#adding-discrete-variables"><i class="fa fa-check"></i><b>11.4</b> Adding Discrete Variables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="graph-library.html"><a href="graph-library.html#two-variables-discrete-x-continuous-y"><i class="fa fa-check"></i><b>12</b> Two Variables: Discrete X, Continuous Y</a>
<ul>
<li class="chapter" data-level="12.1" data-path="graph-library.html"><a href="graph-library.html#box-plot"><i class="fa fa-check"></i><b>12.1</b> Box Plot</a></li>
<li class="chapter" data-level="12.2" data-path="graph-library.html"><a href="graph-library.html#dot-plot"><i class="fa fa-check"></i><b>12.2</b> Dot Plot</a></li>
<li class="chapter" data-level="12.3" data-path="graph-library.html"><a href="graph-library.html#violin-plot"><i class="fa fa-check"></i><b>12.3</b> Violin Plot</a></li>
<li class="chapter" data-level="12.4" data-path="graph-library.html"><a href="graph-library.html#adding-raw-data"><i class="fa fa-check"></i><b>12.4</b> Adding Raw data</a></li>
<li class="chapter" data-level="12.5" data-path="graph-library.html"><a href="graph-library.html#adding-additional-discrete-variables"><i class="fa fa-check"></i><b>12.5</b> Adding Additional Discrete Variables</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="graph-library.html"><a href="graph-library.html#aggregate-data"><i class="fa fa-check"></i><b>13</b> Aggregate Data</a>
<ul>
<li class="chapter" data-level="13.1" data-path="graph-library.html"><a href="graph-library.html#calculating-mean-and-standard-deviation"><i class="fa fa-check"></i><b>13.1</b> Calculating Mean and Standard Deviation</a></li>
<li class="chapter" data-level="13.2" data-path="graph-library.html"><a href="graph-library.html#visualizing-means-and-variation"><i class="fa fa-check"></i><b>13.2</b> Visualizing Means and Variation</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="graph-library.html"><a href="graph-library.html#combining-multiple-plots"><i class="fa fa-check"></i><b>14</b> Combining Multiple plots</a></li>
<li class="chapter" data-level="15" data-path="graph-library.html"><a href="graph-library.html#working-with-color-palettes"><i class="fa fa-check"></i><b>15</b> Working with Color Palettes</a>
<ul>
<li class="chapter" data-level="15.1" data-path="graph-library.html"><a href="graph-library.html#color-palettes-in-rcolorbrewer"><i class="fa fa-check"></i><b>15.1</b> Color Palettes in RColorBrewer</a></li>
<li class="chapter" data-level="15.2" data-path="graph-library.html"><a href="graph-library.html#combining-rcolorbrewer-palettes-with-ggplot"><i class="fa fa-check"></i><b>15.2</b> Combining RColorBrewer Palettes with ggplot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercises.html"><a href="r-exercises.html"><i class="fa fa-check"></i>R Exercises</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Primer of Evolution</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="evolutionary-medicine-ii-evolving-pathogens" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Chapter 13</span> Evolutionary Medicine II: Evolving Pathogens<a href="evolutionary-medicine-ii-evolving-pathogens.html#evolutionary-medicine-ii-evolving-pathogens" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the previous chapter, we focused on understanding non-communicable diseases from an evolutionary perspective. We will now focus on infectious diseases caused by evolving pathogens. In <a href="evolution-of-dna-sequences.html#case-study-sars-cov-2">Chapter 7</a>, we already explored the evolutionary relationship between pathogens and their hosts. We learned how hosts evolve strategies to exclude or combat pathogens, while pathogens are selected to evade the hosts’ defense mechanisms—giving rise to a continuous coevolutionary arms race. Pathogens, of course, have the upper hand in this evolutionary game, since their large population sizes and short generation times allow them to evolve much more rapidly than their hosts—especially in long-lived species like humans. But from a personal and public health perspective, we can’t just stand idly by as pathogens exert selection on our population, watching the cost of selection (<em>e.g.</em>, the death toll caused by disease) rise and hoping that the next generation will be better adapted to recurring waves of infection. We cannot evolve our way out of a contagious disease problem. However, as a society, we collectively have the power to impact a pathogen’s fitness and steer its evolution towards more desirable health outcomes for us. In this chapter, we will explore how evolutionary principles relate to epidemiology, and how cultural practices can critically shape the dynamics of disease spread and the evolution of pathogen properties—including antibiotic resistance in harmful bacteria.</p>
<div id="epidemiology-and-pathogen-fitness" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Epidemiology and Pathogen Fitness<a href="evolutionary-medicine-ii-evolving-pathogens.html#epidemiology-and-pathogen-fitness" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A pathogen’s fitness is directly related to its ability to spread in a population of hosts. Epidemiologists have developed sophisticated models to better understand how diseases spread, how many people will be infected, or how long a disease outbreak might last. Let’s take a look at one such epidemiological model (the SEIR model) to familiarize ourselves with the general logic epidemiologists apply, and then relate this logic to explicitly define pathogen fitness.</p>
<div id="a-basic-epidemiological-model" class="section level3 hasAnchor" number="13.1.1">
<h3><span class="header-section-number">13.1.1</span> A Basic Epidemiological model<a href="evolutionary-medicine-ii-evolving-pathogens.html#a-basic-epidemiological-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are a number of theoretical models epidemiologists apply to study disease dynamics. Many of them are compartmental models, where individuals in a populations are assigned to different compartments (categorical groups), and we quantify the rates at which individuals transition from one compartment to another. For example, in the SEIR model, a population is subdivided into four compartments (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:seir">13.1</a>): (1) susceptible hosts (<em>S</em>) that are available for a pathogen; (2) infected hosts (<em>E</em>) that have contracted a pathogen but cannot yet spread it (<em>i.e.</em>, they are within an incubation period); (3) infectious hosts (<em>I</em>) that show disease symptoms and can pass on the pathogen to susceptible individuals in the population; and (4) recovered hosts (<em>R</em>) that have cleared the infection and are now immune to the pathogen.</p>
<p>The pool of total hosts in the population (<em>N</em>=<em>S</em>+<em>E</em>+<em>I</em>+<em>R</em>) depends on the rate at which new individuals are born (birth rate, 𝝻) and the rate at which individuals die (death rate, 𝝳; Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:seir">13.1</a>). If we assume a constant population size, the birth and death rates cancel each other out; hence, we will ignore them in our considerations. From the perspective of disease dynamics, it is more important at what rates individuals transition from one epidemiological compartment to another:</p>
<ul>
<li><p>The rate at which susceptible individuals become infected depends on the density of susceptible individuals, the density of infectious individuals, and the rate of disease transmission (𝝱). The transmission rate is a property of the pathogen (some pathogens are more easily transmitted than others), as well as the host’s behavior and cultural practices.</p></li>
<li><p>Once infected, the rate at which individuals become infectious depends on the incubation rate (𝝹), which is largely a property of the pathogen. Some pathogens replicate rapidly within a newly infected host (<em>e.g.</em>, noroviruses can cause diarrhea within 12-24 hours post-infection), while others lie dormant for extended periods of time before becoming active (<em>e.g.</em>, infections with <em>Plasmodium vivax</em>, <em>Listeria monocytogenes,</em> and <em>Molluscum contagiosum</em> can take months to unfold).</p></li>
<li><p>Once infectious, individuals have two possible fates. They may be able to clear the infection and recover at a rate of 𝝼. Recovered individuals are unavailable to the pathogen due to acquired immunity, unless they lose that immunity (at the rate of 𝝺). Alternatively, infectious individuals may die as a direct consequence of the pathogen’s activity within the body. The infectious mortality rate is the pathogen’s virulence (𝝰), which is a measure of host damage stemming from interactions between hosts and pathogens.</p></li>
</ul>
<p>From a pathogen’s perspective, epidemiology is all about balancing the rates at which new hosts can be infected and the rates at which hosts become unavailable, either due to death or immunity. Pathogens are, of course, keen to tip the balance in favor of transmission, which allows their spread in a population.</p>
<div class="figure"><span style="display:block;" id="fig:seir"></span>
<img src="images/seir.png" alt="Graphic representation of the SEIR model (see text for details)." width="100%" />
<p class="caption">
Figure 13.1: Graphic representation of the SEIR model (see text for details).
</p>
</div>
</div>
<div id="r0-a-measure-of-pathogen-fitness" class="section level3 hasAnchor" number="13.1.2">
<h3><span class="header-section-number">13.1.2</span> <em>R</em><sub>0</sub>: A Measure of Pathogen Fitness<a href="evolutionary-medicine-ii-evolving-pathogens.html#r0-a-measure-of-pathogen-fitness" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The basic reproductive number (<em>R</em><sub>0</sub>) is the expected number of secondary cases generated by a single infectious individual entering a population composed of entirely susceptible individuals. Hence, <em>R</em><sub>0</sub> estimates the epidemic growth at the start of an outbreak. Imagine a traveler coming back from an exotic destination where they contracted a new kind of infectious disease; if <em>R</em><sub>0</sub>=2, that traveler—patient zero—is expected to infect two other people after their return, and if <em>R</em><sub>0</sub>=6, six other people would be infected. As you can see in Table 13.1, basic reproductive numbers vary vastly among different pathogens that cause health issues in human populations. <em>R</em><sub>0</sub> can also vary within a pathogen depending on the epidemiological context.</p>
<table>
<caption>Table 13.1: Approximate <em>basic reproductive numbers for different pathogens that routinely infect humans.</em></caption>
<thead>
<tr class="header">
<th align="left">Disease</th>
<th align="right">R<sub>0</sub></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Hepatitis C</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">Ebola</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">Zika</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">Spanish flu</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">HIV</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="left">SARS (2002 outbreak)</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">Smallpox</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="left">Rubella</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="left">Mumps</td>
<td align="right">10</td>
</tr>
<tr class="even">
<td align="left">Chickenpox</td>
<td align="right">11</td>
</tr>
<tr class="odd">
<td align="left">Measles</td>
<td align="right">18</td>
</tr>
</tbody>
</table>
<p>The basic reproductive number is a measure of a pathogen’s fitness. Just as natural selection acts to maximize the fitness of individuals, it also acts to maximize the basic reproductive number of pathogens. If <em>R</em><sub>0</sub>&gt;1, a pathogen can spread in a population of hosts, and it can spread faster with increasing values of <em>R</em><sub>0</sub>. If <em>R</em><sub>0</sub>&lt;1, then the rate of spread is not fast enough to remain in the population, and the disease will disappear. If <em>R</em><sub>0</sub>=1, then the frequency of the pathogen remains stable through time.</p>
<p>Importantly, we can link analyses of pathogen evolution to epidemiological analyses, because the basic reproductive number can be approximated using epidemiological parameters that describe the transition rates of individuals across different epidemiological classes (<em>S</em> to <em>E</em> to <em>I</em> to <em>R</em>). Assuming that birth and pathogen-independent mortality rates are the same, incubation periods are short, and loss of immunity is rare, then the basic reproductive number can be defined as:</p>
<span class="math display" id="eq:47">\[\begin{align}
R_0=\frac{βS}{⍺+ν} \tag{13.1}
\end{align}\]</span>
<p>In this case, 𝝱 is the transmission rate, <em>S</em> is the density of susceptible individuals in the population, 𝝰 is the pathogen’s virulence, and 𝝼 is the rate of recovery. To put the formula into words: pathogen fitness is positively influenced by high transmission rates and high densities of susceptible individuals, and it is negatively influenced by high rates of recovery (which converts susceptible individuals to immune individuals) and by high rates of pathogen-induced mortality.</p>
<p>We can examine the basic reproductive numbers that have been reported for different pathogens during past outbreaks. Measles stands out because it has a very high <em>R</em><sub>0</sub>. This high value is driven primarily by measles’ high transmission rate (𝝱). The measles virus (<em>Measles morbillivirus</em>) is transmitted when infectious individuals cough or sneeze, contaminating the air and surfaces with virus particles. The virus stays alive outside the host body for several hours, and anyone breathing in contaminated air or touching contaminated surfaces has a 90 % change of becoming infected. In addition, infectious individuals can spread this virus up to four days before any symptoms arise; so by the time patients realize that they are sick, they have likely already spread to virus to other hosts. This extremely efficient transmission corresponds to a high value of <em>R</em><sub>0</sub>.</p>
<p>In contrast, Ebola—though it seems like a scarier disease based on news coverage—has a much smaller basic reproductive number. The Ebola virus (<em>Zaire ebolavirus</em>) can only be spread by direct contact with blood or other bodily fluids of an infectious individual, which translates to much lower transmission rates. In addition, the high rate at which Ebola causes the death of infectious individuals further decreases the probability of its spread, because it narrows the window during which the pathogen can jump to the next host. Hence, Ebola disease spread is often self-limiting, which explains why outbreaks tend to be spatially restricted.</p>
</div>
</div>
<div id="the-evolution-of-virulence" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> The Evolution of Virulence<a href="evolutionary-medicine-ii-evolving-pathogens.html#the-evolution-of-virulence" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the key factors in pathogen evolution is virulence. Unlike transmissibility, which is often subject to a variety of constraints, virulence can evolve rapidly, with concomitant consequences for disease dynamics. A common misconception is that pathogens will eventually evolve toward low virulence, resulting in a commensal relationship between host and pathogen. When first proposed, the rationale behind this idea appeared to be supported by both theoretical considerations and empirical observations.</p>
<p>Early theoreticians suggested that high virulence decreases pathogen fitness (<em>R</em><sub>0</sub>), and a minimally impacted host is ideal for carrying the pathogen around and facilitating its spread. This notion was supported by the observation that novel hosts often have a higher susceptibility to a pathogen when compared to hosts that experienced a coevolutionary history with the same pathogen. This difference suggested that coevolution between host and pathogen ultimately reduces virulence. For example, smallpox and other diseases common in European populations caused high rates of mortality in Native American peoples that did not have previous contact to these pathogens. This difference in disease susceptibility was ruthlessly exploited by British colonialists and—allegedly—by the U.S. Army, who distributed smallpox-infested blankets as a form of biological warfare to eradicate Native peoples. However, there are also prominent counterexamples, such as diseases like malaria and tuberculosis, which have long-documented histories of coevolution with humans yet still exhibit high virulence.</p>
<p>Today, we know that coevolution does not necessarily lead to pathogens with a low virulence, and, in some cases, high virulence is adaptive for the pathogen. There are three, non-mutually exclusive hypotheses that explain the maintenance of intermediate or high virulence: the trade-off hypothesis, the short-sighted evolution hypothesis, and the coincidental evolution hypothesis.</p>
<div id="trade-offs-and-modes-of-transmission" class="section level3 hasAnchor" number="13.2.1">
<h3><span class="header-section-number">13.2.1</span> Trade-Offs and Modes of Transmission<a href="evolutionary-medicine-ii-evolving-pathogens.html#trade-offs-and-modes-of-transmission" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Virulence, the damage a pathogen causes hosts, is a byproduct of pathogen replication. Pathogens produce antigens and metabolic byproducts while using the host’s tissues, nutrients, and energetic resources, which collectively impair host function and fitness. The more rapidly pathogens replicate within a host, the higher the cost imposed on the host. A trade-off arises, because a pathogen’s fitness improves with increasing reproductive capacity (more infectious particles are produced to infect new hosts), but pathogen fitness is also impaired by the correlated virulence, which reduces the host’s ability to facilitate transmission. Consequently, the optimal virulence is somewhere at an intermediate level; high enough to support sufficient pathogen replication but low enough to limit damage to the host, such that transmission to new hosts can still occur. The exact balance in this trade-off is partly shaped by how pathogens are transmitted from one host to another.</p>
<p>To explore how modes of transmission can impact the trade-off between virulence and transmission, let’s contrast two basic modes of transmission. Horizontal transmission occurs when pathogens are transmitted among individuals of the same generation, while vertical transmission occurs from mothers to offspring. If transmission is exclusively vertical, then the fitness of the pathogen becomes inextricably linked to the fitness of the host; any virulence that damages the host will also damage pathogen. Therefore, the costs associated with elevated virulence should decrease with increasing opportunities for horizontal transmission.</p>
<p>Sharon Messenger and her coauthors (1999) tested this prediction using <em>Escherichia coli</em> bacteria as host cells and a bacteriophage (<em>i.e</em>., a virus that infects bacteria) as a pathogen. In this system, they were able to tightly control the mode of transmission (vertical <em>vs</em>. horizontal), and the researchers alternated periods of vertical transmission (for either one or eight days) with short bouts of horizontal transmission. They predicted that shorter periods of vertical transmission should select for higher rates of pathogen replication, and accordingly, higher virulence. The results of this evolution experiment not only revealed the expected correlation between virulence and pathogen reproduction, but also the expected virulence difference between treatments that differed in the amount of horizontal transmission (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:veritcaltrans">13.2</a>A). When vertical transmission was limited, it was advantageous for phages to replicate quickly—both because increased production of virus particles facilitated horizontal transmission and because costs associated with damage to the host were relatively small (the fate of the host was decoupled from the fate of the pathogen after just one day). In contrast, phages were able to maximize their fitness by minimizing damage to the host when there were long periods of vertical transfer, because phage fitness was contingent on host fitness during that period.</p>
<p>Natural systems also illustrate the importance of vertical transmission in shaping virulence evolution. Fig wasps are tiny hymenopterans that pollinate figs and are parasitized by nematodes. Fig wasps deposit their eggs inside of figs, where most of the wasps’ life cycle takes place: larvae develop, pupate, emerge as adults, and mate inside the fig, and females then disperse out to lay their eggs on a new fruit. Different species of fig wasps vary in their mating systems. In some species, only a single female deposits eggs on a fig, such that the resulting matings in the next generation are primarily between brothers and sisters. In other species, multiple females lay eggs on the same fig. The different behaviors have direct consequences for the transmission of the fig wasps’ nematode parasites. In wasp species where only one female lays her eggs on a particular fig, there are no opportunities for horizontal transmission, and nematodes are exclusively transmitted vertically. Since the nematodes’ fitness is thus linked to the wasps’ fitness, we would predict that the parasites have evolved a relatively low virulence. In contrast, nematodes should evolve higher virulence in wasp species where multiple females lay eggs on the same fig, facilitating horizontal parasite transmission. Indeed, there was a negative correlation between the proportion of single foundress broods and the virulence of nematode parasites across different species of fig wasps (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:veritcaltrans">13.2</a>B). Overall, these two examples illustrate how natural selection can drive the evolution of low virulence when there are high costs associated with damaging the hosts, irrespective of the benefits to increased reproductive rates. The next question is: under what circumstances are costs associated with damaging the host less severe, such that higher virulence can evolve?</p>
<div class="figure"><span style="display:block;" id="fig:veritcaltrans"></span>
<img src="Primer2Evolution_files/figure-html/veritcaltrans-1.png" alt="A. Correlation between pathogen replication and virluence in phages that have frequent opportunities for horizontal transmission (*i.e.*, every day; L1) and phages with few opportunities for horizontal transmission (*i.e.*, every eight days; L8). As predicted by the trade-off hypothesis, virulence is lower in strains with higher levels of vertical transmission. [Data](data/13_vir-to.csv) from Messenger et al. (1999). B. Correlation between the proportion of single foundress broods (*i.e.*, the degree of vertical transmission) and virulence in fig wasps and their nematode parasites. [Data](data/13_figwasp.csv) from Herre (1993)." width="100%" />
<p class="caption">
Figure 13.2: A. Correlation between pathogen replication and virluence in phages that have frequent opportunities for horizontal transmission (<em>i.e.</em>, every day; L1) and phages with few opportunities for horizontal transmission (<em>i.e.</em>, every eight days; L8). As predicted by the trade-off hypothesis, virulence is lower in strains with higher levels of vertical transmission. <a href="data/13_vir-to.csv">Data</a> from Messenger et al. (1999). B. Correlation between the proportion of single foundress broods (<em>i.e.</em>, the degree of vertical transmission) and virulence in fig wasps and their nematode parasites. <a href="data/13_figwasp.csv">Data</a> from Herre (1993).
</p>
</div>
<p>The cost of virulence can be reduced—and even mostly avoided—if a pathogen is not reliant on the host for transmission. Consider the common cold, which is caused by a variety of rhinoviruses, coronaviruses, adenoviruses, and enteroviruses. All of these viruses have to be transmitted directly from one host to another, because they have a limited survivability outside of the host. Hence, a host that is too sick to move around and be in contact with susceptible individuals may clear an infection before significant opportunities for transmission arise. Hence, lower virulence facilitates transmission. However, there are two ways that a pathogen can circumnavigate costs associated with high virulence: a high pathogen survivability outside the host body and pathogen transmission through mobile vectors.</p>
<p>If a pathogen has a high survivability outside of the host’s body, it can linger in the environment and wait for a susceptible individual to pass by—even after the initial host has long perished. For example, anthrax bacteria (<em>Bacillus anthracis</em>) form resting spores that can survive in the soil for decades. Hence, a premature host death does not necessarily come at a substantial fitness cost for the pathogen, especially if high pathogen replication leads to the release of large numbers of propagules. Following the same logic, the virulence of intestinal bacteria that can cause disease is directly correlated with the proportion of outbreaks that are waterborne (<em>i.e.</em>, transmitted through contaminated water; Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:waterb">13.3</a>A). When sanitation is poor and contamination of drinking water common, host mobility becomes secondary to pathogen spread, and transmission is instead facilitated by high rates of pathogen replication with corresponding consequences for virulence.</p>
<p>Costs associated with virulence can also be mitigated through vector-borne transmission, where an intermediate host carries and transmits a pathogen to a susceptible individual. Blood-feeding arthropods are particularly common disease vectors; they transmit many diseases relevant for human health. For example, mosquitoes are intermediate hosts for malaria, dengue, and zika, sand flies transmit leishmaniasis, hemipterans carry Chagas disease, and ticks spread Lyme disease, among many others. A comparison of virulence between diseases with different modes of transmission indicated that the vast majority of directly-transmitted pathogens have a very low virulence (&lt;0.1 % mortality per infection), while elevated and high virulence is much more common among vector-borne pathogens. Interestingly, the virulence of vector-borne pathogens inside the mobile vector that is responsible for disease transmission is often negligible, because the mobility of the intermediate host is critical for pathogen fitness.</p>
<p>In summary, trade-offs between pathogen reproduction and transmission explain the evolution of intermediate levels of virulence. Low virulence can evolve when decreases in host mobility and fitness also reduce pathogen transmission. However, if pathogens do not need “help” from their hosts to infect susceptible individuals, either because they can survive outside of the host or they can be transmitted by a vector, then there is little cost associated with killing the host, and high virulence may not be selected against.</p>
<div class="figure"><span style="display:block;" id="fig:waterb"></span>
<img src="Primer2Evolution_files/figure-html/waterb-1.png" alt="A. Virulence is higher in bacterial pathogens that are associated with frequent waterborne outbreaks. [Data](data/13_waterborne.csv) from Ewald (1991). B. Comparison of virulence between directly-transmitted and vectorborne pathogens. [Data](data/13_vector.csv) from Ewald (1983)." width="100%" />
<p class="caption">
Figure 13.3: A. Virulence is higher in bacterial pathogens that are associated with frequent waterborne outbreaks. <a href="data/13_waterborne.csv">Data</a> from Ewald (1991). B. Comparison of virulence between directly-transmitted and vectorborne pathogens. <a href="data/13_vector.csv">Data</a> from Ewald (1983).
</p>
</div>
</div>
<div id="short-sighted-and-coincidental-evolution-hypotheses" class="section level3 hasAnchor" number="13.2.2">
<h3><span class="header-section-number">13.2.2</span> Short-Sighted and Coincidental Evolution Hypotheses<a href="evolutionary-medicine-ii-evolving-pathogens.html#short-sighted-and-coincidental-evolution-hypotheses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Two additional hypotheses have been put forward to explain the evolution of high virulence in absence of trade-offs between pathogen replication and transmission.</p>
<p>The short-sighted evolution hypothesis emphasizes the fact that evolution and adaptation within the host might favor elevated virulence. For example, competition arising from co-infection of multiple pathogens can favor strains with more rapid replication, which has concomitant negative effects for the host. Rapid pathogen replication is favored, because the pathogen that uses host resources the fastest and successfully transmits to susceptible individuals will be able to persist in a population even when the host dies sooner than optimal for maximal transmission. In contrast, the slower-replicating pathogen may not be able to persist in that situation, because hosts may die (as a consequence of the faster-replicating pathogen) before the pathogen is transmitted. So, if there is within-host competition between pathogens, the cost of having a virulence that is too high tends to be smaller than the cost of having slower rates of replication. Evidence for a relationship between competitive ability and virulence comes from experiments with malaria (<em>Plasmodium chabaudi</em>). Especially during the acute phase of malaria, when the pathogen replicates quickly, strains with higher virulence have a competitive advantage over strains with lower virulence (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:malaria">13.4</a>). Other examples of short-sighted evolution have been inferred when pathogen strains escape competition by colonizing and adapting to novel tissues or organs within the host. For example, polio viruses typically infect the digestive tract, where they cause little harm to the host. Viral mutations that facilitate colonization of cells associated with the nervous system increase within-host fitness of the virus, even though infection of the nervous system does not lead to transmission to susceptible individuals. In this case, host fitness costs associated with viral replication in a novel cell type is just a byproduct of viral mutations that mediate increased within-host fitness, even if that adaptation is an evolutionary dead end for the pathogen.</p>
<div class="figure"><span style="display:block;" id="fig:malaria"></span>
<img src="Primer2Evolution_files/figure-html/malaria-1.png" alt="Correlation between relative virulence and competitiveness for different strains of malaria (*Plasmodium chabaudo*) during acute and chronic phases of the disease. Relative virulence was quantified as the anemia induced by two competing strains when on their own, expressed as the anemia induced by least virulent competitor as a fraction of that induced by the more virulent. Thus, a value of 1.0 means the competing strains induce equal levels of anemia; a value of 0.5 that the less virulent clone induces half the anemia of the more virulent. Competitive suppression is the proportional reduction in strain density due to the presence of a competitor (1, competitive exclusion; 0, no suppression). [Data](data/13_malaria.csv) from Bell et al. (2006)." width="100%" />
<p class="caption">
Figure 13.4: Correlation between relative virulence and competitiveness for different strains of malaria (<em>Plasmodium chabaudo</em>) during acute and chronic phases of the disease. Relative virulence was quantified as the anemia induced by two competing strains when on their own, expressed as the anemia induced by least virulent competitor as a fraction of that induced by the more virulent. Thus, a value of 1.0 means the competing strains induce equal levels of anemia; a value of 0.5 that the less virulent clone induces half the anemia of the more virulent. Competitive suppression is the proportional reduction in strain density due to the presence of a competitor (1, competitive exclusion; 0, no suppression). <a href="data/13_malaria.csv">Data</a> from Bell et al. (2006).
</p>
</div>
<p>Finally, the coincidental evolution hypothesis posits that high virulence can evolve as an incidental byproduct of pathogen adaptation to other ecological niches. This hypothesis has been favored to explain virulence in facultative pathogens. For example, some soil microbes—like <em>Clostridium tetani</em> that causes tetanus—can be highly virulent if they happen to infect humans. Some researchers have suggested that the toxins produced by these bacteria have primarily evolved to deter grazing by protozoan predators in the soil. In humans, these anti-grazing defense toxins inadvertently interfere with normal physiological function and cause health issues, including death.</p>
</div>
</div>
<div id="cultural-practices-disease-spread-and-evolution" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> Cultural Practices, Disease Spread, and Evolution<a href="evolutionary-medicine-ii-evolving-pathogens.html#cultural-practices-disease-spread-and-evolution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Understanding pathogen fitness and the principles governing the evolution of virulence from an epidemiological perspective offers key insights into how we can manage the spread and evolution of pathogens. In fact, evolutionary considerations inform public health guidelines that have profound impacts on disease dynamics—both when they are followed (disease outbreaks contract and low-virulence strains are favored) and when they are not (diseases spread and high-virulence strains can emerge). Thinking about pathogen fitness explicitly in the context of <em>R</em><sub>0</sub>, we can manipulate two parameters in the equation through cultural practices: the rate of transmission (𝝱) and the density of susceptible individuals (<em>S</em>). If we take the reigns of a disease outbreak by tightly controlling rates of transmission or the density of susceptible individuals, then the pathogen has only one evolutionary strategy left to increase <em>R</em><sub>0</sub>; it has to decrease its virulence (𝝰).</p>
<div id="disrupting-pathogen-transmission" class="section level3 hasAnchor" number="13.3.1">
<h3><span class="header-section-number">13.3.1</span> Disrupting Pathogen Transmission<a href="evolutionary-medicine-ii-evolving-pathogens.html#disrupting-pathogen-transmission" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In many cases, the most cost-effective approach to reduce <em>R</em><sub>0</sub> is to minimize the rate of pathogen transmission. Prevention measures that reduce disease spread are, of course, largely dependent on the mode of transmission of the pathogen of concern. Most common pathogens we deal with on a regular basis—viruses that cause colds, the flu, and now COVID-19—are directly transmitted respiratory infections. Simple behavioral changes like increased personal hygiene, mask wearing, social distancing, and reduced travel, especially for people that are symptomatic, can dramatically reduce the spread of disease.</p>
<p>Evidence for how effective these measures are was uncovered during the COVID-19 pandemic, when preventative measures that reduced transmission were much more rigorously enforced, including extended periods of lockdowns in some countries. While these measures primarily targeted the spread of SARS-CoV-2, the effectiveness of preventative measures is hard to gauge when looking at that virus, simply because comparative data from previous outbreaks is not available. However, the same preventative measures also affected the spread of other directly transmitted respiratory infections, including rhinoviruses that cause the common cold and influenza-A that causes the seasonal flu. In the wake of COVID-19-related lockdowns in 2020, infections of rhinoviruses were dramatically lower compared to the same time period in 2019 (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:rhinovirus">13.5</a>A). Infections drastically declined after the implementation of mandatory lockdowns, and they rose back to normal levels right after lockdowns ended later in the year. The same pattern holds true for influenza A. While there was an initial surge in late 2019, coinciding with the emergence of COVID-19, the frequency of positive flu tests plummeted to record lows by mid-2020 (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:rhinovirus">13.5</a>B). More importantly, the seasonal spike in flu cases that invariably occurs over the winter months completely disappeared in the winter of 2020/2021, with continued record-low test positivity rates. Consequently, the COVID-19-induced experiment drastically impacted transmission rates for all directly-transmitted respiratory diseases, clearly showing how impactful cultural practices are when it comes to disease spread.</p>
<div class="figure"><span style="display:block;" id="fig:rhinovirus"></span>
<img src="Primer2Evolution_files/figure-html/rhinovirus-1.png" alt="A. Prevalence of rhinovirus infections in Australia in 2019 (pre-COVID-19) and 2020 (where COVID-19-related lockdowns were enforced). During most of the lockdown period of 2020, rhinovirus prevalence approached zero.  [Data](data/13_rhino.csv) from Jones (2020). B. Prevalence of influenza A in the U.S. from 2018 through 2021. Mid-2020, the prevalence of the common flu fell to a record low, and the typical surge in flu prevalence over the winter was absent for the 2020/2021 flu season. [Data](data/13_flu.csv) from Peek (2021)." width="100%" />
<p class="caption">
Figure 13.5: A. Prevalence of rhinovirus infections in Australia in 2019 (pre-COVID-19) and 2020 (where COVID-19-related lockdowns were enforced). During most of the lockdown period of 2020, rhinovirus prevalence approached zero. <a href="data/13_rhino.csv">Data</a> from Jones (2020). B. Prevalence of influenza A in the U.S. from 2018 through 2021. Mid-2020, the prevalence of the common flu fell to a record low, and the typical surge in flu prevalence over the winter was absent for the 2020/2021 flu season. <a href="data/13_flu.csv">Data</a> from Peek (2021).
</p>
</div>
<p>Cultural practices that prevent disease spread differ for pathogens with other rates of transmission. For example, the use of condoms and other safer sex practices are critical to curb the spread of HIV and other sexually transmitted diseases. Proper sanitary and waste water management practices, as well as the provisioning of clean drinking water, helps to limit infections from waterborne pathogens. And the distribution of insect repellents, mosquito nets, and mosquito-proof housing can drastically reduce the prevalence of vector-borne diseases, like malaria. Although the general approaches to limit disease transmission differ from pathogen to pathogen, and individual action has direct benefits (<em>i.e.</em>, <em>you</em> reduce <em>your</em> risk of contracting a disease by social distancing, wearing a mask, using a condom, or sleeping under a mosquito net), the larger-scale public health benefits hinge on the collective action of many people in a population. A significant negative impact on pathogen fitness can only be expected when a substantial segment of the population adheres to practices that limit transmission. However, if they do, <em>R</em><sub>0</sub> can be pushed below 1, and the pathogen disappears from the population. In many cases, measures that reduce pathogen transmission have proven to be sweeping successes. For example, our ability to provide clean drinking water even when natural disasters disable sanitation and waste water management has lead to stark reductions in outbreaks of waterborne diseases.</p>
</div>
<div id="vaccination-and-herd-immunity" class="section level3 hasAnchor" number="13.3.2">
<h3><span class="header-section-number">13.3.2</span> Vaccination and Herd Immunity<a href="evolutionary-medicine-ii-evolving-pathogens.html#vaccination-and-herd-immunity" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The fitness of a pathogen can also be reduced by reducing the density of susceptible hosts in a population. In theory, we could just safeguard the recovery of infected individuals; as more people get immune after overcoming an infection, the <em>R</em><sub>0</sub> of the pathogen gradually gets smaller. However, letting a disease run its natural course not only comes with huge public health and economic costs, but rapidly spreading pathogens have a large mutational input into the population, potentially leading to the emergence of novel strains that can overcome the acquired immunity of recovered hosts.</p>
<p>Vaccines are a much more effective way of managing the density of susceptible individuals in a population. Compared to uncontrolled disease spread, vaccination is much less costly both from a public health and an economic perspective. For example, the risk for severe neurologic or allergic side effects associated with the MMR vaccine—one of the most common vaccines that protects against measles, mumps, and rubella—is 5.3 per 100,000 fully vaccinated people. Among 1.8 million people that received the vaccine, only one death was putatively—not conclusively—linked to MMR vaccination. In comparison, prior to the 1960s when the MMR vaccine was first introduced, there were 3-4 million measles cases in the US every year, including 48,000 hospitalizations, 1,000 cases of associated encephalitis, and 500 deaths. Over 186,000 children annually were diagnosed with mumps, with many suffering from permanent deafness as a consequence. And an estimated 12.5 million people contracted rubella, causing 11,000 pregnant women to lose their babies, 2,100 newborn deaths, and 20,000 babies born with congenital rubella syndrome, which can cause life-long health issues. Rigorous MMR vaccination campaigns have caused a massive decline in the prevalence of measles, mumps, and rubella, to the point where measles was declared eliminated from U.S. in 2000, after the absence of disease transmission for over 12 months. Similarly, vaccination has lead to the global extinction of smallpox—a vicious disease with death rates around 30 %—in 1980.</p>
<p>The reason why diseases with high vaccination coverage disappear is because the reduction in the density of susceptible individuals pushes the pathogen’s <em>R</em><sub>0</sub> below 1; rather than spreading in a population, a pathogen outbreak now contracts. Importantly, not all individuals in a populations have to be vaccinated to curb disease spread and cause pathogen extinction—only enough people so that <em>R</em><sub>0</sub> is smaller than 1. Using Equation <span class="citation">@ref</span>(eq:47), the proportion of the population that needs to be vaccinated to push <em>R</em><sub>0</sub> below 1 is given by the herd immunity threshold (HIT):</p>
<span class="math display" id="eq:47">\[\begin{align}
HIT=1-\frac{1}{R_0}=1-\frac{⍺+ν}{β} \tag{13.1}
\end{align}\]</span>
<p>Since HIT is directly dependent on <em>R</em><sub>0</sub>, diseases with a higher <em>R</em><sub>0</sub> require higher rates of vaccination (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:hit">13.6</a>). However, once HIT is reached and the pathogen’s <em>R</em><sub>0</sub> is smaller than 1, the phenomenon of “herd immunity” emerges. Since a pathogen can no longer spread in a population that has reached HIT, even individuals that are not vaccinated by the pathogen experience a significant reduction in the likelihood of infection. This is important from a public health perspective because comprehensive vaccination of eligible individuals helps to protect vulnerable segments of the population that do not have the privilege of immunization, including young children and immunocompromised people.</p>
<div class="figure"><span style="display:block;" id="fig:hit"></span>
<img src="Primer2Evolution_files/figure-html/hit-1.png" alt="Heard immunity threshold (HIT) as a function of a pathogen's *R*&lt;sub&gt;0&lt;/sub&gt;. Values for influenza A, polio, chicken and smallpox, as well as measles are indicated by gray lines." width="100%" />
<p class="caption">
Figure 13.6: Heard immunity threshold (HIT) as a function of a pathogen’s <em>R</em><sub>0</sub>. Values for influenza A, polio, chicken and smallpox, as well as measles are indicated by gray lines.
</p>
</div>
<p>Overall, the development and administration of vaccines has been a sweeping success with far-reaching public health benefits. For example, despite various setbacks in the rollout of the COVID-19 vaccination campaign in 2021, the effects of vaccination on disease prevalence became evident within just a few months. By August, states with vaccination rates above 50 % exhibited below average hospitalization rates (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:vax">13.7</a>A). In contrast, every state with an above-average hospitalization rate also exhibited low levels of vaccination coverage. Hence, collective buy-in and action of a majority are crucial to impact disease dynamics in a significant way and produce the desired public health outcomes. The importance of coordinated responses is illustrated by the recent resurgence of measles in the U.S. Even though this disease was considered eliminated in 2000, measles has made a significant comeback over the past decade. Significant outbreaks have been recorded in the Pacific northwest, California, New York, New Jersey, and Michigan, with over 1,200 cases reported in 2019. These outbreaks have, in part, been facilitated by drops in vaccination rates (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:vax">13.7</a>B) inspired by anti-vaccination myths that are rooted in superstition and propagated by dubious entities with ulterior motives.</p>
<div class="figure"><span style="display:block;" id="fig:vax"></span>
<img src="Primer2Evolution_files/figure-html/vax-1.png" alt="A. Relationship between COVID-19 vaccination coverage and the number of hospitalizations in U.S. in August of 2021. The red dot indicates the nation-wide avagerage. [Data](data/13_covid_vax.csv) compiled by [WSJ](https://www.wsj.com/articles/highly-vaccinated-states-keep-worst-covid-19-outcomes-in-check-as-delta-spreads-wsj-analysis-shows-11628328602) from Centers for Disease Control and Prevention (vaccination rates) and the Deptartment of Health and Human Services (hospitalizations). B. Relationship between the percent vaccination and the number of hospitalizations for measles cases in the U.S. [Data](data/13_measles_vax.csv) from Centers for Disease Control and Prevention." width="100%" />
<p class="caption">
Figure 13.7: A. Relationship between COVID-19 vaccination coverage and the number of hospitalizations in U.S. in August of 2021. The red dot indicates the nation-wide avagerage. <a href="data/13_covid_vax.csv">Data</a> compiled by <a href="https://www.wsj.com/articles/highly-vaccinated-states-keep-worst-covid-19-outcomes-in-check-as-delta-spreads-wsj-analysis-shows-11628328602">WSJ</a> from Centers for Disease Control and Prevention (vaccination rates) and the Deptartment of Health and Human Services (hospitalizations). B. Relationship between the percent vaccination and the number of hospitalizations for measles cases in the U.S. <a href="data/13_measles_vax.csv">Data</a> from Centers for Disease Control and Prevention.
</p>
</div>
</div>
<div id="pathogen-responses" class="section level3 hasAnchor" number="13.3.3">
<h3><span class="header-section-number">13.3.3</span> Pathogen Responses<a href="evolutionary-medicine-ii-evolving-pathogens.html#pathogen-responses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One of the most important consequences of successful disease management—whether through the reduction of transmission or the reduction of susceptible individuals in the population—is that we exert selection on a pathogen to evolve a lower virulence. When variables in the numerator of the <em>R</em><sub>0</sub> equation are controlled through cultural practices, a parameter that a population of pathogens still has control over is the virulence, which is in the denominator. So, only decreases in virulence will cause an increase in <em>R</em><sub>0</sub>, and if extrinsic factors reduce <em>R</em><sub>0</sub> below 1, pathogen strains exhibiting mutations conferring a lower virulence should have a higher fitness than those with higher virulence.</p>
<p>Paul Ewald was among the first to popularize the idea that successfully managing pathogen fitness could lead to the evolution of pathogens with reduced virulence. For example, he provided some circumstantial evidence in the 1990s that HIV was evolving a lower virulence in response to the spread of safer sex practices. Later analyses of a well-studied HIV outbreak in rural Uganda indeed provided evidence that the trade-off between virulence and transmission explains the gradual attenuation of HIV through time (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:hivevol">13.8</a>).</p>
<div class="figure"><span style="display:block;" id="fig:hivevol"></span>
<img src="Primer2Evolution_files/figure-html/hivevol-1.png" alt="Evolution of virulence in HIV-1 across time. Reductions in disease transmission have selected for viral strains with lower virulence. [Data](data/13_hiv.csv) from Blanquart et al. (2016)." width="100%" />
<p class="caption">
Figure 13.8: Evolution of virulence in HIV-1 across time. Reductions in disease transmission have selected for viral strains with lower virulence. <a href="data/13_hiv.csv">Data</a> from Blanquart et al. (2016).
</p>
</div>
<p>In summary, being an active participant in public health measures that target disease transmission and aim to increase the number of resistant individuals in a population has three important benefits: (1) protection and minimized disease risk for yourself; (2) herd immunity that provides protection for community members that may not be able to protect themselves; and (3) elimination of pathogens from populations, or—when that is not attainable—selection for pathogen strains with reduced virulence. Approaching disease dynamics and public health issues from evolutionary perspectives has direct applications that are complementary to curative care, which focuses on healing people once they have contracted a disease. Or, as Bill Hamilton highlighted the importance of evolution in public health:</p>
<blockquote>
<p>“It opens our eyes to many quite weird possibilities about disease that most medical scientists, tending to be unaware of current evolutionary thought, don’t think of.” —Bill Hamilton</p>
</blockquote>
</div>
</div>
<div id="antibiotic-resistance" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> Antibiotic Resistance<a href="evolutionary-medicine-ii-evolving-pathogens.html#antibiotic-resistance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Besides emerging diseases, the evolution of antibiotic-resistant bacteria is another major public health issue faced by our society. Antibiotics are antimicrobial substances—many of which are naturally produced by fungi and other organisms—that kill or inhibit the growth of bacteria but not eukaryotic cells. These properties make them applicable for the prophylaxis and treatment of bacterial infections. The mechanisms by which antibiotics work vary widely, but they generally interfere with essential biochemical and physiological pathways that mediate the function of microbial cells. Some antibiotics target the cell wall or the cell membrane; other disrupt the synthesis of microbial DNA or RNA, proteins, or specific metabolites. The discovery and application of antibiotics—starting with Fleming’s discovery of penicillin—transformed medicine and has allowed for the efficient treatment of bacterial diseases that, previously, were often lethal.</p>
<p>The molecular precision with which antibiotics interfere with microbial function is simultaneously one of their biggest weaknesses. Unlike sterilization treatments that apply heat, alcohol, or other cleaning supplies to kill bacterial cells outright, bacteria can evolve adaptations that render antibiotics ineffective or even nonfunctional, thus becoming resistant to their effects. Adaptations that mediate antibiotic resistance include enzymes that metabolize and inactivate antibiotics, modification of targets that make them inert to the effects of antibiotics, modifications of the cell wall that prevent the influx of antibiotics into the cell, and transmembrane transport proteins that can pump antibiotics out of the cell.</p>
<p>Due to their biochemical effects, antibiotics are a source of selection that impact pathogen evolution. The presence of antibiotics increases the fitness of certain genetic variants (those that have resistance alleles), while it decreases the fitness of others (those that lack the resistance alleles). Hence, antibiotics are a source of selection that causes the spread of antibiotic resistant strains in a population.</p>
<p>The broad application of antibiotics in human and veterinary medicine, as well as in livestock production, has lead to a rapid spread of resistant strains across the globe. For example, the prevalence of methicillin-resistant <em>Staphylococcus aureus</em> (MRSA), which is responsible for a variety of difficult-to-treat infections in humans, has increased exponentially since the early 1990s (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:abres">13.9</a>A). There are an estimated 500,000 hospitalizations annually for MRSA infections in the U.S. alone. Of these, about 80,000 cases include severe invasive infections, leading to 11,000 deaths. Considering the death toll, and that the cost of a MRSA-associated hospitalization is over $90,000 per patient, the public health and economic impacts of antibiotic-resistant bacterial pathogens are profound. More importantly, we have also observed the evolution of multi-resistant strains that can evade the effects of multiple antibiotics. Even in rural regions of developing countries, over 92 % of isolated bacterial strains are resistant against certain antibiotics, and 5 % of strains are resistant to combination treatments of seven different antibiotics at once (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:abres">13.9</a>B). Simultaneous resistance to multiple types of antibiotics significantly curtails treatment options, and as a consequence, infections that were easy to treat are becoming lethal problems once again. This problem is exacerbated by the fact that the evolution of antibiotic resistance far outpaces the rate at which we are discovering and developing new antibiotics for clinical use. In fact, the last new class of antibiotics we use in medicine today was discovered in 1987—more than 30 years (almost 900,000 bacterial generations) ago.</p>
<div class="figure"><span style="display:block;" id="fig:abres"></span>
<img src="Primer2Evolution_files/figure-html/abres-1.png" alt="A. Prevlanece of methicillin-resistant *Staphylococcus aureus* (MRSA) in the U.S. from 1993-2005. [Data](data/13_abres1.csv) from CDC. B. Prevalence of antibiotic-resistant bacteria in a rural community of India. Data are presented for different types of antibiotics and for different combination treatments. [Data](data/13_abres2.csv) from Singh et al. (2018)." width="100%" />
<p class="caption">
Figure 13.9: A. Prevlanece of methicillin-resistant <em>Staphylococcus aureus</em> (MRSA) in the U.S. from 1993-2005. <a href="data/13_abres1.csv">Data</a> from CDC. B. Prevalence of antibiotic-resistant bacteria in a rural community of India. Data are presented for different types of antibiotics and for different combination treatments. <a href="data/13_abres2.csv">Data</a> from Singh et al. (2018).
</p>
</div>
<p>The rapid spread of antibiotic-resistant bacteria is primarily a consequence of the broad application of antibiotics. For many decades, antibiotics have been mis- and overused in human medicine and beyond. Such misuses include the inappropriate prescription of antibiotics for viral diseases (flu and cold), failure to take antibiotics for the prescribed course of a treatment, and the excessive intake of antibiotics as a prophylactic. The widespread use of antibiotics causes susceptible strains to disappear, while strains with a mutation conferring resistance benefited from a fitness advantage and became more prevalent. A key question, from an evolutionary perspective, is how we can exert selection on antibiotic strains to favor the maintenance of susceptible strains in a population, so that we can effectively treat infections when they occur.</p>
<p>Key to the solution of this problem is that antibiotic resistance does not come without costs. In absence of antibiotics, resistant strains typically have a lower fitness than susceptible strains. This is likely caused by metabolic inefficiencies and physiological costs associated with resistance mechanisms that reduce microbial growth. Costs associated with antibiotic resistance become evident when we compare the growth rate of resistant bacteria to the growth rates of sensitive strains that are otherwise genetically identical. A recent meta analysis for different types of antibiotics revealed that most resistant strains exhibit a lower fitness than their sensitive counterparts, although the magnitude of difference varies substantially (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:anri">13.10</a>A). In addition, there is a correlation between the degree of resistance (measured as the minimum inhibitory concentration, MIC) and the fitness costs of resistance in absence of an antibiotic (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:anri">13.10</a>B); <em>i.e.</em>, the higher the antibiotic concentration a bacterial strain can tolerate, the lower the fitness of that strain is when competing with sensitive strains in an antibiotic-free environment.</p>
<div class="figure"><span style="display:block;" id="fig:anri"></span>
<img src="Primer2Evolution_files/figure-html/anri-1.png" alt="A. Relative fitness of antibiotic-strains in absence of the antibiotic relative to an equivalent strain that is susceptible. Data is presented for different types of antibiotics, and the gray line indicates equal fitness of the reistant and susceptible strains. [Data](data/13_fitness_cost1.csv) from Melnyk et al. (2015). B. Correlation between the degree of antibiotic resistance and the relative fitness cost; higher resistance is associated with a lower fitness in the absence of an antibiotic. [Data](data/13_fitness_cost2.csv) from Melnyk et al. (2015)." width="100%" />
<p class="caption">
Figure 13.10: A. Relative fitness of antibiotic-strains in absence of the antibiotic relative to an equivalent strain that is susceptible. Data is presented for different types of antibiotics, and the gray line indicates equal fitness of the reistant and susceptible strains. <a href="data/13_fitness_cost1.csv">Data</a> from Melnyk et al. (2015). B. Correlation between the degree of antibiotic resistance and the relative fitness cost; higher resistance is associated with a lower fitness in the absence of an antibiotic. <a href="data/13_fitness_cost2.csv">Data</a> from Melnyk et al. (2015).
</p>
</div>
<p>Given the cost of antibiotic resistance, a primary defense against the spread of resistant strains is to create an environment where susceptible strains have a competitive advantage. Not surprisingly, “The ICU Book”—the primary guide for critical care medicine—states that “the first rule of antibiotics is to try not to use them, and the second rule is try not to use too many of them”. Recognition of the growing problem with antibiotics in the 1990s led some countries to implement restrictions on antibiotic use and launch aggressive campaigns to educate both medical professionals and the the general public about how we curb the spread of resistant strains. In Belgium, for example, these efforts led to a decrease in antibiotic prescription by 36 % from 1998 to 2007. As a consequence, the prevalence of antibiotic resistant <em>Streptococcus pneumoniae</em> started to decrease substantially starting in the year 2000 (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:sucs">13.11</a>). Similarly, erythrimycin-resistant <em>S. pyogenes</em> decreased in prevalence from 17 % to 2 % within just six years (Figure <a href="evolutionary-medicine-ii-evolving-pathogens.html#fig:sucs">13.11</a>). These findings highlight that the spread of resistant strains is reversible, and how proper management of antibiotics can help to prevent issues with resistant strains. Getting the antibiotic-resistance problem under control now is critical, especially because the costs of tolerance—upon which successful management strategies hinge—can decline over time through adaptive evolution (see R exercise).</p>
<div class="figure"><span style="display:block;" id="fig:sucs"></span>
<img src="Primer2Evolution_files/figure-html/sucs-1.png" alt="Prevalence of antibiotic resistant *Streptococcus* species in Belgium. After restructions were put on antibiotic use in the year 2000, the prelavence of resistant strains started to drop. [Data](data/13_endabio.csv) from Goossens et al. (2008)." width="100%" />
<p class="caption">
Figure 13.11: Prevalence of antibiotic resistant <em>Streptococcus</em> species in Belgium. After restructions were put on antibiotic use in the year 2000, the prelavence of resistant strains started to drop. <a href="data/13_endabio.csv">Data</a> from Goossens et al. (2008).
</p>
</div>
</div>
<div id="case-study-covid-19-epidemiology-and-the-cost-of-antibiotic-resistance" class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> Case Study: COVID-19 Epidemiology and the Cost of Antibiotic Resistance<a href="evolutionary-medicine-ii-evolving-pathogens.html#case-study-covid-19-epidemiology-and-the-cost-of-antibiotic-resistance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The R exercise associated with this chapter is composed of two portions; one focusing on the epidemiology of SARS-CoV-2 that is causing the COVID-19 pandemic, and the other focusing on the evolution of costs associated with antibiotic resistance.</p>
<p>In the first part of the exercise, you will calculate the basic reproductive number for SARS-CoV-2 and infer the herd immunity threshold. In addition, you will compare the infection fatality ratios between COVID-19 and the common flu for different age classes in a population. Based on that, you will also calculate the mortality cost associated with natural heard immunity that would have been incurred without the development of successful vaccines.</p>
<p>In the second part of the exercise, you will examine the results of a classic experiment that investigated how costs associated with antibiotic-resistance evolve through time. You will contrast the fitness of genetically identical bacterial strains that only differ in the presence or absence of an antibiotic-resistance allele at an early time point, when that resistance allele just emerged through mutation, and at a much later time point, when bacteria with the resistance allele had evolved in presence of an antibiotic for many generations.</p>
</div>
<div id="practical-skills-data-wrangling-and-log-scales" class="section level2 hasAnchor" number="13.6">
<h2><span class="header-section-number">13.6</span> Practical Skills: Data Wrangling and Log-Scales<a href="evolutionary-medicine-ii-evolving-pathogens.html#practical-skills-data-wrangling-and-log-scales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In <a href="exercises/BIOL520-ex12.zip">this chapter’s R exercise</a>, you can mostly apply the calculation and graphing skills that you have learned in previous chapters. However, some basic data wrangling skills (subsetting and merging) will come in handy during the tasks you have to complete, and changing the scale of the axes of some on your plots will help with data interpretation.</p>
<div id="data-wrangling" class="section level3 hasAnchor" number="13.6.1">
<h3><span class="header-section-number">13.6.1</span> Data Wrangling<a href="evolutionary-medicine-ii-evolving-pathogens.html#data-wrangling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this exercise, you will be subsetting datasets to select (or drop) specific cases (<em>i.e.</em>, rows of data), but for the sake of completion I will also explain how you can subset different variables (<em>i.e.</em>, columns of data). Note that I will focus on the use of the <code>which()</code> function from base R, but other functions can also be used for the same task, including <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/subset"><code>subset()</code></a> from base R, and <a href="https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/filter"><code>filter()</code></a> and <a href="https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/select"><code>select()</code></a> from the <code>dplyr</code> package. The function we will use for merging data frames is called <code>merge()</code> and also comes with base R.</p>
<div id="loading-some-data" class="section level4 unnumbered hasAnchor">
<h4>Loading Some Data<a href="evolutionary-medicine-ii-evolving-pathogens.html#loading-some-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To explain the different subsetting possibilities and merging of data frames, I will use the <a href="data/test_data2.csv">test_data2.csv</a> data set that we have used on other sections of this book. I will also use the <code>summary()</code> function to show how the structure of a data frame changes as a consequence of subsetting.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb143-1" tabindex="-1"></a><span class="co">#Using the test_data2.csv previously used in this book</span></span>
<span id="cb143-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb143-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/test_data2.csv&quot;</span>)</span>
<span id="cb143-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb143-3" tabindex="-1"></a><span class="co">#Use summary to look at data set structure</span></span>
<span id="cb143-4"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb143-4" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code></pre></div>
<pre><code>##        id            sex             population            length     
##  Min.   : 1.00   Length:60          Length:60          Min.   : 81.0  
##  1st Qu.:15.75   Class :character   Class :character   1st Qu.: 98.0  
##  Median :30.50   Mode  :character   Mode  :character   Median :110.5  
##  Mean   :30.50                                         Mean   :110.2  
##  3rd Qu.:45.25                                         3rd Qu.:120.2  
##  Max.   :60.00                                         Max.   :145.0  
##       mass       
##  Min.   : 3.189  
##  1st Qu.: 5.138  
##  Median : 6.422  
##  Mean   : 6.842  
##  3rd Qu.: 8.358  
##  Max.   :13.133</code></pre>
</div>
<div id="selecting-cases" class="section level4 unnumbered hasAnchor">
<h4>Selecting Cases<a href="evolutionary-medicine-ii-evolving-pathogens.html#selecting-cases" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To select specific cases (rows) from a data frame, you can use the <code>which()</code> function from base R and use logical operators to define subsets based on specific criteria. Logical operators include <code>==</code> (equal to), <code>!=</code> (not equal to), <code>&lt;</code> (less than), <code>&gt;</code> (greater than), <code>&lt;=</code> (less than or equal to), <code>&gt;=</code> (greater than or equal to), and <code>!x</code> (not x).</p>
<p>For example, if you want to select samples from the “lake” population from your test data set, you can designate the subset using <code>which(data$population=='lake')</code>. As you can see, only 30 of the original 60 cases are retained in the new data frame:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb145-1" tabindex="-1"></a><span class="co">#Selecting individuals that are from the &quot;lake&quot; population</span></span>
<span id="cb145-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb145-2" tabindex="-1"></a>data.lake <span class="ot">&lt;-</span> data[<span class="fu">which</span>(data<span class="sc">$</span>population<span class="sc">==</span><span class="st">&#39;lake&#39;</span>),]</span>
<span id="cb145-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb145-3" tabindex="-1"></a><span class="fu">summary</span>(data.lake)</span></code></pre></div>
<pre><code>##        id            sex             population            length     
##  Min.   : 1.00   Length:30          Length:30          Min.   : 81.0  
##  1st Qu.: 8.25   Class :character   Class :character   1st Qu.: 94.0  
##  Median :22.50   Mode  :character   Mode  :character   Median :102.0  
##  Mean   :22.50                                         Mean   :105.6  
##  3rd Qu.:36.75                                         3rd Qu.:116.5  
##  Max.   :44.00                                         Max.   :141.0  
##       mass       
##  Min.   : 3.189  
##  1st Qu.: 4.686  
##  Median : 5.559  
##  Mean   : 6.301  
##  3rd Qu.: 8.197  
##  Max.   :11.485</code></pre>
<p>Alternatively, you can choose to drop all the samples from the stream population using <code>which(data$population!='stream'</code> to obtain exactly the same result:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb147-1" tabindex="-1"></a><span class="co">#Selecting individuals that are not from the &quot;stream&quot; population</span></span>
<span id="cb147-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb147-2" tabindex="-1"></a>data.lake <span class="ot">&lt;-</span> data[<span class="fu">which</span>(data<span class="sc">$</span>population<span class="sc">!=</span><span class="st">&#39;stream&#39;</span>), ]</span></code></pre></div>
<p>Selecting cases works the same way for continuous variables. In this example, we are selecting all cases with a length smaller than or equal to 100 using <code>which(data$length&lt;=100)</code>:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb148-1" tabindex="-1"></a><span class="co">#Selecting individuals that are have a length smaller than or equal to 100</span></span>
<span id="cb148-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb148-2" tabindex="-1"></a>data.small <span class="ot">&lt;-</span> data[<span class="fu">which</span>(data<span class="sc">$</span>length<span class="sc">&lt;=</span><span class="dv">100</span>), ]</span>
<span id="cb148-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb148-3" tabindex="-1"></a><span class="fu">summary</span>(data.small)</span></code></pre></div>
<pre><code>##        id            sex             population            length     
##  Min.   : 1.00   Length:18          Length:18          Min.   :81.00  
##  1st Qu.: 9.25   Class :character   Class :character   1st Qu.:87.50  
##  Median :14.50   Mode  :character   Mode  :character   Median :94.00  
##  Mean   :19.00                                         Mean   :91.56  
##  3rd Qu.:29.75                                         3rd Qu.:96.00  
##  Max.   :51.00                                         Max.   :99.00  
##       mass      
##  Min.   :3.189  
##  1st Qu.:3.949  
##  Median :4.690  
##  Mean   :4.571  
##  3rd Qu.:5.247  
##  Max.   :6.202</code></pre>
<p>Finally, you can also combine multiple logical statements with <code>&amp;</code> (AND) or <code>|</code> (OR). This allows you to define subsets based on multiple criteria. For example, you can select data from females that are also shorter than 100 using <code>which(data$sex=='female' &amp; data$length&lt;=100)</code>:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb150-1" tabindex="-1"></a><span class="co">#Selecting individuals that are female AND have a length smaller than or equal to 100</span></span>
<span id="cb150-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb150-2" tabindex="-1"></a>data.smallfemales <span class="ot">&lt;-</span> data[<span class="fu">which</span>(data<span class="sc">$</span>sex<span class="sc">==</span><span class="st">&#39;female&#39;</span> <span class="sc">&amp;</span> data<span class="sc">$</span>length<span class="sc">&lt;=</span><span class="dv">100</span>), ]</span>
<span id="cb150-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb150-3" tabindex="-1"></a><span class="fu">summary</span>(data.smallfemales)</span></code></pre></div>
<pre><code>##        id            sex             population            length     
##  Min.   : 1.00   Length:13          Length:13          Min.   :81.00  
##  1st Qu.: 4.00   Class :character   Class :character   1st Qu.:85.00  
##  Median :11.00   Mode  :character   Mode  :character   Median :90.00  
##  Mean   :11.69                                         Mean   :89.62  
##  3rd Qu.:15.00                                         3rd Qu.:94.00  
##  Max.   :29.00                                         Max.   :98.00  
##       mass      
##  Min.   :3.189  
##  1st Qu.:3.665  
##  Median :4.091  
##  Mean   :4.171  
##  3rd Qu.:4.696  
##  Max.   :5.225</code></pre>
</div>
<div id="selecting-variables" class="section level4 unnumbered hasAnchor">
<h4>Selecting Variables<a href="evolutionary-medicine-ii-evolving-pathogens.html#selecting-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Although not part of this exercise, sometime it is useful to create new data frames with a subset of variables from an original. You can select specific columns in a data frame by just referring to their number, including the colon (<code>:</code>) to designate ranges. For example, the following code chunk simply selects columns 1, 4, and 5 of our sample dataset to make a new one:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb152-1" tabindex="-1"></a><span class="co">#Selecting variables 1 and 4-5</span></span>
<span id="cb152-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb152-2" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> data[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>)]</span>
<span id="cb152-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb152-3" tabindex="-1"></a><span class="fu">summary</span>(newdata)</span></code></pre></div>
<pre><code>##        id            length           mass       
##  Min.   : 1.00   Min.   : 81.0   Min.   : 3.189  
##  1st Qu.:15.75   1st Qu.: 98.0   1st Qu.: 5.138  
##  Median :30.50   Median :110.5   Median : 6.422  
##  Mean   :30.50   Mean   :110.2   Mean   : 6.842  
##  3rd Qu.:45.25   3rd Qu.:120.2   3rd Qu.: 8.358  
##  Max.   :60.00   Max.   :145.0   Max.   :13.133</code></pre>
<p>Alternatively, you can first define a vector with the names of the desired variables you want to keep and then filter an existing data frame based on that:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb154-1" tabindex="-1"></a><span class="co">#Selecting id, length, and mass</span></span>
<span id="cb154-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb154-2" tabindex="-1"></a>myvars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;length&quot;</span>, <span class="st">&quot;mass&quot;</span>)</span>
<span id="cb154-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb154-3" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> data[myvars]</span>
<span id="cb154-4"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb154-4" tabindex="-1"></a><span class="fu">summary</span>(newdata)</span></code></pre></div>
<pre><code>##        id            length           mass       
##  Min.   : 1.00   Min.   : 81.0   Min.   : 3.189  
##  1st Qu.:15.75   1st Qu.: 98.0   1st Qu.: 5.138  
##  Median :30.50   Median :110.5   Median : 6.422  
##  Mean   :30.50   Mean   :110.2   Mean   : 6.842  
##  3rd Qu.:45.25   3rd Qu.:120.2   3rd Qu.: 8.358  
##  Max.   :60.00   Max.   :145.0   Max.   :13.133</code></pre>
<p>Dropping variables based on column numbers works just like selecting them, except that you include <code>-</code> before the number vector:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb156-1" tabindex="-1"></a><span class="co">#Dropping variables 4-5</span></span>
<span id="cb156-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb156-2" tabindex="-1"></a>newdata2 <span class="ot">&lt;-</span> data[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>)]</span>
<span id="cb156-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb156-3" tabindex="-1"></a><span class="fu">summary</span>(newdata2)</span></code></pre></div>
<pre><code>##        id            sex             population       
##  Min.   : 1.00   Length:60          Length:60         
##  1st Qu.:15.75   Class :character   Class :character  
##  Median :30.50   Mode  :character   Mode  :character  
##  Mean   :30.50                                        
##  3rd Qu.:45.25                                        
##  Max.   :60.00</code></pre>
<p>Finally, you can also drop variables based on their name. To do so, you first have to create a logical vector that indicates what variables to retain. Then you can combine that vector with <code>!</code> to generate a new data frame with the subset of desired variables:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb158-1" tabindex="-1"></a><span class="co">#Create logical vector including length, and mass</span></span>
<span id="cb158-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb158-2" tabindex="-1"></a>myvars <span class="ot">&lt;-</span> <span class="fu">names</span>(data) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;length&quot;</span>, <span class="st">&quot;mass&quot;</span>)</span>
<span id="cb158-3"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb158-3" tabindex="-1"></a><span class="co">#Dropping variables based on logical vector</span></span>
<span id="cb158-4"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb158-4" tabindex="-1"></a>newdata2 <span class="ot">&lt;-</span> data[<span class="sc">!</span>myvars]</span>
<span id="cb158-5"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb158-5" tabindex="-1"></a><span class="fu">summary</span>(newdata2)</span></code></pre></div>
<pre><code>##        id            sex             population       
##  Min.   : 1.00   Length:60          Length:60         
##  1st Qu.:15.75   Class :character   Class :character  
##  Median :30.50   Mode  :character   Mode  :character  
##  Mean   :30.50                                        
##  3rd Qu.:45.25                                        
##  Max.   :60.00</code></pre>
</div>
<div id="merging-data-frames" class="section level4 unnumbered hasAnchor">
<h4>Merging Data Frames<a href="evolutionary-medicine-ii-evolving-pathogens.html#merging-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Sometime it is important to merge different data frames so you can perform combined analyses of different data sets or concatenate the results from different analyses. If you want to merge together data frames that contain the same variables but different observations, you can use the <code>rbind()</code> function. For example, the following code creates a new dataset that combines the <code>data.lake</code> and the <code>data.smallfemales</code> data frames we created above:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb160-1" tabindex="-1"></a>comb.data <span class="ot">&lt;-</span> <span class="fu">rbind</span>(data.lake,data.smallfemales)</span>
<span id="cb160-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb160-2" tabindex="-1"></a><span class="fu">summary</span>(comb.data)</span></code></pre></div>
<pre><code>##        id            sex             population            length     
##  Min.   : 1.00   Length:43          Length:43          Min.   : 81.0  
##  1st Qu.: 7.50   Class :character   Class :character   1st Qu.: 89.5  
##  Median :14.00   Mode  :character   Mode  :character   Median : 96.0  
##  Mean   :19.23                                         Mean   :100.7  
##  3rd Qu.:33.50                                         3rd Qu.:111.5  
##  Max.   :44.00                                         Max.   :141.0  
##       mass       
##  Min.   : 3.189  
##  1st Qu.: 4.044  
##  Median : 4.886  
##  Mean   : 5.657  
##  3rd Qu.: 6.384  
##  Max.   :11.485</code></pre>
<p>Similarly, we can use the <code>cbind()</code>function to combine data frames that contain different variables of the same observations. For example, you can combine the newdata and newdata2 data frames we created above with the following code:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb162-1" tabindex="-1"></a>comb.data2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdata,newdata2)</span>
<span id="cb162-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb162-2" tabindex="-1"></a><span class="fu">summary</span>(comb.data2)</span></code></pre></div>
<pre><code>##        id            length           mass              id       
##  Min.   : 1.00   Min.   : 81.0   Min.   : 3.189   Min.   : 1.00  
##  1st Qu.:15.75   1st Qu.: 98.0   1st Qu.: 5.138   1st Qu.:15.75  
##  Median :30.50   Median :110.5   Median : 6.422   Median :30.50  
##  Mean   :30.50   Mean   :110.2   Mean   : 6.842   Mean   :30.50  
##  3rd Qu.:45.25   3rd Qu.:120.2   3rd Qu.: 8.358   3rd Qu.:45.25  
##  Max.   :60.00   Max.   :145.0   Max.   :13.133   Max.   :60.00  
##      sex             population       
##  Length:60          Length:60         
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
## </code></pre>
<p>It is important to note, however, that the <code>cbind()</code> function only works properly when the cases in each data frame are ordered in the exact same way. If not, or if not every case has a reciprocal match in each of the data frames, we can instead use the <code>merge()</code> function. Using, the <code>by</code> argument, we can make sure the cases in the different data sets are matched up properly even when they are sorted in a different way:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb164-1" tabindex="-1"></a>final.data <span class="ot">&lt;-</span> <span class="fu">merge</span>(newdata,newdata2, <span class="at">by=</span><span class="st">&quot;id&quot;</span>)</span>
<span id="cb164-2"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cb164-2" tabindex="-1"></a><span class="fu">summary</span>(final.data)</span></code></pre></div>
<pre><code>##        id            length           mass            sex           
##  Min.   : 1.00   Min.   : 81.0   Min.   : 3.189   Length:60         
##  1st Qu.:15.75   1st Qu.: 98.0   1st Qu.: 5.138   Class :character  
##  Median :30.50   Median :110.5   Median : 6.422   Mode  :character  
##  Mean   :30.50   Mean   :110.2   Mean   : 6.842                     
##  3rd Qu.:45.25   3rd Qu.:120.2   3rd Qu.: 8.358                     
##  Max.   :60.00   Max.   :145.0   Max.   :13.133                     
##   population       
##  Length:60         
##  Class :character  
##  Mode  :character  
##                    
##                    
## </code></pre>
</div>
</div>
</div>
<div id="reflection-questions-12" class="section level2 hasAnchor" number="13.7">
<h2><span class="header-section-number">13.7</span> Reflection Questions<a href="evolutionary-medicine-ii-evolving-pathogens.html#reflection-questions-12" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>In the seminal paper “The dawn of Darwinian Medicine”, George Williams and Randolph Nesse (1991) stated: “Conventional wisdom has it that prolonged host-parasite association leads to a gradual reduction in virulence, with obligate mutualism as the final stage of extended association”. What assumptions underlie this conventional wisdom? Why may those assumptions not hold up to scrutiny?</p></li>
<li><p>Pathogens require a minimum host population size to persist. If a host population is too small, the rate at which infected hosts die or become immune to a pathogen is too high, leading the to the extinction of the pathogen. How would you predict a pathogen to evolve if it were to survive in a small host population?</p></li>
<li><p>Our discussion of disease dynamics has assumed that the outcome of the interaction between a host and a pathogen is solely dependent on traits that a controlled by either the host or the pathogen. What other factors—biotic or abiotic—might influence pathogen spread and evolution in natural populations? How might the spread of diseases and the evolution of virulence change when other factors are also at play?</p></li>
<li><p>From an evolutionary perspective, what is the difference between an antibiotic and disinfectants that you can find in cleaning and medical supplies? Why do we not see the evolution of disinfectant-resistant microbes?</p></li>
<li><p>How can the use of antibiotics in animal production pose a risk to humans?</p></li>
<li><p>What could we do if we wanted antibiotic resistance to evolve as fast as possible?</p></li>
</ol>
</div>
<div id="references-13" class="section level2 hasAnchor" number="13.8">
<h2><span class="header-section-number">13.8</span> References<a href="evolutionary-medicine-ii-evolving-pathogens.html#references-13" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Bell AS, de Roode JC, Sim D, Read AF (2006) <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/j.0014-3820.2006.tb01215.x">Within-host competition in genetically diverse malaria infections: parasite virulence and competitive success</a>. <em>Evolution</em> 60: 1358–1371.</p></li>
<li><p>Blanquart F, Grabowski MK, Herbeck J, Nalugoda F, Serwadda D, Eller MA, Robb ML, Gray R, Kigozi G, Laeyendecker O, Lythgoe KA, Nakigozi G, Quinn TC, Reynolds SJ, Wawer MJ, Fraser C (2016) <a href="https://elifesciences.org/articles/20492">A transmission-virulence evolutionary trade-off explains attenuation of HIV-1 in Uganda</a>. <em>eLife</em> 5: e20492.</p></li>
<li><p>Ewald PW (1983) <a href="https://www.annualreviews.org/doi/10.1146/annurev.es.14.110183.002341">Host-parasite relations, vectors, and the evolution of disease severity</a>. <em>Annual Review of Ecology and Systematics</em> 14: 465–485.</p></li>
<li><p>Ewald PW (1991) <a href="https://www.cambridge.org/core/journals/epidemiology-and-infection/article/waterborne-transmission-and-the-evolution-of-virulence-among-gastrointestinal-bacteria/295EB4F5E51B7AA0D946C27973053725">Waterborne transmission and the evolution of virulence among gastrointestinal bacteria</a>. <em>Epidemiology &amp; Infection</em> 106: 83–119.</p></li>
<li><p>Goossens H, Coenen S, Costers M, De Corte S, De Sutter A, Gordts B, Struelens M (2008) <a href="https://www.eurosurveillance.org/content/10.2807/ese.13.46.19036-en">Achievements of the Belgian antibiotic policy coordination committee (BAPCOC)</a>. <em>Euro Surveillence</em> 13: 1-4.</p></li>
<li><p>Herre EA (1993) <a href="https://www.science.org/doi/abs/10.1126/science.259.5100.1442">Population structure and the evolution of virulence in nematode parasites of fig wasps</a>. <em>Science</em> 259: 1442–1445.</p></li>
<li><p>Jones N (2020) <a href="https://www.nature.com/articles/d41586-020-03519-3">How COVID-19 is changing the cold and flu season</a>. <em>Nature</em> 588: 388–390.</p></li>
<li><p>Melnyk AH, Wong A, Kassen R (2015) <a href="https://onlinelibrary.wiley.com/doi/10.1111/eva.12196">The fitness costs of antibiotic resistance mutations</a>. <em>Evolutionary Applications</em> 8: 273–283.</p></li>
<li><p>Messenger SL, Molineux IJ, Bull JJ (1999) <a href="https://royalsocietypublishing.org/doi/10.1098/rspb.1999.0651">Virulence evolution in a virus obeys a trade-off</a>. <em>Proceedings of the Royal Society B</em> 266: 397–404.</p></li>
<li><p>Peek K (2021) <a href="https://www.scientificamerican.com/article/flu-has-disappeared-worldwide-during-the-covid-pandemic1/">Flu has disappeared for more than a year</a>. <em>Scientific American</em>, Apr 29, 2021.</p></li>
<li><p>Singh AK, Das S, Singh S, Gajamer VR, Pradhan N, Lepcha YD, Tiwari HK (2018) <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199179">Prevalence of antibiotic resistance in commensal <em>Escherichia coli</em> among the children in rural hill communities of Northeast India</a>. <em>PLoS One</em> 13: e0199179.</p></li>
<li><p>Williams GC, Nesse RM (1991) <a href="Williams%20GC,%20Nesse%20RM%20(1991)%20The%20dawn%20of%20Darwinian%20medicine.%20Q%20Rev%20Biol%2066:1–22">The dawn of Darwinian medicine</a>. <em>Quarterly Review of Biology</em> 66:1–22.</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="human-evolution.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": "nullnull",
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
