<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Evolutionary Medicine I: Aging and Diseases of Civilization | A Primer of Evolution</title>
  <meta name="description" content="An Introduction to Evolutionary Thought: Theory, Evidence, and Practice" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Evolutionary Medicine I: Aging and Diseases of Civilization | A Primer of Evolution" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An Introduction to Evolutionary Thought: Theory, Evidence, and Practice" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Evolutionary Medicine I: Aging and Diseases of Civilization | A Primer of Evolution" />
  
  <meta name="twitter:description" content="An Introduction to Evolutionary Thought: Theory, Evidence, and Practice" />
  

<meta name="author" content="Michi Tobler" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="speciation-1.html"/>
<link rel="next" href="evolutionary-medicine-ii-evolving-pathogens.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-F33BYJVTN7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-F33BYJVTN7');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NCY5ZWLVNZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NCY5ZWLVNZ');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#in-the-light-of-evolution"><i class="fa fa-check"></i>In the Light of Evolution</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#beyond-understanding-biodiversity"><i class="fa fa-check"></i>Beyond Understanding Biodiversity</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#an-overview-of-the-semester"><i class="fa fa-check"></i>An Overview of the Semester</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-1-the-basics"><i class="fa fa-check"></i>Part 1: The Basics</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-2-a-genetic-perspective-on-evolution"><i class="fa fa-check"></i>Part 2: A Genetic Perspective on Evolution</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-3-evolutionary-outcomes-in-the-real-world"><i class="fa fa-check"></i>Part 3: Evolutionary Outcomes in the Real World</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-4-applied-evolutionary-biology"><i class="fa fa-check"></i>Part 4: Applied Evolutionary Biology</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i>How to Use This Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html"><i class="fa fa-check"></i>Front Matters</a>
<ul>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html#copyright"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="front-matters.html"><a href="front-matters.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="part"><span><b>I Basic Concepts</b></span></li>
<li class="chapter" data-level="1" data-path="what-evolution-is.html"><a href="what-evolution-is.html"><i class="fa fa-check"></i><b>1</b> What Evolution Is</a>
<ul>
<li class="chapter" data-level="1.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#darwin-and-the-conception-of-a-new-idea"><i class="fa fa-check"></i><b>1.1</b> Darwin and the Conception of a New Idea</a></li>
<li class="chapter" data-level="1.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#two-fundamental-insights"><i class="fa fa-check"></i><b>1.2</b> Two Fundamental Insights</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#predictions"><i class="fa fa-check"></i><b>1.2.1</b> The Pattern: Evolution is Descent with Modification</a></li>
<li class="chapter" data-level="1.2.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#the-process-natural-selection-is-a-mechanism-of-evolution"><i class="fa fa-check"></i><b>1.2.2</b> The Process: Natural Selection is a Mechanism of Evolution</a></li>
<li class="chapter" data-level="1.2.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#distinguishing-between-pattern-and-process"><i class="fa fa-check"></i><b>1.2.3</b> Distinguishing between Pattern and Process</a></li>
<li class="chapter" data-level="1.2.4" data-path="what-evolution-is.html"><a href="what-evolution-is.html#population-thinking"><i class="fa fa-check"></i><b>1.2.4</b> Population Thinking</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#practical-skills-getting-started-with-r"><i class="fa fa-check"></i><b>1.3</b> Practical Skills: Getting Started with R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#what-are-r-and-rstudio"><i class="fa fa-check"></i><b>1.3.1</b> What are R and RStudio?</a></li>
<li class="chapter" data-level="1.3.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#installing-r"><i class="fa fa-check"></i><b>1.3.2</b> Installing R</a></li>
<li class="chapter" data-level="1.3.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#installing-rstudio"><i class="fa fa-check"></i><b>1.3.3</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.3.4" data-path="what-evolution-is.html"><a href="what-evolution-is.html#checking-the-successful-installation"><i class="fa fa-check"></i><b>1.3.4</b> Checking the Successful Installation</a></li>
<li class="chapter" data-level="1.3.5" data-path="what-evolution-is.html"><a href="what-evolution-is.html#some-r-and-rstudio-basics"><i class="fa fa-check"></i><b>1.3.5</b> Some R and RStudio Basics</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="what-evolution-is.html"><a href="what-evolution-is.html#additional-resources"><i class="fa fa-check"></i><b>1.4</b> Additional Resources</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="what-evolution-is.html"><a href="what-evolution-is.html#alternative-evolution-textbooks"><i class="fa fa-check"></i><b>1.4.1</b> Alternative Evolution Textbooks</a></li>
<li class="chapter" data-level="1.4.2" data-path="what-evolution-is.html"><a href="what-evolution-is.html#evolution-in-the-primary-literature-and-the-news"><i class="fa fa-check"></i><b>1.4.2</b> Evolution in the Primary Literature and the News</a></li>
<li class="chapter" data-level="1.4.3" data-path="what-evolution-is.html"><a href="what-evolution-is.html#r-and-rstudio-resources"><i class="fa fa-check"></i><b>1.4.3</b> R and RStudio Resources</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="what-evolution-is.html"><a href="what-evolution-is.html#reflection-questions"><i class="fa fa-check"></i><b>1.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="1.6" data-path="what-evolution-is.html"><a href="what-evolution-is.html#references-1"><i class="fa fa-check"></i><b>1.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html"><i class="fa fa-check"></i><b>2</b> Evidence for Evolution</a>
<ul>
<li class="chapter" data-level="2.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#microevolution"><i class="fa fa-check"></i><b>2.1</b> Microevolution</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#the-case-of-threespine-stickleback"><i class="fa fa-check"></i><b>2.1.1</b> The Case of Threespine Stickleback</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#speciation"><i class="fa fa-check"></i><b>2.2</b> Speciation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#ring-species"><i class="fa fa-check"></i><b>2.2.1</b> Ring Species</a></li>
<li class="chapter" data-level="2.2.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#catching-speciation-in-action"><i class="fa fa-check"></i><b>2.2.2</b> Catching Speciation in Action</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#macroevolution"><i class="fa fa-check"></i><b>2.3</b> Macroevolution</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#geographic-and-temporal-patterns-of-succession"><i class="fa fa-check"></i><b>2.3.1</b> Geographic and Temporal Patterns of Succession</a></li>
<li class="chapter" data-level="2.3.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#transitional-fossils"><i class="fa fa-check"></i><b>2.3.2</b> Transitional Fossils</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#common-ancestry-and-homology"><i class="fa fa-check"></i><b>2.4</b> Common Ancestry and Homology</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#shared-flaws"><i class="fa fa-check"></i><b>2.4.1</b> Shared Flaws</a></li>
<li class="chapter" data-level="2.4.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#why-homologies-matter"><i class="fa fa-check"></i><b>2.4.2</b> Why Homologies Matter</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#deep-time"><i class="fa fa-check"></i><b>2.5</b> Deep Time</a></li>
<li class="chapter" data-level="2.6" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#tiktaalik"><i class="fa fa-check"></i><b>2.6</b> Correspondence of Different Lines of Evidence</a></li>
<li class="chapter" data-level="2.7" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#absence-of-evidence"><i class="fa fa-check"></i><b>2.7</b> Absence of Evidence…</a></li>
<li class="chapter" data-level="2.8" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#case-study-darwins-finches"><i class="fa fa-check"></i><b>2.8</b> Case Study: Darwin’s Finches</a></li>
<li class="chapter" data-level="2.9" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#practical-skills-r-notebooks-and-plotting-with-ggplot"><i class="fa fa-check"></i><b>2.9</b> Practical Skills: R Notebooks and Plotting with ggplot</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#r-notebooks"><i class="fa fa-check"></i><b>2.9.1</b> R Notebooks</a></li>
<li class="chapter" data-level="2.9.2" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#libraries"><i class="fa fa-check"></i><b>2.9.2</b> Using Libraries</a></li>
<li class="chapter" data-level="2.9.3" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#import-data"><i class="fa fa-check"></i><b>2.9.3</b> Importing Data</a></li>
<li class="chapter" data-level="2.9.4" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#graphing-data"><i class="fa fa-check"></i><b>2.9.4</b> Graphing Data</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#reflection-questions-1"><i class="fa fa-check"></i><b>2.10</b> Reflection Questions</a></li>
<li class="chapter" data-level="2.11" data-path="evidence-for-evolution.html"><a href="evidence-for-evolution.html#references-2"><i class="fa fa-check"></i><b>2.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html"><i class="fa fa-check"></i><b>3</b> A Mechanism for Change</a>
<ul>
<li class="chapter" data-level="3.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#darwins-logic"><i class="fa fa-check"></i><b>3.1</b> Darwin’s Logic</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#variation"><i class="fa fa-check"></i><b>3.1.1</b> Variation</a></li>
<li class="chapter" data-level="3.1.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#heritability"><i class="fa fa-check"></i><b>3.1.2</b> Heritability</a></li>
<li class="chapter" data-level="3.1.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#the-struggle-for-existence"><i class="fa fa-check"></i><b>3.1.3</b> The Struggle for Existence</a></li>
<li class="chapter" data-level="3.1.4" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#non-random-survival-and-reproduction"><i class="fa fa-check"></i><b>3.1.4</b> Non-Random Survival and Reproduction</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#putting-darwins-logic-to-the-test"><i class="fa fa-check"></i><b>3.2</b> Putting Darwin’s Logic to the Test</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-there-variation-in-beak-size"><i class="fa fa-check"></i><b>3.2.1</b> Is there Variation in Beak Size?</a></li>
<li class="chapter" data-level="3.2.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-variation-in-beak-size-heritable"><i class="fa fa-check"></i><b>3.2.2</b> Is Variation in Beak Size Heritable?</a></li>
<li class="chapter" data-level="3.2.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-there-a-struggle-for-existence"><i class="fa fa-check"></i><b>3.2.3</b> Is there a Struggle for Existence?</a></li>
<li class="chapter" data-level="3.2.4" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#is-survival-non-random"><i class="fa fa-check"></i><b>3.2.4</b> Is Survival Non-Random?</a></li>
<li class="chapter" data-level="3.2.5" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#did-non-random-survival-lead-to-evolution"><i class="fa fa-check"></i><b>3.2.5</b> Did Non-Random Survival Lead to Evolution?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#case-study-exploring-among-population-variation"><i class="fa fa-check"></i><b>3.3</b> Case Study: Exploring Among-Population Variation</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#the-cave-molly-and-its-ancestors"><i class="fa fa-check"></i><b>3.3.1</b> The Cave Molly and its Ancestors</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#practical-skills-number-sequences-allometry-and-histograms"><i class="fa fa-check"></i><b>3.4</b> Practical Skills: Number Sequences, Allometry, and Histograms</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#number-sequences"><i class="fa fa-check"></i><b>3.4.1</b> Number Sequences</a></li>
<li class="chapter" data-level="3.4.2" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#allometry-residuals"><i class="fa fa-check"></i><b>3.4.2</b> Allometry &amp; Residuals</a></li>
<li class="chapter" data-level="3.4.3" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#histograms-and-density-functions"><i class="fa fa-check"></i><b>3.4.3</b> Histograms and Density Functions</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#reflection-questions-2"><i class="fa fa-check"></i><b>3.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="3.6" data-path="a-mechanism-for-change.html"><a href="a-mechanism-for-change.html#references-3"><i class="fa fa-check"></i><b>3.6</b> References</a></li>
</ul></li>
<li class="part"><span><b>II A Genetic Perspective on Evolution</b></span></li>
<li class="chapter" data-level="4" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html"><i class="fa fa-check"></i><b>4</b> The Raw Materials for Evolution</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#the-genotype-phenotype-gap"><i class="fa fa-check"></i><b>4.1</b> The Genotype-Phenotype Gap</a></li>
<li class="chapter" data-level="4.2" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#mutation-the-fundamental-source-of-novelty"><i class="fa fa-check"></i><b>4.2</b> Mutation: The Fundamental Source of Novelty</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#point-mutations"><i class="fa fa-check"></i><b>4.2.1</b> Point Mutations</a></li>
<li class="chapter" data-level="4.2.2" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#inversions"><i class="fa fa-check"></i><b>4.2.2</b> Inversions</a></li>
<li class="chapter" data-level="4.2.3" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#gene-duplication"><i class="fa fa-check"></i><b>4.2.3</b> Gene Duplication</a></li>
<li class="chapter" data-level="4.2.4" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#genome-duplication"><i class="fa fa-check"></i><b>4.2.4</b> Genome Duplication</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#mutation-rates"><i class="fa fa-check"></i><b>4.3</b> Mutation Rates</a></li>
<li class="chapter" data-level="4.4" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#quantifying-genetic-variation"><i class="fa fa-check"></i><b>4.4</b> Quantifying Genetic Variation</a></li>
<li class="chapter" data-level="4.5" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#a-null-model-for-evolution"><i class="fa fa-check"></i><b>4.5</b> A Null Model for Evolution</a></li>
<li class="chapter" data-level="4.6" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#case-study-hardy-weinberg-equilirbium"><i class="fa fa-check"></i><b>4.6</b> Case Study: Hardy-Weinberg Equilirbium</a></li>
<li class="chapter" data-level="4.7" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#practical-skills-number-sequences-2.0-and-complex-graphs"><i class="fa fa-check"></i><b>4.7</b> Practical Skills: Number Sequences 2.0 and Complex Graphs</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#number-sequences-1"><i class="fa fa-check"></i><b>4.7.1</b> Number Sequences</a></li>
<li class="chapter" data-level="4.7.2" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#layering-data-sets"><i class="fa fa-check"></i><b>4.7.2</b> Layering Data Sets</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#reflection-questions-3"><i class="fa fa-check"></i><b>4.8</b> Reflection Questions</a></li>
<li class="chapter" data-level="4.9" data-path="the-raw-materials-for-evolution.html"><a href="the-raw-materials-for-evolution.html#references-4"><i class="fa fa-check"></i><b>4.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html"><i class="fa fa-check"></i><b>5</b> Evolutionary Mechanisms I: Modeling Selection</a>
<ul>
<li class="chapter" data-level="5.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#the-effects-of-selection"><i class="fa fa-check"></i><b>5.1</b> The Effects of Selection</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#frequency-dependent-selection"><i class="fa fa-check"></i><b>5.1.1</b> Frequency-Dependent Selection</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#modeling-the-effects-of-selection"><i class="fa fa-check"></i><b>5.2</b> Modeling the Effects of Selection</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#relative-fitness"><i class="fa fa-check"></i><b>5.2.1</b> Relative Fitness</a></li>
<li class="chapter" data-level="5.2.2" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#calculating-allele-frequency-changes"><i class="fa fa-check"></i><b>5.2.2</b> Calculating Allele Frequency Changes</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#case-study-modeling-selection"><i class="fa fa-check"></i><b>5.3</b> Case Study: Modeling Selection</a></li>
<li class="chapter" data-level="5.4" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#practical-skills"><i class="fa fa-check"></i><b>5.4</b> Practical Skills: Modeling Selection</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#modeling-selection"><i class="fa fa-check"></i><b>5.4.1</b> Modeling Selection</a></li>
<li class="chapter" data-level="5.4.2" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#running-multiple-selection-models"><i class="fa fa-check"></i><b>5.4.2</b> Running Multiple Selection Models</a></li>
<li class="chapter" data-level="5.4.3" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#frequency-dependent-selection-1"><i class="fa fa-check"></i><b>5.4.3</b> Frequency-Dependent Selection</a></li>
<li class="chapter" data-level="5.4.4" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#understanding-equilibria"><i class="fa fa-check"></i><b>5.4.4</b> Understanding Equilibria</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#reflection-questions-4"><i class="fa fa-check"></i><b>5.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="5.6" data-path="evolutionary-mechanisms-i-modeling-selection.html"><a href="evolutionary-mechanisms-i-modeling-selection.html#references-5"><i class="fa fa-check"></i><b>5.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><i class="fa fa-check"></i><b>6</b> Evolutionary Mechanisms II: Mutation, Genetic Drift, Migration, and Non-Random Mating</a>
<ul>
<li class="chapter" data-level="6.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#mutation-the-force-creating-novelty"><i class="fa fa-check"></i><b>6.1</b> Mutation: The Force Creating Novelty</a></li>
<li class="chapter" data-level="6.2" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#genetic-drift-the-random-force"><i class="fa fa-check"></i><b>6.2</b> Genetic Drift: The Random Force</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#interactions-between-drift-and-selection"><i class="fa fa-check"></i><b>6.2.1</b> Interactions Between Drift and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#migration-the-homogenizing-force"><i class="fa fa-check"></i><b>6.3</b> Migration: The Homogenizing Force</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#interactions-between-migration-and-selection"><i class="fa fa-check"></i><b>6.3.1</b> Interactions Between Migration and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#non-random-mating-not-much-of-a-force"><i class="fa fa-check"></i><b>6.4</b> Non-Random Mating: Not Much of a Force</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#interactions-between-inbreeding-and-selection"><i class="fa fa-check"></i><b>6.4.1</b> Interactions between Inbreeding and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#case-study-background-beyond-selection"><i class="fa fa-check"></i><b>6.5</b> Case Study Background: Beyond Selection</a></li>
<li class="chapter" data-level="6.6" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#practical-skills-modeling-mutation-drift-and-selection"><i class="fa fa-check"></i><b>6.6</b> Practical Skills: Modeling Mutation, Drift, and Selection</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#modeling-mutation-and-selection"><i class="fa fa-check"></i><b>6.6.1</b> Modeling Mutation and Selection</a></li>
<li class="chapter" data-level="6.6.2" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#modeling-genetic-drift"><i class="fa fa-check"></i><b>6.6.2</b> Modeling Genetic Drift</a></li>
<li class="chapter" data-level="6.6.3" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#modeling-genetic-drift-and-selection"><i class="fa fa-check"></i><b>6.6.3</b> Modeling Genetic Drift and Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#reflection-questions-5"><i class="fa fa-check"></i><b>6.7</b> Reflection Questions</a></li>
<li class="chapter" data-level="6.8" data-path="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html"><a href="evolutionary-mechanisms-ii-mutation-genetic-drift-migration-and-non-random-mating.html#references-6"><i class="fa fa-check"></i><b>6.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html"><i class="fa fa-check"></i><b>7</b> Evolution of DNA Sequences</a>
<ul>
<li class="chapter" data-level="7.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#dna-alignment-and-genome-assembly"><i class="fa fa-check"></i><b>7.1</b> DNA Alignment and Genome Assembly</a></li>
<li class="chapter" data-level="7.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#reconstructing-history-phylogenetic-trees"><i class="fa fa-check"></i><b>7.2</b> Reconstructing History: Phylogenetic Trees</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#molecular-phylogenies"><i class="fa fa-check"></i><b>7.2.1</b> Molecular Phylogenies</a></li>
<li class="chapter" data-level="7.2.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#molecular-phylogenies-in-real-life"><i class="fa fa-check"></i><b>7.2.2</b> Molecular Phylogenies in Real Life</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#the-neutral-theory"><i class="fa fa-check"></i><b>7.3</b> The Neutral Theory</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#molecular-clocks"><i class="fa fa-check"></i><b>7.3.1</b> Molecular Clocks</a></li>
<li class="chapter" data-level="7.3.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#detecting-signatures-of-selection"><i class="fa fa-check"></i><b>7.3.2</b> Detecting Signatures of Selection</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#case-study-sars-cov-2"><i class="fa fa-check"></i><b>7.4</b> Case Study: SARS-CoV-2</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#host-pathogen-coevolution"><i class="fa fa-check"></i><b>7.4.1</b> Host-Pathogen Coevolution</a></li>
<li class="chapter" data-level="7.4.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#the-evolution-of-the-seasonal-flu"><i class="fa fa-check"></i><b>7.4.2</b> The Evolution of the Seasonal Flu</a></li>
<li class="chapter" data-level="7.4.3" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#high-virulence-flu-strains"><i class="fa fa-check"></i><b>7.4.3</b> High-Virulence Flu Strains</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#practical-skills-working-with-phylogenetic-trees"><i class="fa fa-check"></i><b>7.5</b> Practical Skills: Working with Phylogenetic Trees</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#installing-dependencies"><i class="fa fa-check"></i><b>7.5.1</b> Installing Dependencies</a></li>
<li class="chapter" data-level="7.5.2" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#the-pipe-operator"><i class="fa fa-check"></i><b>7.5.2</b> The Pipe Operator</a></li>
<li class="chapter" data-level="7.5.3" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#importing-a-tree"><i class="fa fa-check"></i><b>7.5.3</b> Importing a Tree</a></li>
<li class="chapter" data-level="7.5.4" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#plotting-a-tree"><i class="fa fa-check"></i><b>7.5.4</b> Plotting a Tree</a></li>
<li class="chapter" data-level="7.5.5" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#annotating-a-tree"><i class="fa fa-check"></i><b>7.5.5</b> Annotating a Tree</a></li>
<li class="chapter" data-level="7.5.6" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#calculating-the-distance-to-root"><i class="fa fa-check"></i><b>7.5.6</b> Calculating the Distance to Root</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#reflection-questions-6"><i class="fa fa-check"></i><b>7.6</b> Reflection Questions</a></li>
<li class="chapter" data-level="7.7" data-path="evolution-of-dna-sequences.html"><a href="evolution-of-dna-sequences.html#references-7"><i class="fa fa-check"></i><b>7.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html"><i class="fa fa-check"></i><b>8</b> The Evolution of Quantitative Traits</a>
<ul>
<li class="chapter" data-level="8.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#qualitative-traits-and-epistasis"><i class="fa fa-check"></i><b>8.1</b> Qualitative Traits and Epistasis</a></li>
<li class="chapter" data-level="8.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantitative-traits-a-product-of-genes-and-environment"><i class="fa fa-check"></i><b>8.2</b> Quantitative Traits: a Product of Genes and Environment</a></li>
<li class="chapter" data-level="8.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantitative-trait-evolution"><i class="fa fa-check"></i><b>8.3</b> Quantitative Trait Evolution</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantifying-trait-heritability"><i class="fa fa-check"></i><b>8.3.1</b> Quantifying Trait Heritability</a></li>
<li class="chapter" data-level="8.3.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#quantifying-the-strength-of-selection"><i class="fa fa-check"></i><b>8.3.2</b> Quantifying the Strength of Selection</a></li>
<li class="chapter" data-level="8.3.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#calculating-the-response-to-selection"><i class="fa fa-check"></i><b>8.3.3</b> Calculating the Response to Selection</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#modes-of-selection-on-quantitative-traits"><i class="fa fa-check"></i><b>8.4</b> Modes of Selection on Quantitative Traits</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#directional-selection"><i class="fa fa-check"></i><b>8.4.1</b> Directional Selection</a></li>
<li class="chapter" data-level="8.4.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#stabilizing-selection"><i class="fa fa-check"></i><b>8.4.2</b> Stabilizing Selection</a></li>
<li class="chapter" data-level="8.4.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#disruptive-selection"><i class="fa fa-check"></i><b>8.4.3</b> Disruptive Selection</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#identifying-genes-underlying-quantitative-traits"><i class="fa fa-check"></i><b>8.5</b> Identifying Genes Underlying Quantitative Traits</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#qtl-mapping"><i class="fa fa-check"></i><b>8.5.1</b> QTL Mapping</a></li>
<li class="chapter" data-level="8.5.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#gwas"><i class="fa fa-check"></i><b>8.5.2</b> GWAS</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#case-study-quantitative-genetics"><i class="fa fa-check"></i><b>8.6</b> Case Study: Quantitative Genetics</a></li>
<li class="chapter" data-level="8.7" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#practical-skills-qtl-mapping"><i class="fa fa-check"></i><b>8.7</b> Practical Skills: QTL Mapping</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#installing-dependencies-1"><i class="fa fa-check"></i><b>8.7.1</b> Installing Dependencies</a></li>
<li class="chapter" data-level="8.7.2" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#read-qtl-data"><i class="fa fa-check"></i><b>8.7.2</b> Read QTL Data</a></li>
<li class="chapter" data-level="8.7.3" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#explore-the-data-genotypes-loci-linkage-map"><i class="fa fa-check"></i><b>8.7.3</b> Explore the Data: Genotypes, Loci &amp; Linkage Map</a></li>
<li class="chapter" data-level="8.7.4" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#explore-the-data-phenotypes"><i class="fa fa-check"></i><b>8.7.4</b> Explore the Data: Phenotypes</a></li>
<li class="chapter" data-level="8.7.5" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#qtl-scan"><i class="fa fa-check"></i><b>8.7.5</b> QTL Scan</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#reflection-questions-7"><i class="fa fa-check"></i><b>8.8</b> Reflection Questions</a></li>
<li class="chapter" data-level="8.9" data-path="the-evolution-of-quantitative-traits.html"><a href="the-evolution-of-quantitative-traits.html#references-8"><i class="fa fa-check"></i><b>8.9</b> References</a></li>
</ul></li>
<li class="part"><span><b>III Evolution in the Real World</b></span></li>
<li class="chapter" data-level="9" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html"><i class="fa fa-check"></i><b>9</b> Adaptation and Phenotypic Plasticity</a>
<ul>
<li class="chapter" data-level="9.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#inferring-adaptation"><i class="fa fa-check"></i><b>9.1</b> Inferring Adaptation</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#interspecific-comparisons"><i class="fa fa-check"></i><b>9.1.1</b> Interspecific Comparisons</a></li>
<li class="chapter" data-level="9.1.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#intraspecific-studies"><i class="fa fa-check"></i><b>9.1.2</b> Intraspecific Studies</a></li>
<li class="chapter" data-level="9.1.3" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#local-adaptation-within-species"><i class="fa fa-check"></i><b>9.1.3</b> Local Adaptation within Species</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#phenotypic-plasticity"><i class="fa fa-check"></i><b>9.2</b> Phenotypic Plasticity</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#types-of-phenotypic-plasticity"><i class="fa fa-check"></i><b>9.2.1</b> Types of Phenotypic Plasticity</a></li>
<li class="chapter" data-level="9.2.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#reaction-norms-and-the-evolution-of-plasticity"><i class="fa fa-check"></i><b>9.2.2</b> Reaction Norms and the Evolution of Plasticity</a></li>
<li class="chapter" data-level="9.2.3" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#adaptive-and-maladaptive-phenotypic-plasticity"><i class="fa fa-check"></i><b>9.2.3</b> Adaptive and Maladaptive Phenotypic Plasticity</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#case-study-local-adaptation-and-phenotypic-plasticity"><i class="fa fa-check"></i><b>9.3</b> Case Study: Local Adaptation and Phenotypic Plasticity</a></li>
<li class="chapter" data-level="9.4" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#practical-skills-more-variables-more-graphs"><i class="fa fa-check"></i><b>9.4</b> Practical Skills: More Variables, More Graphs</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#example-1-many-independent-variables"><i class="fa fa-check"></i><b>9.4.1</b> Example 1: Many Independent Variables</a></li>
<li class="chapter" data-level="9.4.2" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#example-2-many-dependent-variables"><i class="fa fa-check"></i><b>9.4.2</b> Example 2: Many Dependent Variables</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#reflection-questions-8"><i class="fa fa-check"></i><b>9.5</b> Reflection Questions</a></li>
<li class="chapter" data-level="9.6" data-path="adaptation-and-phenotypic-plasticity.html"><a href="adaptation-and-phenotypic-plasticity.html#references-9"><i class="fa fa-check"></i><b>9.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html"><i class="fa fa-check"></i><b>10</b> Social Behavior and Sexual Selection</a>
<ul>
<li class="chapter" data-level="10.1" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#social-behavior"><i class="fa fa-check"></i><b>10.1</b> Social Behavior</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#kin-selection"><i class="fa fa-check"></i><b>10.1.1</b> Kin Selection</a></li>
<li class="chapter" data-level="10.1.2" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#reciprocal-altruism"><i class="fa fa-check"></i><b>10.1.2</b> Reciprocal Altruism</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#sexual-selection"><i class="fa fa-check"></i><b>10.2</b> Sexual Selection</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#causes-of-sexual-selection"><i class="fa fa-check"></i><b>10.2.1</b> Causes of Sexual Selection</a></li>
<li class="chapter" data-level="10.2.2" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#intrasexual-selection-male-male-competition"><i class="fa fa-check"></i><b>10.2.2</b> Intrasexual Selection: Male-Male Competition</a></li>
<li class="chapter" data-level="10.2.3" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#sexual-conflict"><i class="fa fa-check"></i><b>10.2.3</b> Sexual Conflict</a></li>
<li class="chapter" data-level="10.2.4" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#intersexual-selection-female-mate-choice"><i class="fa fa-check"></i><b>10.2.4</b> Intersexual Selection: Female Mate Choice</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#case-study-altruism-and-sexual-selection"><i class="fa fa-check"></i><b>10.3</b> Case Study: Altruism and Sexual Selection</a></li>
<li class="chapter" data-level="10.4" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#reflection-questions-9"><i class="fa fa-check"></i><b>10.4</b> Reflection Questions</a></li>
<li class="chapter" data-level="10.5" data-path="social-behavior-and-sexual-selection.html"><a href="social-behavior-and-sexual-selection.html#references-10"><i class="fa fa-check"></i><b>10.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="speciation-1.html"><a href="speciation-1.html"><i class="fa fa-check"></i><b>11</b> Speciation</a>
<ul>
<li class="chapter" data-level="11.1" data-path="speciation-1.html"><a href="speciation-1.html#species-and-species-concepts"><i class="fa fa-check"></i><b>11.1</b> Species and Species Concepts</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="speciation-1.html"><a href="speciation-1.html#the-biological-species-concept"><i class="fa fa-check"></i><b>11.1.1</b> The Biological Species Concept</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="speciation-1.html"><a href="speciation-1.html#speciation-as-a-gradual-process"><i class="fa fa-check"></i><b>11.2</b> Speciation as a Gradual Process</a></li>
<li class="chapter" data-level="11.3" data-path="speciation-1.html"><a href="speciation-1.html#mechanisms-of-reproductive-isolation"><i class="fa fa-check"></i><b>11.3</b> Mechanisms of Reproductive Isolation</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="speciation-1.html"><a href="speciation-1.html#pre-mating-isolation"><i class="fa fa-check"></i><b>11.3.1</b> Pre-Mating Isolation</a></li>
<li class="chapter" data-level="11.3.2" data-path="speciation-1.html"><a href="speciation-1.html#post-mating-pre-zygotic-isolation"><i class="fa fa-check"></i><b>11.3.2</b> Post-Mating, Pre-zygotic Isolation</a></li>
<li class="chapter" data-level="11.3.3" data-path="speciation-1.html"><a href="speciation-1.html#post-zygotic-isolation"><i class="fa fa-check"></i><b>11.3.3</b> Post-Zygotic Isolation</a></li>
<li class="chapter" data-level="11.3.4" data-path="speciation-1.html"><a href="speciation-1.html#reproductive-isolation-as-a-complex-trait"><i class="fa fa-check"></i><b>11.3.4</b> Reproductive Isolation as a Complex Trait</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="speciation-1.html"><a href="speciation-1.html#the-evolution-of-reproductive-isolation"><i class="fa fa-check"></i><b>11.4</b> The Evolution of Reproductive Isolation</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="speciation-1.html"><a href="speciation-1.html#polyploidization-and-instantaneous-speciation"><i class="fa fa-check"></i><b>11.4.1</b> Polyploidization and Instantaneous Speciation</a></li>
<li class="chapter" data-level="11.4.2" data-path="speciation-1.html"><a href="speciation-1.html#allopatric-speciation-and-hybridization"><i class="fa fa-check"></i><b>11.4.2</b> Allopatric Speciation and Hybridization</a></li>
<li class="chapter" data-level="11.4.3" data-path="speciation-1.html"><a href="speciation-1.html#ecological-speciation"><i class="fa fa-check"></i><b>11.4.3</b> Ecological Speciation</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="speciation-1.html"><a href="speciation-1.html#adaptive-radiation"><i class="fa fa-check"></i><b>11.5</b> Adaptive Radiation</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="speciation-1.html"><a href="speciation-1.html#african-cichlid-fishes"><i class="fa fa-check"></i><b>11.5.1</b> African Cichlid Fishes</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="speciation-1.html"><a href="speciation-1.html#case-study-speciation"><i class="fa fa-check"></i><b>11.6</b> Case Study: Speciation</a></li>
<li class="chapter" data-level="11.7" data-path="speciation-1.html"><a href="speciation-1.html#practical-skills-interpreting-structure-plots"><i class="fa fa-check"></i><b>11.7</b> Practical Skills: Interpreting Structure Plots</a></li>
<li class="chapter" data-level="11.8" data-path="speciation-1.html"><a href="speciation-1.html#reflection-questions-10"><i class="fa fa-check"></i><b>11.8</b> Reflection Questions</a></li>
<li class="chapter" data-level="11.9" data-path="speciation-1.html"><a href="speciation-1.html#references-11"><i class="fa fa-check"></i><b>11.9</b> References</a></li>
</ul></li>
<li class="part"><span><b>IV Applied Evolutionary Biology</b></span></li>
<li class="chapter" data-level="12" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><i class="fa fa-check"></i><b>12</b> Evolutionary Medicine I: Aging and Diseases of Civilization</a>
<ul>
<li class="chapter" data-level="12.1" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#darwinian-medicine"><i class="fa fa-check"></i><b>12.1</b> Darwinian Medicine</a></li>
<li class="chapter" data-level="12.2" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#diseases-of-civilization"><i class="fa fa-check"></i><b>12.2</b> Diseases of Civilization</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#modern-hunter-gatherers-and-urbanites"><i class="fa fa-check"></i><b>12.2.1</b> Modern Hunter-Gatherers and Urbanites</a></li>
<li class="chapter" data-level="12.2.2" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#old-adaptations-in-a-modern-world"><i class="fa fa-check"></i><b>12.2.2</b> Old Adaptations in a Modern World</a></li>
<li class="chapter" data-level="12.2.3" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#an-example-breast-cancer"><i class="fa fa-check"></i><b>12.2.3</b> An Example: Breast Cancer</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#why-we-age-and-die"><i class="fa fa-check"></i><b>12.3</b> Why We Age… and Die</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#rate-of-living-hypothesis"><i class="fa fa-check"></i><b>12.3.1</b> Rate of Living Hypothesis</a></li>
<li class="chapter" data-level="12.3.2" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#evolutionary-theories-of-aging"><i class="fa fa-check"></i><b>12.3.2</b> Evolutionary Theories of Aging</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#case-study-evolution-of-aging"><i class="fa fa-check"></i><b>12.4</b> Case Study: Evolution of Aging</a></li>
<li class="chapter" data-level="12.5" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#practical-skills-life-table-analysis"><i class="fa fa-check"></i><b>12.5</b> Practical Skills: Life Table Analysis</a></li>
<li class="chapter" data-level="12.6" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#reflection-questions-11"><i class="fa fa-check"></i><b>12.6</b> Reflection Questions</a></li>
<li class="chapter" data-level="12.7" data-path="evolutionary-medicine-i-aging-and-diseases-of-civilization.html"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#references-12"><i class="fa fa-check"></i><b>12.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html"><i class="fa fa-check"></i><b>13</b> Evolutionary Medicine II: Evolving Pathogens</a>
<ul>
<li class="chapter" data-level="13.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#epidemiology-and-pathogen-fitness"><i class="fa fa-check"></i><b>13.1</b> Epidemiology and Pathogen Fitness</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#a-basic-epidemiological-model"><i class="fa fa-check"></i><b>13.1.1</b> A Basic Epidemiological model</a></li>
<li class="chapter" data-level="13.1.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#r0-a-measure-of-pathogen-fitness"><i class="fa fa-check"></i><b>13.1.2</b> <em>R</em><sub>0</sub>: A Measure of Pathogen Fitness</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#the-evolution-of-virulence"><i class="fa fa-check"></i><b>13.2</b> The Evolution of Virulence</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#trade-offs-and-modes-of-transmission"><i class="fa fa-check"></i><b>13.2.1</b> Trade-Offs and Modes of Transmission</a></li>
<li class="chapter" data-level="13.2.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#short-sighted-and-coincidental-evolution-hypotheses"><i class="fa fa-check"></i><b>13.2.2</b> Short-Sighted and Coincidental Evolution Hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#cultural-practices-disease-spread-and-evolution"><i class="fa fa-check"></i><b>13.3</b> Cultural Practices, Disease Spread, and Evolution</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#disrupting-pathogen-transmission"><i class="fa fa-check"></i><b>13.3.1</b> Disrupting Pathogen Transmission</a></li>
<li class="chapter" data-level="13.3.2" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#vaccination-and-herd-immunity"><i class="fa fa-check"></i><b>13.3.2</b> Vaccination and Herd Immunity</a></li>
<li class="chapter" data-level="13.3.3" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#pathogen-responses"><i class="fa fa-check"></i><b>13.3.3</b> Pathogen Responses</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#antibiotic-resistance"><i class="fa fa-check"></i><b>13.4</b> Antibiotic Resistance</a></li>
<li class="chapter" data-level="13.5" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#case-study-covid-19-epidemiology-and-the-cost-of-antibiotic-resistance"><i class="fa fa-check"></i><b>13.5</b> Case Study: COVID-19 Epidemiology and the Cost of Antibiotic Resistance</a></li>
<li class="chapter" data-level="13.6" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#practical-skills-data-wrangling-and-log-scales"><i class="fa fa-check"></i><b>13.6</b> Practical Skills: Data Wrangling and Log-Scales</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#data-wrangling"><i class="fa fa-check"></i><b>13.6.1</b> Data Wrangling</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#reflection-questions-12"><i class="fa fa-check"></i><b>13.7</b> Reflection Questions</a></li>
<li class="chapter" data-level="13.8" data-path="evolutionary-medicine-ii-evolving-pathogens.html"><a href="evolutionary-medicine-ii-evolving-pathogens.html#references-13"><i class="fa fa-check"></i><b>13.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="human-evolution.html"><a href="human-evolution.html"><i class="fa fa-check"></i><b>14</b> Human Evolution</a>
<ul>
<li class="chapter" data-level="14.1" data-path="human-evolution.html"><a href="human-evolution.html#phylogenetic-position"><i class="fa fa-check"></i><b>14.1</b> Phylogenetic Position</a></li>
<li class="chapter" data-level="14.2" data-path="human-evolution.html"><a href="human-evolution.html#what-the-fossils-say"><i class="fa fa-check"></i><b>14.2</b> What the Fossils Say</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="human-evolution.html"><a href="human-evolution.html#an-abridged-timeline"><i class="fa fa-check"></i><b>14.2.1</b> An Abridged Timeline</a></li>
<li class="chapter" data-level="14.2.2" data-path="human-evolution.html"><a href="human-evolution.html#evolutionary-trends"><i class="fa fa-check"></i><b>14.2.2</b> Evolutionary Trends</a></li>
<li class="chapter" data-level="14.2.3" data-path="human-evolution.html"><a href="human-evolution.html#a-lone-survivor-of-an-extinct-radiation"><i class="fa fa-check"></i><b>14.2.3</b> A Lone Survivor of an Extinct Radiation</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="human-evolution.html"><a href="human-evolution.html#modern-human-origins"><i class="fa fa-check"></i><b>14.3</b> Modern Human Origins</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="human-evolution.html"><a href="human-evolution.html#hypotheses"><i class="fa fa-check"></i><b>14.3.1</b> Hypotheses</a></li>
<li class="chapter" data-level="14.3.2" data-path="human-evolution.html"><a href="human-evolution.html#multiregional-evolution-vs.-out-of-africa"><i class="fa fa-check"></i><b>14.3.2</b> Multiregional Evolution <em>vs</em>. Out-Of-Africa</a></li>
<li class="chapter" data-level="14.3.3" data-path="human-evolution.html"><a href="human-evolution.html#out-of-africa-vs.-hybridization-and-assimilation"><i class="fa fa-check"></i><b>14.3.3</b> Out-of-Africa <em>vs</em>. Hybridization-and-Assimilation</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="human-evolution.html"><a href="human-evolution.html#what-makes-us-human"><i class="fa fa-check"></i><b>14.4</b> What Makes Us Human?</a></li>
<li class="chapter" data-level="14.5" data-path="human-evolution.html"><a href="human-evolution.html#case-study-modern-human-origins"><i class="fa fa-check"></i><b>14.5</b> Case Study: Modern Human Origins</a></li>
<li class="chapter" data-level="14.6" data-path="human-evolution.html"><a href="human-evolution.html#reflection-questions-13"><i class="fa fa-check"></i><b>14.6</b> Reflection Questions</a></li>
<li class="chapter" data-level="14.7" data-path="human-evolution.html"><a href="human-evolution.html#references-14"><i class="fa fa-check"></i><b>14.7</b> References</a></li>
</ul></li>
<li class="part"><span><b>V Interactive Simulations</b></span></li>
<li class="chapter" data-level="" data-path="simulating-selection.html"><a href="simulating-selection.html"><i class="fa fa-check"></i>Simulating Selection</a></li>
<li class="chapter" data-level="" data-path="simulating-genetic-drift.html"><a href="simulating-genetic-drift.html"><i class="fa fa-check"></i>Simulating Genetic Drift</a></li>
<li class="chapter" data-level="" data-path="simulating-mutation-and-selection.html"><a href="simulating-mutation-and-selection.html"><i class="fa fa-check"></i>Simulating Mutation and Selection</a></li>
<li class="chapter" data-level="" data-path="simulating-genetic-drift-and-selection.html"><a href="simulating-genetic-drift-and-selection.html"><i class="fa fa-check"></i>Simulating Genetic Drift and Selection</a></li>
<li class="appendix"><span><b>Appendix I</b></span></li>
<li class="chapter" data-level="" data-path="graph-library.html"><a href="graph-library.html"><i class="fa fa-check"></i>Graph Library</a>
<ul>
<li class="chapter" data-level="8" data-path="graph-library.html"><a href="graph-library.html#sample-data"><i class="fa fa-check"></i><b>8</b> Sample Data</a></li>
<li class="chapter" data-level="9" data-path="graph-library.html"><a href="graph-library.html#loading-dependencies"><i class="fa fa-check"></i><b>9</b> Loading Dependencies</a></li>
<li class="chapter" data-level="10" data-path="graph-library.html"><a href="graph-library.html#one-variable-continuous"><i class="fa fa-check"></i><b>10</b> One Variable: Continuous</a>
<ul>
<li class="chapter" data-level="10.1" data-path="graph-library.html"><a href="graph-library.html#frequency-histogram"><i class="fa fa-check"></i><b>10.1</b> Frequency Histogram</a></li>
<li class="chapter" data-level="10.2" data-path="graph-library.html"><a href="graph-library.html#density-plot"><i class="fa fa-check"></i><b>10.2</b> Density Plot</a></li>
<li class="chapter" data-level="10.3" data-path="graph-library.html"><a href="graph-library.html#frequency-histogram-with-density"><i class="fa fa-check"></i><b>10.3</b> Frequency Histogram with Density</a></li>
<li class="chapter" data-level="10.4" data-path="graph-library.html"><a href="graph-library.html#adding-a-discrete-variable"><i class="fa fa-check"></i><b>10.4</b> Adding a Discrete Variable</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="graph-library.html"><a href="graph-library.html#two-variables-continuous-x-and-y"><i class="fa fa-check"></i><b>11</b> Two Variables: Continuous X and Y</a>
<ul>
<li class="chapter" data-level="11.1" data-path="graph-library.html"><a href="graph-library.html#scatter-plot"><i class="fa fa-check"></i><b>11.1</b> Scatter Plot</a></li>
<li class="chapter" data-level="11.2" data-path="graph-library.html"><a href="graph-library.html#regression-line"><i class="fa fa-check"></i><b>11.2</b> Regression Line</a></li>
<li class="chapter" data-level="11.3" data-path="graph-library.html"><a href="graph-library.html#scatter-plot-with-regression"><i class="fa fa-check"></i><b>11.3</b> Scatter Plot with Regression</a></li>
<li class="chapter" data-level="11.4" data-path="graph-library.html"><a href="graph-library.html#adding-discrete-variables"><i class="fa fa-check"></i><b>11.4</b> Adding Discrete Variables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="graph-library.html"><a href="graph-library.html#two-variables-discrete-x-continuous-y"><i class="fa fa-check"></i><b>12</b> Two Variables: Discrete X, Continuous Y</a>
<ul>
<li class="chapter" data-level="12.1" data-path="graph-library.html"><a href="graph-library.html#box-plot"><i class="fa fa-check"></i><b>12.1</b> Box Plot</a></li>
<li class="chapter" data-level="12.2" data-path="graph-library.html"><a href="graph-library.html#dot-plot"><i class="fa fa-check"></i><b>12.2</b> Dot Plot</a></li>
<li class="chapter" data-level="12.3" data-path="graph-library.html"><a href="graph-library.html#violin-plot"><i class="fa fa-check"></i><b>12.3</b> Violin Plot</a></li>
<li class="chapter" data-level="12.4" data-path="graph-library.html"><a href="graph-library.html#adding-raw-data"><i class="fa fa-check"></i><b>12.4</b> Adding Raw data</a></li>
<li class="chapter" data-level="12.5" data-path="graph-library.html"><a href="graph-library.html#adding-additional-discrete-variables"><i class="fa fa-check"></i><b>12.5</b> Adding Additional Discrete Variables</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="graph-library.html"><a href="graph-library.html#aggregate-data"><i class="fa fa-check"></i><b>13</b> Aggregate Data</a>
<ul>
<li class="chapter" data-level="13.1" data-path="graph-library.html"><a href="graph-library.html#calculating-mean-and-standard-deviation"><i class="fa fa-check"></i><b>13.1</b> Calculating Mean and Standard Deviation</a></li>
<li class="chapter" data-level="13.2" data-path="graph-library.html"><a href="graph-library.html#visualizing-means-and-variation"><i class="fa fa-check"></i><b>13.2</b> Visualizing Means and Variation</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="graph-library.html"><a href="graph-library.html#combining-multiple-plots"><i class="fa fa-check"></i><b>14</b> Combining Multiple plots</a></li>
<li class="chapter" data-level="15" data-path="graph-library.html"><a href="graph-library.html#working-with-color-palettes"><i class="fa fa-check"></i><b>15</b> Working with Color Palettes</a>
<ul>
<li class="chapter" data-level="15.1" data-path="graph-library.html"><a href="graph-library.html#color-palettes-in-rcolorbrewer"><i class="fa fa-check"></i><b>15.1</b> Color Palettes in RColorBrewer</a></li>
<li class="chapter" data-level="15.2" data-path="graph-library.html"><a href="graph-library.html#combining-rcolorbrewer-palettes-with-ggplot"><i class="fa fa-check"></i><b>15.2</b> Combining RColorBrewer Palettes with ggplot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercises.html"><a href="r-exercises.html"><i class="fa fa-check"></i>R Exercises</a></li>
<li class="chapter" data-level="A" data-path="simulating-selection-1.html"><a href="simulating-selection-1.html"><i class="fa fa-check"></i><b>A</b> Simulating Selection</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Primer of Evolution</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="evolutionary-medicine-i-aging-and-diseases-of-civilization" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Chapter 12</span> Evolutionary Medicine I: Aging and Diseases of Civilization<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#evolutionary-medicine-i-aging-and-diseases-of-civilization" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The study of evolutionary biology is frequently seen as a purely academic exercise, albeit one that allows us to better understand—and perhaps appreciate—the living world around us. Over recent decades, however, evolutionary biology has matured from the basic science of understanding the origins and complexity of biological systems to an applied science for solving practical problems faced by humanity. Evolutionary principles are now routinely applied when developing strategies to address issues associated with human and environmental health in a time of rapid change. So, in the final section of this book, we will turn our attention to how we can apply evolutionary principles to better understand who we are, where we came from, and how we can address some of the major challenges faced by our society, especially in the context of human health and medicine.</p>
<p>The analytical tools used by evolutionary biologists to study the form and function of other organisms can, of course, be applied to the study of human form and function—though appropriate caution is always needed when interpreting such research findings. The added level of caution is not necessary because humans are in some way special or different from other organisms; rather, the study of humans bears unique constraints in terms of study design and the modes of inference we have at our disposal. It is simply not ethical to conduct certain experiments with human subjects. As such, we sometimes lack one of the critical scientific tools—the experiment with tightly controlled conditions—that allows for the establishment of causation. Hence, caution is required particularly because we often cannot rule out alternative hypotheses of observable phenomena.</p>
<div id="darwinian-medicine" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> Darwinian Medicine<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#darwinian-medicine" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Despite the limitations of applying evolutionary approaches to understand human nature, incorporation of evolutionary principles into our understanding of human health and disease has lead to important breakthroughs, with implications for the prevention and treatment of both individual and public health issues. While classic biomedical research has focused on understanding the molecular and physiological underpinnings of diseases, Darwinian medicine (or evolutionary medicine) is also concerned with how evolutionary history and evolutionary processes have impacted our propensity to contract diseases. Such approaches have lead to important insights about the biology of cancers, autoimmune diseases, and evolving pathogens. Table 12.1 lists some core principles of evolutionary medicine based on recommendation of The Association of American Medical Colleges and the Howard Hughes Medical Institute (Grunspan et al. 2018). While some medical schools have been slow to adopt the inclusion of evolutionary principles into their curricula, rigorous evolution education is now commonplace among healthcare professionals.</p>
<table>
<caption>Table 12.1:Core principles of evolutionary medicine based on Grunspan et al. (2018)</caption>
<colgroup>
<col width="19%" />
<col width="80%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Topic</th>
<th align="left">Core principle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Types of explanation</td>
<td align="left">Both proximate (mechanistic) and ultimate (evolutionary) explanations are needed to provide a full biological understanding of traits, including those that increase vulnerability to disease.</td>
</tr>
<tr class="even">
<td align="left">Evolutionary processes</td>
<td align="left">All evolutionary processes, including natural selection, genetic drift, mutation, migration and non-random mating, are important for understanding traits and disease.</td>
</tr>
<tr class="odd">
<td align="left">Reproductive success</td>
<td align="left">Natural selection maximizes reproductive success, sometimes at the expense of health and longevity.</td>
</tr>
<tr class="even">
<td align="left">Sexual selection</td>
<td align="left">Sexual selection shapes traits that result in different health risks between sexes.</td>
</tr>
<tr class="odd">
<td align="left">Constraints</td>
<td align="left">Several constraints inhibit the capacity of natural selection to shape traits that are hypothetically optimal for health.</td>
</tr>
<tr class="even">
<td align="left">Trade-off</td>
<td align="left">Evolutionary changes in one trait that improves fitness can be linked to changes in other traits that decrease fitness.</td>
</tr>
<tr class="odd">
<td align="left">Life history</td>
<td align="left">Life history traits, such as age at first reproduction, reproductive lifespan and rate of senescence, are shaped by evolution and have implications for health and disease.</td>
</tr>
<tr class="even">
<td align="left">Levels of selection</td>
<td align="left">Vulnerabilities to disease can result when selection has opposing effects at different levels (<em>e.g.,</em> genetic elements, cells, organisms, kin and other levels).</td>
</tr>
<tr class="odd">
<td align="left">Phylogeny</td>
<td align="left">Tracing phylogenetic relationships for species, populations, traits or pathogens can provide insights into health and disease.</td>
</tr>
<tr class="even">
<td align="left">Coevolution</td>
<td align="left">Coevolution among species can influence health and disease (<em>e.g.</em>, evolutionary arms races and mutualistic relationships such as those seen in the microbiome).</td>
</tr>
<tr class="odd">
<td align="left">Plasticity</td>
<td align="left">Environmental factors can shift developmental trajectories in ways that influence health, and the plasticity of these trajectories can be the product of evolved adaptive mechanisms.</td>
</tr>
<tr class="even">
<td align="left">Defenses</td>
<td align="left">Many signs and symptoms of disease (<em>e.g.</em>, fever) are useful defenses, which can be pathological if dysregulated.</td>
</tr>
<tr class="odd">
<td align="left">Mismatch</td>
<td align="left">Disease risks can be altered for organisms living in environments that differ from those in which their ancestors evolved.</td>
</tr>
<tr class="even">
<td align="left">Cultural practices</td>
<td align="left">Cultural practices can influence the evolution of humans and other species (including pathogens), in ways that can affect health and disease (<em>e.g.</em>, anti-biotic use, birth practices, diet).</td>
</tr>
</tbody>
</table>
<p>We have already covered a wide range of topics associated with core concepts in evolutionary medicine, albeit not always in the explicit context of human health and disease. In this and the next chapter, we will explore select topics in more depth. First, we will examine how mismatches between modern environments and those of our ancestors impact our susceptibility to non–communicable diseases, and explore why we age and die. In the next chapter, we will discuss how evolutionary principles inform our understanding of pathogen spread and evolution, and how we can use cultural practices to impact disease dynamics in our population.</p>
</div>
<div id="diseases-of-civilization" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Diseases of Civilization<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#diseases-of-civilization" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Human populations have undoubtedly evolved a wide variety of adaptations to local environmental conditions and lifestyles. Recent research has not only identified a number of phenotypic traits associated with adaptations to different diets, pathogens, oxygen levels, cold resistance, and exposure to very high or very low levels of UV (Table 12.2), but in many cases also found candidate genes that underlie adaptive trait variation in specific populations (Rees et al 2020). In all of these cases, local adaptation has evolved in response to very specific sources of selection, often over time periods spanning thousands of years. For example, evolution of lactase persistence was associated with the domestication of cattle and other dairy animals about 10,000 years ago, leading to an increase in lactase persistence alleles over the past 5,000 years, until they reached present-day levels (see <a href="evolutionary-mechanisms-i-modeling-selection.html#fig:lactase">Chapter 5</a>). Similarly, human populations that traditionally eat a high-starch diet exhibit a high copy number of amylase genes (AMY1) compared to populations that traditionally eat a low-starch diet (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:amylase">12.1</a>A). AMY1 genes encode the enzyme amylase, which is responsible for catalyzing the hydrolysis of complex cabrohydrates to simple sugars during digestion, and copy number variation is directly correlated with the amount of amylase produced in the saliva (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:amylase">12.1</a>B). The surge of lactase persistence alleles in populations consuming diary and the high amylase copy numbers in populations eating a lot of starchy foods exemplify how evolution has shaped traits associated with digestion in response to cultural practices (<em>i.e.</em>, regional food preferences).</p>
<table>
<caption>Table 12.2: Examples of local adaptation in human populations based on Rees et al. (2020).</caption>
<colgroup>
<col width="62%" />
<col width="37%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Adaptation</th>
<th align="left">Population with adaptations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><u><em>Diet</em></u></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Lactase persistence</td>
<td align="left">Eurasians and Africans</td>
</tr>
<tr class="odd">
<td align="left">Fatty diets</td>
<td align="left">Greenlandic Inuit</td>
</tr>
<tr class="even">
<td align="left">Starchy diets</td>
<td align="left">Across different populations</td>
</tr>
<tr class="odd">
<td align="left">Low selenium levels</td>
<td align="left">Chinese</td>
</tr>
<tr class="even">
<td align="left">Low iron levels</td>
<td align="left">Europeans</td>
</tr>
<tr class="odd">
<td align="left">Low calcium levels</td>
<td align="left">Non-Africans</td>
</tr>
<tr class="even">
<td align="left">Frequent starvation</td>
<td align="left">Samoans</td>
</tr>
<tr class="odd">
<td align="left"><u><em>Pathogens</em></u></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Malaria resistance</td>
<td align="left">Sub-Saharan Africans</td>
</tr>
<tr class="odd">
<td align="left">African sleeping sickness</td>
<td align="left">Western Africans</td>
</tr>
<tr class="even">
<td align="left">Hepatitis C</td>
<td align="left">Europeans</td>
</tr>
<tr class="odd">
<td align="left"><u><em>Oxidative stress</em></u></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">High altitude</td>
<td align="left">Tibetans, Andeans, and Ethiopians</td>
</tr>
<tr class="odd">
<td align="left">Breath-holding diving</td>
<td align="left">Bajau (Indonesia)</td>
</tr>
<tr class="even">
<td align="left"><u><em>Cold resistance</em></u></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Cold perception</td>
<td align="left">Eurasians</td>
</tr>
<tr class="even">
<td align="left">Energy regulation, metabolism, and cardiovascular function</td>
<td align="left">Siberians</td>
</tr>
<tr class="odd">
<td align="left">Differentiation of brown and brite adipocytes</td>
<td align="left">Greenlandic Inuit</td>
</tr>
<tr class="even">
<td align="left"><u><em>UV exposure</em></u></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Pigmentation changes</td>
<td align="left">Across different populations</td>
</tr>
<tr class="even">
<td align="left">Low vitamin D levels</td>
<td align="left">Northern Europeans</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:amylase"></span>
<img src="Primer2Evolution_files/figure-html/amylase-1.png" alt="A. AMY1 gene copy number in human populations with a high starch diet and populations with a low starch diet. Triangles indicate median copy numbers. [Data](data/12_amylase1.csv) from Perry et al. (2007). B. Copy number variation of AMY1 is directly correlated with the amount amylase protein present in the saliva of individuals, indicating that copy number variation likely impacts function. [Data](data/12_amylase2.csv) from Perry et al. (2007)." width="100%" />
<p class="caption">
Figure 12.1: A. AMY1 gene copy number in human populations with a high starch diet and populations with a low starch diet. Triangles indicate median copy numbers. <a href="data/12_amylase1.csv">Data</a> from Perry et al. (2007). B. Copy number variation of AMY1 is directly correlated with the amount amylase protein present in the saliva of individuals, indicating that copy number variation likely impacts function. <a href="data/12_amylase2.csv">Data</a> from Perry et al. (2007).
</p>
</div>
<p>The onset of agriculture 10,000 years ago was not the last time that human lifestyles have changed dramatically. Perhaps the most important change in recent human evolution was the the industrial revolution, which occurred between 1760 and 1840. This time period was marked by a transition in manufacturing processes, initially in Europe and the United States, where goods previously made by hand were now produced with machines powered by steam and, later, electricity. The industrial revolution led to unprecedented human population growth and population connectivity associated with increased globalization. During this time, almost every aspect of daily life changed. Humans changed the ways they moved around, transitioning from walking to using transportation. The structure of social interactions changed both at larger scales (aggregation of people into growing urban centers) and at smaller scales (changes in family structures and the social roles of men and women). Humans had increasing access to medical treatments, but also increasing exposure to environmental pollutants. And perhaps most significantly, humans completely changed what they ate; today most foods are industrially processed products made from cereal grains, refined sugars, and an excess of trans and saturated fats. In many ways, our modern life bears little resemblance to that of our ancestors.</p>
<div id="modern-hunter-gatherers-and-urbanites" class="section level3 hasAnchor" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Modern Hunter-Gatherers and Urbanites<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#modern-hunter-gatherers-and-urbanites" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The profound changes to our environment and our lifestyles over the past 10,000 years—really, mostly over the past 250 years—are illustrated by comparing modern urbanites and modern hunter-gatherers. Modern hunter-gatherers still obtain the majority of their food by foraging and hunting, similar to most humans prior to the sedentary agricultural societies that arose 10,000 years ago. Modern hunter-gatherers include the Inuit and Iñupiat peoples from Arctic regions in North America and Greenland, the Huaorani and Yąnomamö peoples in South America, the Orang Patek peoples of Palawan, the Pila Nguru of Australia, as well as the Bayaka and San peoples of sub-Saharan Africa, among many others (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:hgdiet">12.2</a>A). While modern urbanites walk an average of 2.5 km per day and burn energy at a rate of about 1.18 times the resting metabolic rate, hunter-gatherers of the !Kung in the Kalahari desert and the Aché in Paraguay walk between 14.9 and 19.2 km per day and burn energy at a rate of 1.71-2.15 times the resting metabolic rate (Cordain et al. 1997). At the same time, hunter-gatherers have a lower caloric intake (~3,000 kcal/day vs. 3,600 kcal/day in an average American), and their diet primarily consists of lean game, fish and shellfish, eggs, fruits, vegetables, and other plant products (although there are staggering geographic and cultural differences; Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:hgdiet">12.2</a>B). Hunter-gatherer diets are also exceedingly nutritious, providing vitamins, minerals, and dietary fibers at rates that far exceed the recommended daily allowances set by the U.S. Food and Nutrition Board (Eaton and Konner 1997).</p>
<div class="figure"><span style="display:block;" id="fig:hgdiet"></span>
<img src="Primer2Evolution_files/figure-html/hgdiet-1.png" alt="A. The San peoples or Bushmen are indiginous hunter-gatherer cultures that are the first cultures of Southern Africa. Photo: [Aino Tuominen](https://ainotuominen.myportfolio.com/projects) (CC0). B. Diet composition of four hunter-gatherer communities, the Inuit of the high Arctic in Canada, the Hiwi of South America, the !Kung of southern Africa, and the Hadza of eastern Africa. [Data](data/12_diet.csv) from Leonard (2002)." width="100%" />
<p class="caption">
Figure 12.2: A. The San peoples or Bushmen are indiginous hunter-gatherer cultures that are the first cultures of Southern Africa. Photo: <a href="https://ainotuominen.myportfolio.com/projects">Aino Tuominen</a> (CC0). B. Diet composition of four hunter-gatherer communities, the Inuit of the high Arctic in Canada, the Hiwi of South America, the !Kung of southern Africa, and the Hadza of eastern Africa. <a href="data/12_diet.csv">Data</a> from Leonard (2002).
</p>
</div>
<p>Not surprisingly, our sedentary lifestyles and splurges rich in sugar, fat, and alcohol have been associated with a wide variety of health issues. Average Americans exhibit higher blood cholesterol levels (204 mg/dl vs. 121 in !Kung and 141 in Inuit) and higher body mass indices (&gt;29 in 2018 vs. 19 in !Kung and 24 in Inuit; Leonard 2002). More over, our modern lifestyles and diets have been associated with a wide variety of health conditions that are comparatively rare or even absent in hunter-gatherer communities: cardiovascular diseases like heart attacks and strokes; cancer in a variety of forms; autoimmune diseases like diabetes, celiac disease, and multiple sclerosis; neurodegenerative diseases like Alzheimer’s and Parkinson’s disease; and mental health issues like depression, anxiety, and substance abuse. Due to the rarity of these diseases in hunter-gatherer communities and the documented links to lifestyle and eating habits, these diseases are also know as “diseases of civilization” or “lifestyle diseases”. The impacts of diseases of civilization are profound. While over 60 % of deaths in the U.S. in 1900 were caused by infectious diseases, by 1940 the majority of deaths were associated with with heart disease, cancers, and non-communicable diseases. Today, 7 out of the 10 leading causes of death in the U.S. are non-communicable and have significant risk factors associated with modern life.</p>
</div>
<div id="old-adaptations-in-a-modern-world" class="section level3 hasAnchor" number="12.2.2">
<h3><span class="header-section-number">12.2.2</span> Old Adaptations in a Modern World<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#old-adaptations-in-a-modern-world" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Human populations—with their large census sizes and accordingly large pools of standing genetic variation—are undoubtedly able to respond to selection and adapt to changing environmental conditions. As explained above, we know how the increase in dairy and starchy foods during the advent of agriculture exerted selection on a variety of digestive enzymes, leading to high frequencies of lactose persistence alleles (<a href="evolutionary-mechanisms-i-modeling-selection.html#fig:lactase">Chapter 5</a>) and high copy numbers of amylase genes (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:amylase">12.1</a>). Evolutionary change in humans is thus certainly responsive to the cultural practices that vary among populations. Still, evolution obviously takes time, and many of the drastic changes in diet and lifestyle only date back a handful of generations. Change in cultural practices—which has happened in just a few generations—has consequently outpaced evolutionary change by natural selection.</p>
<p>As we study adaptive trait variation in humans, we consequently need to ask ourselves what environments humans are actually adapted to. The environments experienced by modern urbanites—and even those of our ancestors within the past few millenia, since the start of recorded history (~5,000 years ago)—bear little resemblance to the environments humans experienced for the vast majority of their evolutionary history. Considering that anatomically modern <em>Homo sapiens</em> emerged around 300,000 years ago, even the advent of agriculture only reaches back into about 3 % of our species’ history. Many of the traits that make us human evolved during the Stone Age, when humans lived predominantly as nomadic hunter-gatherers.</p>
<p>Diseases of civilization may therefore be a consequence of mismatch between traits evolved in another environmental context and the environment we are currently experiencing. Traits that were previously adaptive or selectively neutral may suddenly have a negative impact on health and, ultimately, fitness. For example, an apatite for fatty and sugary foods and alcohol may have been adaptive or selectively neutral when these resources were scarce and periodic starvation was common. However, in an age where these goods are perpetually available—thanks to cooperate lobbying and governmental regulation, often at a lower prices than healthier options—excessive intake can lead to obesity, diabetes, and substance abuse, with all of their associated health issues.</p>
<p>In other cases, diseases of civilization may be a consequence of hidden phenotypic variation, uncovered when development is impacted by novel environmental conditions or habits (<em>i.e.</em>, phenotypic plasticity in response to novel environmental cues not present before). For example, myopia (nearsightedness) is rare in hunter-gatherer communities, but 22 % of humans worldwide are myopic to a degree that they require glasses. The incidence of myopia has been drastically increasing since World War I (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:myopia">12.3</a>A) and coincided with the introduction for formalized schooling in many countries. Comparison of the frequency of myopia across countries with different education systems still reveals substantial differences in the prevalence of myopia today (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:myopia">12.3</a>B).</p>
<p>It turns out that the increase in myopia prevalence was an inadvertent consequence of school work that emphasizes near-field visual work, like reading books and working on computer monitors. The visual experience during development influences the growth of the eye, and extensive near-field work ultimately impacts far-field vision. It is important to note that there is also a heritable component to myopia, and people vary in the degree to which they are susceptible to development of myopia (<em>i.e.</em>, there is genetic variation for plasticity in this trait). Essentially, the alleles that control the propensity of an individual to develop myopia in response to near-field visual work were selectively neutral in the past, when such work was comparatively rare. With the change of schooling and workplace practices, however, that hidden propensity to change eye growth in response to an environmental cue became not only visible, but led to suboptimal trait expression that was not previously tested by natural selection. The availability of mitigating measures (glasses, contact lenses, laser surgeries) indicate that alleles increasing susceptibility to myopia will likely remain in human populations at a high frequency.</p>
<div class="figure"><span style="display:block;" id="fig:myopia"></span>
<img src="Primer2Evolution_files/figure-html/myopia-1.png" alt="A. Prevalence of myopia from 1938 to 2013 for four Asian countries. [Data](data/12_myopia.csv) from Morgan et al. (2018). A. Prevalence of myopia for countries with different education systems. [Data](data/12_myopia.csv) from Morgan et al. (2018)." width="100%" />
<p class="caption">
Figure 12.3: A. Prevalence of myopia from 1938 to 2013 for four Asian countries. <a href="data/12_myopia.csv">Data</a> from Morgan et al. (2018). A. Prevalence of myopia for countries with different education systems. <a href="data/12_myopia.csv">Data</a> from Morgan et al. (2018).
</p>
</div>
<p>Diseases of civilization may be prevalent in modern societies because not enough time has passed to match our bodies to our novel lifestyles. In other words, diseases of civilization are a symptom of a lack of adaptation; as a population, we have not yet evolved the defenses necessary to fend off many perils of modern life (<em>e.g.</em>, sedentary lifestyles and high-calorie diets). Studying diseases of civilization from an evolutionary perspective allows us to better understand why their prevalence is so high. While these insights may not be as important for developing treatments for such diseases (that is explored by biomedical research, which illuminates the proximate causes of disease), understanding the ultimate causes behind disease development is critical for disease prevention. Understanding how our traits from ancient times respond to the novel environmental conditions that we have created for ourselves is key to preventative healthcare that evaluates how environmental factors and lifestyle choices affect disease risk.</p>
</div>
<div id="an-example-breast-cancer" class="section level3 hasAnchor" number="12.2.3">
<h3><span class="header-section-number">12.2.3</span> An Example: Breast Cancer<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#an-example-breast-cancer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One of the most common types of cancer is breast cancer. In the U.S. alone, there are over 284,000 new cases and over 44,000 deaths every single year, primarily in women. I want to use breast cancer as a case study to explore how evolutionary perspectives might inform our understanding and the prevention of a disease, as breast cancer has a number of risk factors that relate to evolutionary genetics and diseases of civilization.</p>
<p>Research has indicated that genetic predisposition plays a role in the development of some breast cancers. Particularly, mutations in the <em>BRCA1</em> and <em>BRCA2</em> genes—two tumor suppressor genes—have been associated with an elevated risk for breast cancer in women. While only 5-10 % of breast cancers are associated with BRCA mutations, 40-65 % of women with a BRCA mutations are treated for breast cancer within their lifetime. As a consequence, only 59 % of women with a <em>BRCA1</em> mutation and 71 % of women with a <em>BRCA2</em> mutation reach an age of 70 (compared 84 % of women without this mutation). Hence, selection against mutations in BRAC genes should be strong, and deleterious alleles should be accordingly rare. Population genetic analyses, however, have indicated that 1 in 381 women (0.26%) carries a <em>BRAC1</em> mutation and 1 in 277 (0.36%) a <em>BRAC</em> 2 mutation, and these allele frequencies are much higher than expected considering the high incidence of disease. Interestingly, at least <em>BRAC1</em> appears to be under positive selection in humans and chimpanzees, suggesting that natural selection acts to promote alternative genetic variants at that locus rather than removing them (Huttley et al. 2000). Cochran and colleagues (2006) proposed that mutations in <em>BRAC1</em> stimulate neural growth and might be linked to higher cognitive abilities, providing fitness benefits that balance costs associated with cancer development. However, rigorous tests of this hypothesis are still lacking.</p>
<p>Besides genetic factors, environmental and lifestyle factors also affect breast cancer risk. Early work attempting to explain the high frequency of breast cancer focused on the hypothesis that this type of cancer was caused by a pathogen. In mice, tumors in the mammary glands are frequently associated with a viral infection (mouse mammary tumor virus, MMTV), and researchers have hypothesized that MMTV or MMTV-like viruses could also be responsible for causing tumors in women. This hypothesis was supported by two primary findings: (1) Some cells isolated from human breast cancers indeed exhibited DNA sequences which resembled MMTV. (2) Breast cancer rates in Europe appeared to be correlated with the presence of different species of mice, <em>Mus domesticus</em>, which occurs in western Europe, and <em>M. musculus</em>, which occurs in eastern Europe. MMTV frequencies differ significantly between the two species and are much higher in <em>M. domesticus</em>. Intriguingly, breast cancer rates in women are higher in countries with <em>M. domesticus</em> than in countries with <em>M. musculus</em>, with countries in the hybrid zone between the two species being intermediate (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:bcancer">12.4</a>A). Some researchers have taken this as evidence for a causal link between MMTV and human breast cancers, even though no MMTV particles have ever been found in human cancer samples. Correlation, in this case, may consequently not be causation. If you consider the distributional border that separates the two species (it runs through Germany, south through the Balkans), it does not take a whole lot of detective work to come up with a tangible list of confounding variables that might also impact breast cancer risk. The distribution of the two mouse species is actually paralleled by major socioeconomic differences between countries in western and eastern Europe, which arose as a consequence of the Iron Curtain that separated the Soviet block from the West and its allied states. For over 50 years, lifestyles across the divided Europe were drastically different.</p>
<p>The question then becomes: what are the lifestyle changes that potentially impact breast cancer risks? Besides obesity and substance abuse, changes in family planning and reproductive medicine have been associated with the development of breast cancers. Women in the western world, on average, have relatively few children, and many use hormonal birth control that strictly manages menstrual cycling. Most women in our society have 9-12 menstrual cycles per year until they reach menopause. This high rate of cycling, however, seems to be a relatively new phenomenon. In more traditional societies, where women bear more children and contraceptives are less common, menstrual cycles are much more irregular throughout women’s life. For example, pre-menopausal Dogon women from Mali on average have only three menstrual cycles over a period of two years (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:bcancer">12.4</a>B), which is about 85 % less than women in our society. The reduced number of menstrual cycles in Dogon women is not associated with a later onset of menarche or an early onset of menopause, but with a lower frequency of cycles—especially in women aged 20-34 (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:bcancer">12.4</a>C). Women of that age have a reduced number of cycles because they are either pregnant or are going through amenorrhea associated with lactation.</p>
<p>So, what might be the causal relationship between menstrual cycling and breast cancer? Pulses of estrogen and progesterone in the post-ovulatory phase of the menstrual cycle stimulate the proliferation of breast tissues, leading to the cyclical changes in breast size and shape experienced by many women. Signals for cell proliferation, however, are not only received by healthy breast cells, but also cells that exhibit somatic mutations and are potential precursors to tumors. Hence, the higher frequency of menstrual cycles increases the number of growth signals potential cancer cells receive over the course of a woman’s life, and thus, the likelihood that malignant tumors eventually develop. The link between menstrual cycling and breast cancer risk is not only supported by comparisons of menstruation rates between cultures, but also within our own society. For example, late onset menarche and early onset menopause that reduce the number of lifetime menstrual cycles are also correlated with breast cancer risk (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:bcancer">12.4</a>D). Finally, breast cancer risk is not only associated with the number of hormone surges that coincide with menstrual cycling, but also with the strength of the hormone peak. For example, women in industrialized nations that have a comparatively high energy intake also exhibit higher progesterone concentrations during the post-ovulatory phase, which in turn are correlated with the incidence of breast cancers across countries (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:bcancer">12.4</a>E).</p>
<p>The high rate of breast cancer in our society is therefore at least in part a consequence of changed habits in reproduction and family planning. An inadvertent consequence of a reduced number of pregnancies and hormonal birth control is the increase in growth stimuli received by cancer precursors after every ovulation. Pharmaceutical research has consequently started to develop methods of hormonal birth control that reduce the number cycles each year to 1-4 (<em>e.g.</em>, Seaonale, Quartette, and Amethyst). Ironically, these drugs were—and still are—catching on slowly, because monthly menstrual cycling is perceived as natural and reduced cycling as artificial, and thus, perhaps unhealthy. As a consequence, extended-use birth control drugs are typically advertised for the convenience they provide and not for the potential health benefits.</p>
<div class="figure"><span style="display:block;" id="fig:bcancer"></span>
<img src="Primer2Evolution_files/figure-html/bcancer-1.png" alt="A. Incidence of breast cancer in women from different countries that overlap with the distribiution of *M. domesticus* (western Europe), *M. musculus* (eastern Europe), or the hybrid zone between the two species. [Data](data/12_bc1.csv) from Stewart et al. (2000). B. The number of menstrual cycles Dogon women exhibit over a two year period. On average, adult, pre-menopausal women in that society only have 3 cycles over that period. [Data](data/12_bc2.csv) from Strassman (1999). C. The number of menstural cycles over a two year period in Dogon women as a function of age. Menstrual cycling dips in 20-34-year old as a consequence of pregnancy and amenorrhea. [Data](data/12_bc3.csv) from Strassman (1999). D. Breast cancer risk as a function of the onset of menarche and menopause. Having a late onset of menarche or an early onset of menopause reduces breast cancer risk. [Data](data/12_bc4.csv) from Collaborative Group on Hormonal Factors in Breast Cancer (2012). E. xxx. [Data](data/12_bc5.csv) from Jasieńska and Thune (2001)." width="100%" />
<p class="caption">
Figure 12.4: A. Incidence of breast cancer in women from different countries that overlap with the distribiution of <em>M. domesticus</em> (western Europe), <em>M. musculus</em> (eastern Europe), or the hybrid zone between the two species. <a href="data/12_bc1.csv">Data</a> from Stewart et al. (2000). B. The number of menstrual cycles Dogon women exhibit over a two year period. On average, adult, pre-menopausal women in that society only have 3 cycles over that period. <a href="data/12_bc2.csv">Data</a> from Strassman (1999). C. The number of menstural cycles over a two year period in Dogon women as a function of age. Menstrual cycling dips in 20-34-year old as a consequence of pregnancy and amenorrhea. <a href="data/12_bc3.csv">Data</a> from Strassman (1999). D. Breast cancer risk as a function of the onset of menarche and menopause. Having a late onset of menarche or an early onset of menopause reduces breast cancer risk. <a href="data/12_bc4.csv">Data</a> from Collaborative Group on Hormonal Factors in Breast Cancer (2012). E. xxx. <a href="data/12_bc5.csv">Data</a> from Jasieńska and Thune (2001).
</p>
</div>
</div>
</div>
<div id="why-we-age-and-die" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Why We Age… and Die<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#why-we-age-and-die" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The inevitability of aging and death is an intriguing biological paradox that warrants closer examination from an evolutionary perspective. Both scientists and science fiction writers have been obsessed with the fountain of youth and the secret to eternal life—without much success. So why is it that we age and ultimately die? Why hasn’t natural selection favored alleles that prolong survival extensively—or even eternally—to allow for many bouts of reproduction? After all, it seems like an immortal variant would have a fitness advantage over any variant that succumbs to an early death. When pondering why we age and die, Nobel laureate Francis Jacob said it most elegantly in 1982 :</p>
<blockquote>
<p>“It is truly amazing that a complex organism, formed through an extraordinarily intricate process of morphogenesis, should be unable to perform the much simpler task of merely maintaining what already exists.”</p>
<p>Francis Jacob, 1982</p>
</blockquote>
<p>The inability of organisms to maintain their bodies is the ultimate cause of aging (also known as senescence): a decline in survivability and reproductive capacity with increasing age. Aging is almost universal in multicellular organisms and even present in some microbes, where asymmetric cell divisions leave behind larger mother cells with reduced viability. Only a few organisms that appear to defy age-related deterioration have been found so far, and they include some flatworms (Platyhelminthes) and small cnidarians (<em>Hydra</em>) with asexual reproduction.</p>
<div id="rate-of-living-hypothesis" class="section level3 hasAnchor" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Rate of Living Hypothesis<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#rate-of-living-hypothesis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One hypothesis as to why natural selection has not favored alleles for longer lifespans (or even eternal life) is that it simply can’t. Perhaps natural selection has already pushed the lifespan to the maximum , such that the maximum lifespans observed in different species today are bound by intrinsic constraints that are impossible for natural selection to overcome. The rate of living hypothesis posits that ageing is an inadvertent byproduct of metabolic activity. As cells live and proliferate, they continue to accrue irreparable damage to the point that sustaining proper function is impossible.</p>
<p>The rate of living hypothesis makes two testable predictions: (1) The rate of aging in different species should be correlated with the pace of life. Organisms that have a very fast mass-specific metabolism (<em>e.g.</em>, bats and hummingbirds) should age comparatively fast and accordingly have short lifespans, while aging in those with slow mass-specific metabolism (<em>e.g.</em>, sloths and some deep-sea animals) should age much slower and have longer lifespans. (2) Because organisms have already been selected to resist and repair damage at their maximum capacity and lifespan is constrained by other factors, species should not be able to evolve longer lifespans.</p>
<div id="prediction-1-metabolism-and-aging" class="section level4 unnumbered hasAnchor">
<h4>Prediction 1: Metabolism and Aging<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#prediction-1-metabolism-and-aging" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If aging was an inadvertent consequence of metabolic activity, we would expect clear correlations between mass-specific energy expenditure (<em>i.e.</em>, metabolic rate) and lifespan. Some organisms should live fast and die young, while others live more slowly and die old. A wide variety of approaches have been used to test this prediction. For example, if the rate of living theory were true, all organisms should have roughly the same lifetime energy expenditure—but it turns out lifetime energy expenditure varies drastically, even among species of mammals. More direct tests have looked at correlations between metabolic rate and lifespan, and again support for the hypothesis is mixed at best. While there is a negative correlation between energy expenditure and lifespan among mammals, the same correlation is absent among birds (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:ltee">12.5</a>A-B). More over, intraspecific variation in metabolism of mice was positively correlated with lifespan; mice with higher metabolic activity actually lived longer than those with lower metabolic activity (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:ltee">12.5</a>C), a pattern opposite of that predicted by the rate of living hypothesis. Consequently, neither patterns of lifetime energy expenditure nor correlations between energy expenditure and lifespan support the idea that there are internal constrains associated with metabolism to explain why organisms age.</p>
<div class="figure"><span style="display:block;" id="fig:ltee"></span>
<img src="Primer2Evolution_files/figure-html/ltee-1.png" alt="A. Relationship between daily energy expenditure and life span across different species of birds. The two variables are not significantly correlated. [Data](data/12_metabolism_birds.csv) from Speakman (2005). B. Relationship between daily energy expenditure and life span across different species of mammals There is a weak negative correlation between the two variables. [Data](data/12_metabolism_mammals.csv) from Speakman (2005). C. Intraspecific variation of metabolic intensity in laboratory mice is positively correlated with lifespan, opposite of what is predicted by the rate of living hypothesis. [Data](data/12_metabolism_mice.csv) from Speakman et al. (2002)." width="100%" />
<p class="caption">
Figure 12.5: A. Relationship between daily energy expenditure and life span across different species of birds. The two variables are not significantly correlated. <a href="data/12_metabolism_birds.csv">Data</a> from Speakman (2005). B. Relationship between daily energy expenditure and life span across different species of mammals There is a weak negative correlation between the two variables. <a href="data/12_metabolism_mammals.csv">Data</a> from Speakman (2005). C. Intraspecific variation of metabolic intensity in laboratory mice is positively correlated with lifespan, opposite of what is predicted by the rate of living hypothesis. <a href="data/12_metabolism_mice.csv">Data</a> from Speakman et al. (2002).
</p>
</div>
</div>
<div id="prediction-2-selection-on-life-span" class="section level4 unnumbered hasAnchor">
<h4>Prediction 2: Selection on Life Span<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#prediction-2-selection-on-life-span" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If intrinsic constraints prevented natural selection from favoring longer lifespan, selection on lifespan should have no evolutionary effects. To test this hypothesis, researchers have used a number of selection experiments where they control when organisms reproduce. For example, selection experiments using <em>Drosophila melanogaster</em> continuously propagated offspring that were produced by young adults (early reproducing) or by older individuals that were towards the maximum lifespan (late reproducing). Contrary to the prediction of the rate of living hypothesis, the longevity of flies in the late-reproducing selection lines increased substantially from around 35 to almost 70 days, a 100 % increase, in just 20 generations (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:sellong">12.6</a>A). Reversal of selection in generation 19 also lead to a decrease of longevity, indicating that lifespan can evolve rapidly in either direction (gray line in Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:sellong">12.6</a>A). The evolution of longer lifespans would be consistent with the rate of living hypothesis if flies that evolved a longer lifespan also evolved lower metabolic rates. While flies with postponed senescence indeed have a lower metabolic rate compared to control flies in the first two weeks of their lives, these differences disappear later in life (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:sellong">12.6</a>B), and the overall magnitude of difference in metabolic rate is not sufficient to explain observed differences in longevity.</p>
<div class="figure"><span style="display:block;" id="fig:sellong"></span>
<img src="Primer2Evolution_files/figure-html/sellong-1.png" alt="A. Evolution of lifespan in selection lines that either reproduce early or late in life. Not the increase in lifespan especially in late-reproducing flies and the decrease in lifespan once selection in reversed. [Data](data/12_selection_longevity.csv) form Luckinbill and Clare (1985). B. The evolution of increased lifespan leads to a decrease of metabolic rates, but only in the first two weeks of a fly's life. [Data](data/12_old-mr.csv) form Service (1987)." width="100%" />
<p class="caption">
Figure 12.6: A. Evolution of lifespan in selection lines that either reproduce early or late in life. Not the increase in lifespan especially in late-reproducing flies and the decrease in lifespan once selection in reversed. <a href="data/12_selection_longevity.csv">Data</a> form Luckinbill and Clare (1985). B. The evolution of increased lifespan leads to a decrease of metabolic rates, but only in the first two weeks of a fly’s life. <a href="data/12_old-mr.csv">Data</a> form Service (1987).
</p>
</div>
<p>While the rate of living hypothesis and related ideas (<em>e.g.</em>, genomic instability, telomere attrition, and epigenetic alterations) have stimulated diverse research projects about why we age and uncovered important proximate mechanisms of aging, the central premises of these ideas do not hold up to scrutiny. There does not appear to be a universal intrinsic constraint that limits how long cells or organisms can live, and lifespan can clearly evolve in either direction when selection is applied. So, if longer lifespans are technically possible, why is it that they do not evolve?</p>
</div>
</div>
<div id="evolutionary-theories-of-aging" class="section level3 hasAnchor" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Evolutionary Theories of Aging<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#evolutionary-theories-of-aging" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Evolutionary explanations for aging focus less on the inability of organisms to repair damage that accrues from metabolic activity, and more on the costs and benefits associated with a failure to repair damage as it arises. As in the rate of living hypothesis, aging from an evolutionary perspective is a consequence of gradual decay—but early death does not necessarily translate to lower fitness. To examine the relationship between aging and fitness, we will focus on two non-mutually exclusive hypotheses: (1) The mutation accumulation hypothesis posits that the costs associated with a failure to repair damage and the resulting aging are minimal. (2) The antagonistic pleitropy hypothesis proposes that there may even be benefits associated with with a failure to repair damage and the resulting aging.</p>
<div id="mutation-accumulation-hypothesis" class="section level4 unnumbered hasAnchor">
<h4>Mutation-Accumulation Hypothesis<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#mutation-accumulation-hypothesis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The mutation-accumulation hypothesis explains aging through a decline in the effectiveness of selection as organisms age. The older an individual is, the lower its chances are to produce future offspring (this future reproductive potential is also called the residual reproductive value). Hence, the residual reproductive value declines as a function of age. If a deleterious mutation arises that causes a loss of function early in life, the mutation is strongly selected against, because the residual reproductive value for young individuals is high and the fitness consequences of an early-acting loss of function mutation are accordingly high. However, if a deleterious mutation causes a similar loss of function much later in life, the fitness costs are much lower because the residual reproductive value is also lower. In other words, if a deleterious mutation unfolds its effects late it life, that mutation will already have been passed on to the next generation before the carrier ever experiences the detrimental effects. The detrimental effects are simply not visible to natural selection until it is too late and the deleterious alleles have already been inherited by individuals of the next generation. Consequently, deleterious mutations that unfold their effects late in life can accumulate in a population over time because selection against those mutations is weak.</p>
<p>Experiments have shown that deleterious mutations behind aging can indeed accumulate in populations. For example, Reed and Bryant (2000) studied large and small populations of houseflies (<em>Musca domestica</em>). Normally, male houseflies live for about 28 days and females for about 36 days, but the researchers only allowed the flies to reproduce for four or five days after they reached sexual maturity. Hence, any deleterious mutations that unfolded their effects after day five of a fly’s adult life had suddenly become selectively neutral. After 24 generations of reproduction limited to early adults, the lifespan of flies significantly declined to just 25 days (13 % decline) in males and about 30 days (18 % decline) in females—irrespective of population size (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:delmu">12.7</a>A). This decline in lifespan is a direct consequence of selection’s inability to remove deleterious mutations with late-acting fitness effects from the population. Hence, more rapid aging, in this case, has evolved simply because there were no substantial fitness costs to dying early.</p>
<p>Evidence for mutation accumulation as a cause for aging also comes from natural systems. For example, annual killifish (Nothobranchidae) live in temporary waters associated with African savannas. In this ecosystem, pools fill up during the rainy season but dry out rapidly once the rains stop. Annual killifish are able to survive in these habitats because they have desiccation-resistant eggs that remain dormant during the dry season. Once the rainy season starts, the offspring hatch, rapidly grow to adulthood, spawn to produce the eggs for the next generation, and then die as the water evaporates around them. As a consequence of the temporally limited availability of their habitat, annual killifishes have evolved some of the shortest lifespans of any vertebrates; even under ideal laboratory conditions, these fish only live for 3-12 months, which is much shorter than related species of killifish that live in permanent water bodies. A recent study compared the evolution of genomes in two clades of annual killifishes (genera <em>Callopanchax</em> and <em>Nothobranchius</em>) as well as sister genera of non-annual killifish that live in permanent waters of western Africa (<em>Scriptaphyosemion</em> and <em>Aphyosemion</em>) (Cui et al. 2019). The researchers were particularly interested in whether they might be able to detect evidence for relaxed selection in annual killifish genomes that might be indicative of mutation accumulation. Indeed, annual killifish have much larger portions of the genome associated with relaxed selection compared to closely related species from permanent habitats, which also have longer lifespans (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:delmu">12.7</a>B). The pronounced signatures of relaxed selection indicate that mutations with effects only after the habitats dry up and the fish die anyways have become selectively neutral and are retained in the annual species, while they are purged by purifying selection in the non-annual species.</p>
<p>Finally, humans also offer circumstantial evidence for the accumulation of deleterious effects with late life impacts. Many late-onset genetic diseases are consistent with this hypothesis. For example, hereditary nonpolyposis colon cancer is caused by mutations in DNA repair genes. The median age of diagnosis for this type of cancer is 48 years. So most patients do not see the deleterious effects of such mutations until after the age at which reproduction begins—and in many cases has already ended. Other cancers, as well as Huntington’s disease, have also been proposed to be manifestations of aging caused by late-acting deleterious mutations.</p>
<div class="figure"><span style="display:block;" id="fig:delmu"></span>
<img src="Primer2Evolution_files/figure-html/delmu-1.png" alt="A. Evolution of lifespan in houseflies (*Musca domestica*) whose reproductive was limited to the first five days of their lives. Since deleterious mutations that unfold their effect after the reproductive period become selectively neutral, lifespan decreases as a consequence of the accumulation of deleterious mutations in the populations. [Data](data/12_del_mut.csv) form Reed and Bryant (2000). B. Patterns of genome evolution in annual killifishes and their non-annual relatives. Annual killifish exhibit much stronger signatures of relaxed selection characteristic for mutation accumulation. Note that clade 1 consists of *Callopanchax* (annual) and *Scriotaphyosemion* (non-annual); clade 2 of *Nothobranchius* (annual) and *Aphyosemion* (non-annual). [Data](data/12_killifish.csv) form Cui et al. (2019)." width="100%" />
<p class="caption">
Figure 12.7: A. Evolution of lifespan in houseflies (<em>Musca domestica</em>) whose reproductive was limited to the first five days of their lives. Since deleterious mutations that unfold their effect after the reproductive period become selectively neutral, lifespan decreases as a consequence of the accumulation of deleterious mutations in the populations. <a href="data/12_del_mut.csv">Data</a> form Reed and Bryant (2000). B. Patterns of genome evolution in annual killifishes and their non-annual relatives. Annual killifish exhibit much stronger signatures of relaxed selection characteristic for mutation accumulation. Note that clade 1 consists of <em>Callopanchax</em> (annual) and <em>Scriotaphyosemion</em> (non-annual); clade 2 of <em>Nothobranchius</em> (annual) and <em>Aphyosemion</em> (non-annual). <a href="data/12_killifish.csv">Data</a> form Cui et al. (2019).
</p>
</div>
</div>
<div id="antagonistic-pleiotropy-hypothesis" class="section level4 unnumbered hasAnchor">
<h4>Antagonistic-Pleiotropy Hypothesis<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#antagonistic-pleiotropy-hypothesis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The antagonistic-pleiotropy hypothesis explains aging as a consequence of pleiotropic effects that increase reproduction early in life and reduce survivability later in life. Because natural selection weakens as the residual reproductive value decreases, alleles that cause early maturation or elevated reproductive output are favored—even if they simultaneously have deleterious effects later on. For example, a mutant allele might change the way organisms allocate energy to growth, maintenance, and reproduction. If energy is invested disproportionally into the production of offspring early in life, detrimental effects associated with a lack of investment into maintenance and repair can cause individuals to suffer from an earlier decline in function and increased mortality. In this case, aging might evolve not only due to low costs associated with late-acting mutations, but also because the costs are outweighed by fitness benefits early in life.</p>
<p>Experiments with <em>Drosophila</em> and other model organisms provide evidence for the role of antagonistic pleiotropy in the evolution of aging. For example, Zwaan et al. (1995) established different lines of <em>D. melanogaster</em> that were either selected for short or for long lifespans. Similar to the experiment described in Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:sellong">12.6</a>A), both selection regimes caused lifespans to evolve in the predicted direction; they got shorter relative to the control in one treatment and longer relative to the control in the other (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:antpleim">12.8</a>A). However, the change in lifespan did not occur in isolation. Particularly, the evolution of longer lifespans was accompanied by a severe reduction of fecundity (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:antpleim">12.8</a>A), indicating that there is a cost to longevity, as predicted by the antagonistic-pleiotropy hypothesis. Competition experiments using flies with different lifespans have indicated that living longer is not necessarily beneficial, if long-living flies are out-reproduced by flies that might die earlier. This is an important reminder that fitness is not just a function of survival. In fact, a mutation conferring eternal life will always be selected against if it also reduces lifetime reproductive output to the extent that the contribution of a carrier to the next generation’s gene pool is diminished.</p>
<p>While the general evidence for antagonistic pleiotropy’s role in the evolution of aging is mounting, evidence from humans remains scant. One possible candidate for antagonistic pleiotropy is hereditary haemochromatosis, an autosomal recessive disorder associated with iron uptake. While young individuals benefit from enhanced dietary iron absorption in terms of immune function, older individuals face costs associated with raised iron loads, which can cause cardiomyopathy and neurodegenerative diseases later in life (Rodríguez et al 2017). In addition, recent results from genome-wide association studies on diseases that appear at different periods in life also indicated that pleiotropic effects associated with aging may be common in the human genome (Rodríguez et al 2017).</p>
<div class="figure"><span style="display:block;" id="fig:antpleim"></span>
<img src="Primer2Evolution_files/figure-html/antpleim-1.png" alt="A. Selection of either short or long lifespan  in *D. melanogaster* causes clear evolutionary responses in longevity. [Data](data/12_selection_longevity2.csv) form Zwaan et al. (1995). B. Evolution of longer lifespans coincides with drastic reductions in fecundity, indicating antaginistic pleiotropic effects. [Data](data/12_selection_longevity3.csv) form Zwaan et al. (1995)." width="100%" />
<p class="caption">
Figure 12.8: A. Selection of either short or long lifespan in <em>D. melanogaster</em> causes clear evolutionary responses in longevity. <a href="data/12_selection_longevity2.csv">Data</a> form Zwaan et al. (1995). B. Evolution of longer lifespans coincides with drastic reductions in fecundity, indicating antaginistic pleiotropic effects. <a href="data/12_selection_longevity3.csv">Data</a> form Zwaan et al. (1995).
</p>
</div>
</div>
<div id="ecology-and-the-evolution-of-aging" class="section level4 unnumbered hasAnchor">
<h4>Ecology and the Evolution of Aging<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#ecology-and-the-evolution-of-aging" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Mutation accumulation and antagonistic pleiotropy can explain why nearly all organisms age. The core insight is that long life—perhaps contrary to our intuition—is not as important to fitness as making a substantial contribution to the gene pool of the next generation. However, these two hypotheses alone cannot explain why annual killifish die after just 3 months, but greenland sharks live up to 400 years. Clearly, investing into growth and maintenance is actually beneficial under some circumstances. So, what factors determine whether a “live fast and die young” or a “live slow and die old” strategy prevails?</p>
<p>One of the key determinants shaping the evolution of aging is the rate of extrinsic mortality; <em>i.e.</em>, the likelihood that external factors like predation, disease, resource limitation, or exposure to environmental stress kill an organism. If the rate of extrinsic mortality is very high and individuals are unlikely to survive for long periods of time, there is little use in investing energy into maintenance and growth. Energy, in such a case, is best invested into reproduction while still alive. The annual killifishes discussed above are a perfect example. All members of the species will invariably die when their habitats dry at the onset of the dry season. Therefore, the best life history strategy is to grow fast and reproduce as much as possible before it is too late. Investment into repairing cellular damage that has accrued as a consequence of metabolic activity is simply not a priority when your habitat all but vanishes. In contrast, for species with a low rate of extrinsic mortality, fitness may be maximized by growing for a longer period of time, because larger bodies are associated with increasedcompetitiveness and higher fecundity.</p>
<p>Evidence for the role of extrinsic mortality in aging can also be found in other study systems. For example, Shattuck and Williams (2010) compared the lifespan of arboreal and terrestrial mammals. Lifespan was positively correlated with body size, and arboreal species that are exposed to fewer predators exhibited significantly higher longevity than their terrestrial counterparts that are more vulnerable to predation (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:natage">12.9</a>A). Similarly, populations of the Virginia opossum (<em>Didelphis virginiana</em>) age differently depending on their risk of extrinsic mortality. On the mainland, where opossums face a number of predators, extrinsic mortality is high and cumulative survival reaches zero after less than 30 months (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:natage">12.9</a>B). In contrast, opossums on an island in the Gulf of Mexico, which is free of natural predators, have a much higher life expectancy (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:natage">12.9</a>B). Accordingly, mainland and island opossums age differently and differentially allocate resources to maintenance and reproduction. Female opossums on the mainland make a substantial investment into reproduction in their first year after reaching maturity, but their investment declines in the second year—if they are still alive (Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:natage">12.9</a>C). This decline in investment is a consequence of aging and in stark contrast with reproductive investments on the island, where females are able to invest equally into their offspring in year 1 and year 2 of reproduction. Differences in the decline of physiological performance between populations also provides evidence for more rapid aging in mainland opossums.</p>
<p>Along with extrinsic mortality, selection on other life history traits can also affect the evolution of aging in natural populations. For example, selection on body size, offspring number and size, and reproductive intervals may all have inadvertent consequences on the frequency of alleles that affect aging, whether it is through mutation accumulation or antagonistic pleiotropy. Ultimately, the optimal strategy in any ecological context is shaped by trade-offs in how limited time and energy are allocated to different needs (<em>i.e.</em>, growth, maintenance, repair, and reproduction).</p>
<div class="figure"><span style="display:block;" id="fig:natage"></span>
<img src="Primer2Evolution_files/figure-html/natage-1.png" alt="A. Differences in lifespan between arboreal and terrestrial mammals. [Data](data/data/12_arboreal.csv) form Shattuck and Williams (2010). B. Cumulative survival in mainland and island populations of the Virginia opossum (*Didelphis virginiana*). [Data](data/12_possums.csv) form Austad (1993). C. Investment into reproduction of mainland and island opossums in their first and second year of reproduction. [Data](data/12_possrep.csv) form Austad (1993)." width="100%" />
<p class="caption">
Figure 12.9: A. Differences in lifespan between arboreal and terrestrial mammals. <a href="data/data/12_arboreal.csv">Data</a> form Shattuck and Williams (2010). B. Cumulative survival in mainland and island populations of the Virginia opossum (<em>Didelphis virginiana</em>). <a href="data/12_possums.csv">Data</a> form Austad (1993). C. Investment into reproduction of mainland and island opossums in their first and second year of reproduction. <a href="data/12_possrep.csv">Data</a> form Austad (1993).
</p>
</div>
</div>
</div>
</div>
<div id="case-study-evolution-of-aging" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Case Study: Evolution of Aging<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#case-study-evolution-of-aging" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <a href="exercises/BIOL520-ex11.zip">R exercise associated with this chapter</a> contains three components that further explore the evolution of aging. You will first learn how to use life tables to simulate the effects of deleterious mutations and antagonistic pleiotropy on the lifetime reproductive success of individuals in a population. These simulations will allow you to explore the fitness consequences associated with different mutations behind aging in natural populations. In the second part of the exercise, you will take a closer look at the result of two experimental studies. One of them manipulated the reproductive timing of flies and quantified the consequences for the evolution of lifespan. The other explores the fitness consequences of an allele at the Age-1 locus in <em>Caenorhabditis elegans</em>, which causes an 80 % increase in lifespan. Together, these problems should provide you will a deeper understanding of the evolutionary processes underlying the gradual decay of aging organisms.</p>
</div>
<div id="practical-skills-life-table-analysis" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> Practical Skills: Life Table Analysis<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#practical-skills-life-table-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Life table analysis is a tool used in demography and biology to make inferences about age-structured populations. For evolutionary life history analyses, life tables include the probability that an average individual of a population reaches a certain age (survivorship, <em>l</em><sub>x</sub>) and the average reproductive success of individuals in each age group (age-specific reproductive success, <em>m</em><sub>x</sub>). Both of these variables are typically measured in natural populations; we can quantify the annual survivability of individuals in a particular population, we can determine the age at which individuals reach sexual maturity and start to reproduce, and we can quantify how many offspring are produced at any given age.</p>
<p>Table 12.3 provides an example of a basic life table, summarizing the survivorship and age-specific reproductive success for a population with age classes from 0 to 50. In this particular example, individuals have a 90 % chance to survive each year; so the probability that an individual reaches age 1 is 0.9, age 2 is 0.81 (0.9<sup>2</sup>), age 3 is 0.729 (0.9<sup>3</sup>), and so on. It is important to note that the chance of survival from one year to the next may not be constant throughout life. Many species have relatively high mortality as juveniles, and survivability is much higher once individuals reach adulthood (think of the high mortality of ocean sunfish larvae, which are just 2.5 mm long, compared to the mortality of adults that are 3 m long and weigh up to 2.5 tons).</p>
<p>Finally, Table 12.3 also provides an estimate of the age-specific reproductive success of individuals that have survived to that age. In our example, reproductive success is zero in the first 10 years before individuals reach sexual maturity. After that, individuals have a reproductive success of 1 each year for the rest of their lives. Again, in natural populations, age-specific fertility often varies. In longer-lived animals with parental care, for example, reproductive success starts out relatively low in young adults, increases as individuals gain more experience, and eventually declines as consequence of aging.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb136-1" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">50</span></span>
<span id="cb136-2"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb136-2" tabindex="-1"></a>lx <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fl">0.9</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">+</span><span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">51</span>)),<span class="dv">3</span>)</span>
<span id="cb136-3"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb136-3" tabindex="-1"></a>mx <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">11</span>),<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">40</span>))</span>
<span id="cb136-4"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb136-4" tabindex="-1"></a>lt <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(age, lx, mx)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; ">
<table class="table table-striped" style="color: black; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-35">Table 12.1: </span><span id="tab:unnamed-chunk-35">Table 12.2: </span>Table 12.3: Life tables include the age-specific survival probability and reproductive success of an average individual in a population.
</caption>
<thead>
<tr>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Age class
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Survivorship (lx)
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Age-specific reproductive success (mx)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.810
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.729
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.656
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.590
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0.531
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.430
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0.387
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
0.349
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
0.314
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0.282
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
0.254
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.229
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
0.206
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
0.185
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
0.167
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
0.150
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
0.135
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0.122
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
0.109
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
0.098
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
0.089
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
0.080
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
0.072
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
0.065
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
0.058
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
0.052
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
0.047
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
0.042
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
0.038
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
0.034
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
0.031
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
0.028
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
0.025
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
0.023
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
0.020
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
0.018
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
0.016
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
0.015
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0.013
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
0.008
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
47
</td>
<td style="text-align:right;">
0.007
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
0.005
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
</div>
<p>Based on the age-specific survivorship and reproductive success determined empirically in a natural population, we can now calculate the projected reproductive success (rs) of an individual as the product of survivorship (<em>l</em><sub>x</sub>) and age-specific reproductive success (<em>m</em><sub>x</sub>). This value represents the potential reproductive success of an average individual in a population at any given age. For example, the projected reproductive success at age 17 is dependent on the likelihood that an individual survived to that age (0.167) and the age-specific reproductive success (1).</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb137-1" tabindex="-1"></a>lt<span class="sc">$</span>rs <span class="ot">&lt;-</span> <span class="fu">round</span>(lt<span class="sc">$</span>lx<span class="sc">*</span>lt<span class="sc">$</span>mx, <span class="dv">3</span>)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; ">
<table class="table table-striped" style="color: black; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-37">Table 12.3: </span><span id="tab:unnamed-chunk-37">Table 12.4: </span>Measured components
</caption>
<thead>
<tr>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Age class
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Survivorship (lx)
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Age-specific reproductive success (mx)
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
lx*mx
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.810
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.729
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.656
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.590
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0.531
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.430
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0.387
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
0.349
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
0.314
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.314
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0.282
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.282
</td>
</tr>
<tr>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
0.254
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.254
</td>
</tr>
<tr>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.229
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.229
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
0.206
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.206
</td>
</tr>
<tr>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
0.185
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.185
</td>
</tr>
<tr>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
0.167
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.167
</td>
</tr>
<tr>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
0.150
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.150
</td>
</tr>
<tr>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
0.135
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.135
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0.122
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.122
</td>
</tr>
<tr>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
0.109
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.109
</td>
</tr>
<tr>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
0.098
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.098
</td>
</tr>
<tr>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
0.089
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.089
</td>
</tr>
<tr>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
0.080
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.080
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
0.072
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.072
</td>
</tr>
<tr>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
0.065
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.065
</td>
</tr>
<tr>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
0.058
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.058
</td>
</tr>
<tr>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
0.052
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.052
</td>
</tr>
<tr>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
0.047
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.047
</td>
</tr>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
0.042
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.042
</td>
</tr>
<tr>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
0.038
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.038
</td>
</tr>
<tr>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
0.034
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.034
</td>
</tr>
<tr>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
0.031
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.031
</td>
</tr>
<tr>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
0.028
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.028
</td>
</tr>
<tr>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
0.025
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.025
</td>
</tr>
<tr>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
0.023
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.023
</td>
</tr>
<tr>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
0.020
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.020
</td>
</tr>
<tr>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
0.018
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.018
</td>
</tr>
<tr>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
0.016
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.016
</td>
</tr>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
0.015
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.015
</td>
</tr>
<tr>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0.013
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.013
</td>
</tr>
<tr>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.012
</td>
</tr>
<tr>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.011
</td>
</tr>
<tr>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.010
</td>
</tr>
<tr>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.009
</td>
</tr>
<tr>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
0.008
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.008
</td>
</tr>
<tr>
<td style="text-align:right;">
47
</td>
<td style="text-align:right;">
0.007
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.007
</td>
</tr>
<tr>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.006
</td>
</tr>
<tr>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.006
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
0.005
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.005
</td>
</tr>
</tbody>
</table>
</div>
<p>Finally, we can calculate the projected lifetime reproductive success of an individual as the sum of the projected reproductive success at each age:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb138-1" tabindex="-1"></a>ltrs <span class="ot">&lt;-</span> <span class="fu">sum</span>(lt<span class="sc">$</span>rs)</span>
<span id="cb138-2"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb138-2" tabindex="-1"></a><span class="fu">print</span>(ltrs)</span></code></pre></div>
<pre><code>## [1] 3.091</code></pre>
<p>This life table can also be visualized graphically. If we simultaneously plot the survivorship (<em>l</em><sub>x</sub>; blue line in Figure <a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#fig:ltgraph">12.10</a>) and age-specific reproductive success (<em>m</em><sub>x</sub>; green line), then the lifetime reproductive success is the area below the intersection of the two curves (gray shaded area). As you can imagine, increasing survivorship (<em>i.e.</em>, lifting the blue line) will also increase lifetime reproductive success; decreasing survivorship will lower lifetime reproductive success. Similarly, shifting the time of sexual maturity can impact lifetime reproductive success as well.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb140-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb140-2"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb140-2" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">data=</span>lt, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>rs), <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;lightgray&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-3"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb140-3" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data=</span>lt, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>lx), <span class="at">color=</span><span class="st">&quot;#8da0cb&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-4"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb140-4" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data=</span>lt, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>mx), <span class="at">color=</span><span class="st">&quot;#66c2a5&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-5"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb140-5" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Age&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-6"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb140-6" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Value&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-7"><a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#cb140-7" tabindex="-1"></a>    <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:ltgraph"></span>
<img src="Primer2Evolution_files/figure-html/ltgraph-1.png" alt="xxx" width="100%" />
<p class="caption">
Figure 12.10: xxx
</p>
</div>
<p>Life tables are useful because we can now quantify the potential impacts that changing life events have on lifetime reproductive success, a proxy for fitness in many evolutionary analyses. For example, we can simulate the effects of a deleterious mutation that kills individuals at age 30 (<em>i.e.</em>, the blue line abruptly shifts to zero at the 30 mark) and calculate exactly how much lifetime reproductive success (<em>i.e.,</em> how much area under the curve) is lost as a consequence. Similarly, we can simulate the effects of a pleiotropic mutation that increases reproduction early in life (shifting the green line to the left) and reduces survival late in life (again pushing the blue line to zero) to examine potential fitness consequences. This is exactly what you will be doing in the R exercise associated with this chapter.</p>
</div>
<div id="reflection-questions-11" class="section level2 hasAnchor" number="12.6">
<h2><span class="header-section-number">12.6</span> Reflection Questions<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#reflection-questions-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Can you develop testable hypotheses about the proximate and ultimate mechanisms that lead to different diseases of civilization?</p></li>
<li><p>How are evolutionary hypotheses of aging similar to the rate of living hypothesis, and how are they different?</p></li>
<li><p>Is natural selection an important component of evolutionary explanations for aging? Why or why not?</p></li>
<li><p>The antagonistic pleiotropy hypothesis assumes that mutations that are deleterious late in life can have a fitness benefit early in life. What about the opposite scenario? Could a mutation that imposes a cost early in life but provides a fitness advantage late in life also spread in a population?</p></li>
<li><p>How would you expect lifespan to evolve in a population of zoo animals?</p></li>
<li><p>“Most animals age, therefore aging must be an adaptation for something.” What do you think about this statement?</p></li>
</ol>
</div>
<div id="references-12" class="section level2 hasAnchor" number="12.7">
<h2><span class="header-section-number">12.7</span> References<a href="evolutionary-medicine-i-aging-and-diseases-of-civilization.html#references-12" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Austad SN (1993). <a href="https://zslpublications.onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-7998.1993.tb02665.x">Retarded senescence in an insular population of Virginia opossums (<em>Didelphis virginiana</em>)</a>. <em>Journal of Zoology</em> 229, 695–708.</p></li>
<li><p>Cochran G, J Hardy, H Harpending (2006). <a href="https://www.cambridge.org/core/journals/journal-of-biosocial-science/article/abs/natural-history-of-ashkenazi-intelligence/170E96F5581A9F39524DAC717886D945">Natural history of Ashkenazi intelligence</a>. <em>Journal of Biosocial Science</em> 38, 659-693.</p></li>
<li><p>Collaborative Group on Hormonal Factors in Breast Cancer (2012). <a href="https://www.thelancet.com/journals/lanonc/article/PIIS1470-2045(12)70425-4/fulltext">Menarche, menopause, and breast cancer risk: individual participant meta-analysis, including 118 964 women with breast cancer from 117 epidemiological studies</a>. <em>Lancet Oncology</em> 13, 1141–1151.</p></li>
<li><p>Cordain L, RW Gotshall, SB Eaton (1997). Evolutionary aspects of exercise. <a href="https://www.karger.com/Article/Abstract/59601"><em>World Review of Nutrition and Dietetics</em></a> 81: 49-60</p></li>
<li><p>Cui R, T Medeiros, D Willemsen, LNM Iasi, GE Collier, M Graef, … DR Valenzano (2019). <a href="https://www.cell.com/cell/fulltext/S0092-8674(19)30632-4">Relaxed selection limits lifespan by increasing mutation load</a>. <em>Cell</em> 178, 385–399.e20.</p></li>
<li><p>Eaton SB, SB Eaton III, MJ Konner (1997). <a href="https://www.nature.com/articles/1600389">Paleolithic nutrition revisited: a twelve-year retrospective on its nature and implications</a>. <em>European Journal of Clinical Nutrition</em> 51, 207–216.</p></li>
<li><p>Grunspan DZ, RM Nesse, ME Barnes, SE Brownell (2018). <a href="https://academic.oup.com/emph/article/2018/1/13/4774983">Core principles of evolutionary medicine: A Delphi study</a>. <em>Evolution, Medicine, and Public Health</em> 2018, 13–23.</p></li>
<li><p>Huttley GA, S Easteal, MC Southey, A Tesoriero, GG Giles, MR McCredie, … DJ Venter (2000). <a href="https://www.nature.com/articles/ng0800_410">Adaptive evolution of the tumour suppressor BRCA1 in humans and chimpanzees</a>. <em>Nature Genetics</em> 25, 410–413.</p></li>
<li><p>Jasieńska G, I Thune (2001). <a href="https://www.bmj.com/content/322/7286/586">Lifestyle, hormones, and risk of breast cancer</a>. <em>BMJ</em> 322, 586–587.</p></li>
<li><p>Leonard WR (2002). <a href="https://www.jstor.org/stable/26060086">Food for thought</a>. <em>Scientific American</em> 287, 106–115.</p></li>
<li><p>Luckinbill LS, MJ Clare (1985). <a href="https://www.nature.com/articles/hdy198566">Selection for life span in <em>Drosophila melanogaster</em></a>. <em>Heredity</em> 55, 9–18.</p></li>
<li><p>Morgan IG, AN French, RS Ashby, X Guo, X Ding, M He, KA Rose (2018). <a href="https://www.sciencedirect.com/science/article/abs/pii/S1350946217300393?via%3Dihub">The epidemics of myopia: aetiology and prevention</a>. <em>Progress in Retinal and Eye Research</em> 62, 134–149.</p></li>
<li><p>Perry GH, NJ Dominy, KG Claw, AS Lee, H Fiegler, R Redon, … AC Stone (2007). <a href="https://www.nature.com/articles/ng2123">Diet and the evolution of human amylase gene copy number variation</a>. <em>Nature Genetics</em> 39, 1256–1260.</p></li>
<li><p>Reed, D. H., &amp; Bryant, E. H. (2000). <a href="https://www.nature.com/articles/6887370">The evolution of senescence under curtailed life span in laboratory populations of <em>Musca domestica</em> (the housefly</a>). <em>Heredity</em> 85, 115–121.</p></li>
<li><p>Rees JS, S Castellano, AM Andrés (2020). <a href="https://www.cell.com/trends/genetics/fulltext/S0168-9525(20)30070-6">The genomics of human local adaptation</a>. <em>Trends in Genetics</em> 36, 415–428.</p></li>
<li><p>Rodríguez JA, UM Marigorta, DA Hughes, N Spataro, E Bosch, A Navarro (2017). <a href="Rodríguez,%20J.%20A.,%20Marigorta,%20U.%20M.,%20Hughes,%20D.%20A.,%20Spataro,%20N.,%20Bosch,%20E.,%20&amp;%20Navarro,%20A.%20(2017).%20Antagonistic%20pleiotropy%20and%20mutation%20accumulation%20influence%20human%20senescence%20and%20disease.%20Nature%20Ecology%20&amp;%20Evolution,%201(3),%2055.">Antagonistic pleiotropy and mutation accumulation influence human senescence and disease</a>. <em>Nature Ecology &amp; Evolution</em> 1, 55.</p></li>
<li><p>Service PM (1987). <a href="https://www.journals.uchicago.edu/doi/10.1086/physzool.60.3.30162285">Physiological mechanisms of increased stress resistance in <em>Drosophila melanogaster</em> selected for postponed senescence</a>. <em>Physiological Zoology</em> 60, 321–326.</p></li>
<li><p>Shattuck MR, Williams SA (2010). <a href="https://www.pnas.org/content/107/10/4635">Arboreality has allowed for the evolution of increased longevity in mammals</a>. <em>Proceedings of the National Academy of Sciences USA</em> 107, 4635–4639.</p></li>
<li><p>Speakman JR (2005). <a href="https://journals.biologists.com/jeb/article/208/9/1717/9377/Body-size-energy-metabolism-and-lifespan">Body size, energy metabolism and lifespan</a>. <em>Journal of Experimental Biology</em> 208, 1717–1730.</p></li>
<li><p>Speakman JR, C Selman, JS McLaren. EJ Harper (2002). <a href="https://academic.oup.com/jn/article/132/6/1583S/4687881">Living fast, dying when? The link between aging and energetics</a>. <em>Journal of Nutrition</em> 132, S1583–S1597.</p></li>
<li><p>Stewart TH, RD Sage, AF Stewart, DW Cameron (2000). <a href="https://www.nature.com/articles/6690941">Breast cancer incidence highest in the range of one species of house mouse, <em>Mus domesticus</em></a>. <em>British Journal of Cancer</em> 82, 446–451.</p></li>
<li><p>Strassmann BI (1999). <a href="https://www.liebertpub.com/doi/10.1089/jwh.1999.8.193">Menstrual cycling and breast cancer: an evolutionary perspective</a>. <em>Journal of Women’s Health</em> 8, 193–202.</p></li>
<li><p>Zwaan B, R Bijlsma, RF Hoekstra (1995). <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1558-5646.1995.tb02301.x">Direct selection on lifespan in <em>Drosophila melanogaster</em></a>. <em>Evolution</em> 49, 649–659.</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="speciation-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="evolutionary-medicine-ii-evolving-pathogens.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": "nullnull",
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
